import { SITE_CONFIG } from '@/config/site.config';
// ============================================================
// BRANDS CONFIG — Car Brands (BRAND_COUNT below is the real number)
// Each brand: slug, name, priority, system, models
// ============================================================

export type Brand = {
  slug: string;
  name: string;
  /* Diese App hat keine /marken-Route; der Slug bleibt für Bilddateinamen. */
  nameSlug: string;
  priority: 'P1' | 'P2' | 'P3';
  system: string;   // ECU/immobilizer system
  models?: BrandModel[];
  customH1?: string;
  customMetaTitle?: string;
};

/*
 * Nur noch slug und name.
 *
 * Hier standen zusätzlich years und generations. Keine Seite liest sie, aber
 * brands.ts hängt über data/carModels.ts an LeadCaptureForm ("use client") —
 * also wurden 563 Mal die Worte "Alle bouwjaren" an jeden deutschen Besucher
 * ausgeliefert, im JavaScript, wo keine Übersetzungsprüfung je hinsieht.
 */
export type BrandModel = {
  slug: string;
  name: string;
};

export const BRANDS: Brand[] = [
  {
    slug: 'bmw', name: 'BMW', nameSlug: 'bmw', priority: 'P1',
    system: 'CAS2 / CAS3+ / CAS4+ / FEM / BDC',
    models: [
      { slug: '1-serie', name: '1er' },
      { slug: '2-serie', name: '2er' },
      { slug: '3-serie', name: '3er' },
      { slug: '4-serie', name: '4er' },
      { slug: '5-serie', name: '5er' },
      { slug: '6-serie', name: '6er' },
      { slug: '7-serie', name: '7er' },
      { slug: '8-serie', name: '8er' },
      { slug: 'i3', name: 'i3' },
      { slug: 'i4', name: 'i4' },
      { slug: 'i5', name: 'i5' },
      { slug: 'i7', name: 'i7' },
      { slug: 'i8', name: 'i8' },
      { slug: 'ix', name: 'iX' },
      { slug: 'ix1', name: 'iX1' },
      { slug: 'ix2', name: 'iX2' },
      { slug: 'ix3', name: 'iX3' },
      { slug: 'x1', name: 'X1' },
      { slug: 'x2', name: 'X2' },
      { slug: 'x3', name: 'X3' },
      { slug: 'x4', name: 'X4' },
      { slug: 'x5', name: 'X5' },
      { slug: 'x6', name: 'X6' },
      { slug: 'x7', name: 'X7' },
      { slug: 'z3', name: 'Z3' },
      { slug: 'z4', name: 'Z4' },
      { slug: 'm2', name: 'M2' },
      { slug: 'm3', name: 'M3' },
      { slug: 'm4', name: 'M4' },
      { slug: 'm5', name: 'M5' },
      { slug: 'm6', name: 'M6' },
      { slug: 'm8', name: 'M8' },
    ],
  },
  {
    slug: 'mercedes', name: 'Mercedes-Benz', nameSlug: 'mercedes', priority: 'P1',
    system: 'IR / HFM / NEC / EIS / ESL',
    models: [
      { slug: 'a-klasse', name: 'A-Klasse' },
      { slug: 'b-klasse', name: 'B-Klasse' },
      { slug: 'c-klasse', name: 'C-Klasse' },
      { slug: 'cla', name: 'CLA' },
      { slug: 'clk', name: 'CLK' },
      { slug: 'cls', name: 'CLS' },
      { slug: 'e-klasse', name: 'E-Klasse' },
      { slug: 'g-klasse', name: 'G-Klasse' },
      { slug: 'gl', name: 'GL' },
      { slug: 'gla', name: 'GLA' },
      { slug: 'glb', name: 'GLB' },
      { slug: 'glc', name: 'GLC' },
      { slug: 'gle', name: 'GLE' },
      { slug: 'glk', name: 'GLK' },
      { slug: 'gls', name: 'GLS' },
      { slug: 'm-klasse', name: 'M-Klasse' },
      { slug: 'r-klasse', name: 'R-Klasse' },
      { slug: 's-klasse', name: 'S-Klasse' },
      { slug: 'sl', name: 'SL' },
      { slug: 'slc', name: 'SLC' },
      { slug: 'slk', name: 'SLK' },
      { slug: 'sls-amg', name: 'SLS AMG' },
      { slug: 'sprinter', name: 'Sprinter' },
      { slug: 'v-klasse', name: 'V-Klasse' },
      { slug: 'viano', name: 'Viano' },
      { slug: 'vito', name: 'Vito' },
      { slug: 'eqe', name: 'EQE' },
      { slug: 'eqs', name: 'EQS' },
      { slug: 'eqc', name: 'EQC' },
      { slug: 'eqa', name: 'EQA' },
      { slug: 'eqb', name: 'EQB' },
    ],
  },
  {
    slug: 'volkswagen', name: 'Volkswagen', nameSlug: 'volkswagen', priority: 'P1',
    system: 'MQB / MLB / PQ35 / SFD',
    models: [
      { slug: 'caddy', name: 'Caddy' },
      { slug: 'caravelle', name: 'Caravelle' },
      { slug: 'crafter', name: 'Crafter' },
      { slug: 'cross-golf', name: 'Cross Golf' },
      { slug: 'eos', name: 'Eos' },
      { slug: 'euro-van', name: 'Euro Van' },
      { slug: 'fox', name: 'Fox' },
      { slug: 'golf', name: 'Golf' },
      { slug: 'golf-5', name: 'Golf 5' },
      { slug: 'golf-6', name: 'Golf 6' },
      { slug: 'golf-7', name: 'Golf 7' },
      { slug: 'golf-8', name: 'Golf 8' },
      { slug: 'golf-cabrio', name: 'Golf Cabrio' },
      { slug: 'golf-gti', name: 'Golf Gti' },
      { slug: 'golf-plus', name: 'Golf Plus' },
      { slug: 'id3', name: 'ID.3' },
      { slug: 'id4', name: 'ID.4' },
      { slug: 'jetta', name: 'Jetta' },
      { slug: 'kombi', name: 'Kombi' },
      { slug: 'lavida', name: 'Lavida' },
      { slug: 'lt28', name: 'LT28' },
      { slug: 'lupo', name: 'Lupo' },
      { slug: 'maggiolino', name: 'Maggiolino' },
      { slug: 'magotan', name: 'Magotan' },
      { slug: 'multivan', name: 'Multivan' },
      { slug: 'nouvelle', name: 'Nouvelle' },
      { slug: 'coccinelle', name: 'Coccinelle' },
      { slug: 'passat', name: 'Passat' },
      { slug: 'passat-w8', name: 'Passat W8' },
      { slug: 'polo', name: 'Polo' },
      { slug: 'polo-6r', name: 'Polo 6R' },
      { slug: 'rabbit', name: 'Rabbit' },
      { slug: 'routan', name: 'Routan' },
      { slug: 'sagitar', name: 'Sagitar' },
      { slug: 'saveiro', name: 'Saveiro' },
      { slug: 'scirocco', name: 'Scirocco' },
      { slug: 'sharan', name: 'Sharan' },
      { slug: 'tiguan', name: 'Tiguan' },
      { slug: 'touareg', name: 'Touareg' },
      { slug: 'touran', name: 'Touran' },
      { slug: 'transporter', name: 'Transporter' },
      { slug: 'up', name: 'Up' },
      { slug: 'vento', name: 'Vento' },
    ],
  },
  {
    slug: 'audi', name: 'Audi', nameSlug: 'audi', priority: 'P1',
    system: 'MMI / MIB / VW Group',
    models: [
      { slug: 'a1', name: 'A1' },
      { slug: 'a2', name: 'A2' },
      { slug: 'a3', name: 'A3' },
      { slug: 'a4', name: 'A4' },
      { slug: 'a5', name: 'A5' },
      { slug: 'a6', name: 'A6' },
      { slug: 'a7', name: 'A7' },
      { slug: 'a8', name: 'A8' },
      { slug: 'q2', name: 'Q2' },
      { slug: 'q3', name: 'Q3' },
      { slug: 'q5', name: 'Q5' },
      { slug: 'q7', name: 'Q7' },
      { slug: 'q8', name: 'Q8' },
      { slug: 'r8', name: 'R8' },
      { slug: 'tt', name: 'TT' },
      { slug: 'e-tron', name: 'e-tron' },
      { slug: 'q4-e-tron', name: 'Q4 e-tron' },
      { slug: 'e-tron-gt', name: 'e-tron GT' },
      { slug: 's1', name: 'S1' },
      { slug: 's3', name: 'S3' },
      { slug: 's4', name: 'S4' },
      { slug: 's5', name: 'S5' },
      { slug: 's6', name: 'S6' },
      { slug: 's7', name: 'S7' },
      { slug: 's8', name: 'S8' },
      { slug: 'rs3', name: 'RS3' },
      { slug: 'rs4', name: 'RS4' },
      { slug: 'rs5', name: 'RS5' },
      { slug: 'rs6', name: 'RS6' },
      { slug: 'rs7', name: 'RS7' },
      { slug: 'rs-q3', name: 'RS Q3' },
      { slug: 'rs-q8', name: 'RS Q8' },
    ],
  },
  {
    slug: 'volvo', name: 'Volvo', nameSlug: 'volvo', priority: 'P2',
    system: 'Volvo VIDA / DICE / CEM',
    models: [
      { slug: 'c30', name: 'C30' },
      { slug: 'c70', name: 'C70' },
      { slug: 's40', name: 'S40' },
      { slug: 's60', name: 'S60' },
      { slug: 's70', name: 'S70' },
      { slug: 's80', name: 'S80' },
      { slug: 's90', name: 'S90' },
      { slug: 'v40', name: 'V40' },
      { slug: 'v50', name: 'V50' },
      { slug: 'v60', name: 'V60' },
      { slug: 'v70', name: 'V70' },
      { slug: 'v90', name: 'V90' },
      { slug: 'xc40', name: 'XC40' },
      { slug: 'xc60', name: 'XC60' },
      { slug: 'xc70', name: 'XC70' },
      { slug: 'xc90', name: 'XC90' },
      { slug: 'ex30', name: 'EX30' },
      { slug: 'ex90', name: 'EX90' },
      { slug: 'c40', name: 'C40' },
    ],
  },
  {
    slug: 'toyota', name: 'Toyota', nameSlug: 'toyota', priority: 'P1',
    system: 'Smart Key / G chip',
    models: [
      { slug: 'auris', name: 'Auris' },
      { slug: 'avensis', name: 'Avensis' },
      { slug: 'aygo', name: 'Aygo' },
      { slug: 'c-hr', name: 'C-HR' },
      { slug: 'camry', name: 'Camry' },
      { slug: 'celica', name: 'Celica' },
      { slug: 'corolla', name: 'Corolla' },
      { slug: 'corolla-cross', name: 'Corolla Cross' },
      { slug: 'gt86', name: 'GT86' },
      { slug: 'highlander', name: 'Highlander' },
      { slug: 'hilux', name: 'Hilux' },
      { slug: 'iq', name: 'IQ' },
      { slug: 'land-cruiser', name: 'Land Cruiser' },
      { slug: 'mr2', name: 'MR2' },
      { slug: 'prius', name: 'Prius' },
      { slug: 'proace', name: 'Proace' },
      { slug: 'proace-city', name: 'Proace City' },
      { slug: 'rav4', name: 'RAV4' },
      { slug: 'supra', name: 'Supra' },
      { slug: 'urban-cruiser', name: 'Urban Cruiser' },
      { slug: 'verso', name: 'Verso' },
      { slug: 'yaris', name: 'Yaris' },
      { slug: 'yaris-cross', name: 'Yaris Cross' },
      { slug: 'bz4x', name: 'bZ4X' },
    ],
  },
  {
    slug: 'ford', name: 'Ford', nameSlug: 'ford', priority: 'P1',
    system: 'Ford PATS / Passive Anti-Theft System',
    models: [
      { slug: 'b-max', name: 'B-Max' },
      { slug: 'c-max', name: 'C-Max' },
      { slug: 'cougar', name: 'Cougar' },
      { slug: 'courier', name: 'Courier' },
      { slug: 'ecosport', name: 'EcoSport' },
      { slug: 'edge', name: 'Edge' },
      { slug: 'escape', name: 'Escape' },
      { slug: 'escort', name: 'Escort' },
      { slug: 'explorer', name: 'Explorer' },
      { slug: 'f-150', name: 'F-150' },
      { slug: 'fiesta', name: 'Fiesta' },
      { slug: 'focus', name: 'Focus' },
      { slug: 'fusion', name: 'Fusion' },
      { slug: 'galaxy', name: 'Galaxy' },
      { slug: 'grand-c-max', name: 'Grand C-Max' },
      { slug: 'ka', name: 'KA' },
      { slug: 'ka-plus', name: 'KA+' },
      { slug: 'kuga', name: 'Kuga' },
      { slug: 'mondeo', name: 'Mondeo' },
      { slug: 'mustang', name: 'Mustang' },
      { slug: 'mustang-mach-e', name: 'Mustang Mach-E' },
      { slug: 'puma', name: 'Puma' },
      { slug: 'ranger', name: 'Ranger' },
      { slug: 's-max', name: 'S-Max' },
      { slug: 'tourneo', name: 'Tourneo' },
      { slug: 'transit', name: 'Transit' },
      { slug: 'transit-connect', name: 'Transit Connect' },
      { slug: 'transit-courier', name: 'Transit Courier' },
      { slug: 'transit-custom', name: 'Transit Custom' },
    ],
  },
  {
    slug: 'opel', name: 'Opel', nameSlug: 'opel', priority: 'P1',
    system: 'Opel Immobiliser I / II / III',
    models: [
      { slug: 'agila', name: 'Agila' },
      { slug: 'amperia', name: 'Amperia' },
      { slug: 'antara', name: 'Antara' },
      { slug: 'astra', name: 'Astra' },
      { slug: 'calibra', name: 'Calibra' },
      { slug: 'combo', name: 'Combo' },
      { slug: 'corsa', name: 'Corsa' },
      { slug: 'crossland', name: 'Crossland' },
      { slug: 'frontera', name: 'Frontera' },
      { slug: 'insignia', name: 'Insignia' },
      { slug: 'meriva', name: 'Meriva' },
      { slug: 'mokka', name: 'Mokka' },
      { slug: 'movano', name: 'Movano' },
      { slug: 'omega', name: 'Omega' },
      { slug: 'signum', name: 'Signum' },
      { slug: 'karl', name: 'Karl' },
      { slug: 'sintra', name: 'Sintra' },
      { slug: 'speedster', name: 'Speedster' },
      { slug: 'tigra', name: 'Tigra' },
      { slug: 'vectra', name: 'Vectra' },
      { slug: 'vivaro', name: 'Vivaro' },
      { slug: 'zafira', name: 'Zafira' },
    ],
  },
  {
    slug: 'renault', name: 'Renault', nameSlug: 'renault', priority: 'P2',
    system: 'Renault Card Key / UCH',
    models: [
      { slug: 'arkana', name: 'Arkana' },
      { slug: 'austral', name: 'Austral' },
      { slug: 'avantime', name: 'Avantime' },
      { slug: 'captur', name: 'Captur' },
      { slug: 'clio', name: 'Clio' },
      { slug: 'clio-ii', name: 'Clio II' },
      { slug: 'clio-iii', name: 'Clio III' },
      { slug: 'clio-iv', name: 'Clio IV' },
      { slug: 'coach', name: 'Coach' },
      { slug: 'espace', name: 'Espace' },
      { slug: 'espace-iii', name: 'Espace III' },
      { slug: 'espace-iv', name: 'Espace IV' },
      { slug: 'fluence', name: 'Fluence' },
      { slug: 'kadjar', name: 'Kadjar' },
      { slug: 'kangoo', name: 'Kangoo' },
      { slug: 'koleos', name: 'Koleos' },
      { slug: 'kyron', name: 'Kyron' },
      { slug: 'laguna', name: 'Laguna' },
      { slug: 'laguna-ii', name: 'Laguna II' },
      { slug: 'laguna-iii', name: 'Laguna III' },
      { slug: 'latitude', name: 'Latitude' },
      { slug: 'master', name: 'Master' },
      { slug: 'megane', name: 'Megane' },
      { slug: 'megane-e-tech', name: 'Megane E-Tech' },
      { slug: 'megane-ii', name: 'Megane II' },
      { slug: 'megane-iii', name: 'Megane III' },
      { slug: 'megane-iv', name: 'Megane IV' },
      { slug: 'modus', name: 'Modus' },
      { slug: 'safrane', name: 'Safrane' },
      { slug: 'scenic', name: 'Scenic' },
      { slug: 'talisman', name: 'Talisman' },
      { slug: 'trafic', name: 'Trafic' },
      { slug: 'twingo', name: 'Twingo' },
      { slug: 'twizy', name: 'Twizy' },
      { slug: 'zoe', name: 'Zoe' },
    ],
  },
  {
    slug: 'peugeot', name: 'Peugeot', nameSlug: 'peugeot', priority: 'P2',
    system: 'PSA BSI / PIN extractie',
    models: [
      { slug: '106', name: '106' },
      { slug: '107', name: '107' },
      { slug: '108', name: '108' },
      { slug: '206', name: '206' },
      { slug: '206-plus', name: '206+' },
      { slug: '206-cabrio', name: '206 Cabrio' },
      { slug: '207', name: '207' },
      { slug: '208', name: '208' },
      { slug: '301', name: '301' },
      { slug: '306', name: '306' },
      { slug: '306-sb', name: '306 SB' },
      { slug: '306-sc', name: '306 SC' },
      { slug: '307', name: '307' },
      { slug: '308', name: '308' },
      { slug: '406', name: '406' },
      { slug: '406-sb', name: '406 SB' },
      { slug: '406-sc', name: '406 SC' },
      { slug: '406-sv', name: '406 SV' },
      { slug: '407', name: '407' },
      { slug: '607', name: '607' },
      { slug: '806', name: '806' },
      { slug: '806-sb', name: '806 SB' },
      { slug: '806-sc', name: '806 SC' },
      { slug: '807', name: '807' },
      { slug: '1007', name: '1007' },
      { slug: '2008', name: '2008' },
      { slug: '3008', name: '3008' },
      { slug: '4007', name: '4007' },
      { slug: '5008', name: '5008' },
      { slug: '508', name: '508' },
      { slug: 'bipper', name: 'Bipper' },
      { slug: 'boxer', name: 'Boxer' },
      { slug: 'expert', name: 'Expert' },
      { slug: 'partner', name: 'Partner' },
      { slug: 'ranch', name: 'Ranch' },
      { slug: 'rcz', name: 'RCZ' },
      { slug: 'traveller', name: 'Traveller' },
    ],
  },
  {
    slug: 'fiat', name: 'Fiat', nameSlug: 'fiat', priority: 'P2',
    system: 'Fiat Code 2 / Delphi / Marelli',
    models: [
      { slug: '124-spider', name: '124 Spider' },
      { slug: '500', name: '500' },
      { slug: '500c', name: '500C' },
      { slug: '500l', name: '500L' },
      { slug: '500x', name: '500X' },
      { slug: '600', name: '600' },
      { slug: 'barchetta', name: 'Barchetta' },
      { slug: 'bravo', name: 'Bravo' },
      { slug: 'croma', name: 'Croma' },
      { slug: 'doblo', name: 'Doblo' },
      { slug: 'ducato', name: 'Ducato' },
      { slug: 'fiorino', name: 'Fiorino' },
      { slug: 'freemont', name: 'Freemont' },
      { slug: 'grande-punto', name: 'Grande Punto' },
      { slug: 'idea', name: 'Idea' },
      { slug: 'multipla', name: 'Multipla' },
      { slug: 'palio', name: 'Palio' },
      { slug: 'panda', name: 'Panda' },
      { slug: 'punto', name: 'Punto' },
      { slug: 'punto-evo', name: 'Punto Evo' },
      { slug: 'qubo', name: 'Qubo' },
      { slug: 'scudo', name: 'Scudo' },
      { slug: 'sedici', name: 'Sedici' },
      { slug: 'seicento', name: 'Seicento' },
      { slug: 'stilo', name: 'Stilo' },
      { slug: 'talento', name: 'Talento' },
      { slug: 'tipo', name: 'Tipo' },
      { slug: 'ulysse', name: 'Ulysse' },
    ],
  },
  {
    slug: 'seat', name: 'Seat', nameSlug: 'seat', priority: 'P2',
    system: 'VAG Immobiliser / MQB',
    models: [
      { slug: 'alhambra', name: 'Alhambra' },
      { slug: 'altea', name: 'Altea' },
      { slug: 'altea-xl', name: 'Altea XL' },
      { slug: 'arona', name: 'Arona' },
      { slug: 'arosa', name: 'Arosa' },
      { slug: 'ateca', name: 'Ateca' },
      { slug: 'cordoba', name: 'Cordoba' },
      { slug: 'exeo', name: 'Exeo' },
      { slug: 'ibiza', name: 'Ibiza' },
      { slug: 'leon', name: 'Leon' },
      { slug: 'mii', name: 'Mii' },
      { slug: 'tarraco', name: 'Tarraco' },
      { slug: 'toledo', name: 'Toledo' },
    ],
  },
  {
    slug: 'skoda', name: 'Skoda', nameSlug: 'skoda', priority: 'P2',
    system: 'VAG Immobiliser / MQB / SFD',
    models: [
      { slug: 'citigo', name: 'Citigo' },
      { slug: 'enyaq', name: 'Enyaq' },
      { slug: 'fabia', name: 'Fabia' },
      { slug: 'kamiq', name: 'Kamiq' },
      { slug: 'karoq', name: 'Karoq' },
      { slug: 'kodiaq', name: 'Kodiaq' },
      { slug: 'octavia', name: 'Octavia' },
      { slug: 'praktik', name: 'Praktik' },
      { slug: 'rapid', name: 'Rapid' },
      { slug: 'roomster', name: 'Roomster' },
      { slug: 'scala', name: 'Scala' },
      { slug: 'superb', name: 'Superb' },
      { slug: 'yeti', name: 'Yeti' },
    ],
  },
  {
    slug: 'mazda', name: 'Mazda', nameSlug: 'mazda', priority: 'P2',
    system: 'Mazda PATS / Mitsubishi System',
    models: [
      { slug: 'mazda-121', name: 'Mazda 121' },
      { slug: 'mazda-2', name: 'Mazda 2' },
      { slug: 'mazda-3', name: 'Mazda 3' },
      { slug: 'mazda-323', name: 'Mazda 323' },
      { slug: 'mazda-5', name: 'Mazda 5' },
      { slug: 'mazda-6', name: 'Mazda 6' },
      { slug: 'mazda-626', name: 'Mazda 626' },
      { slug: 'bt-50', name: 'BT-50' },
      { slug: 'cx-3', name: 'CX-3' },
      { slug: 'cx-30', name: 'CX-30' },
      { slug: 'cx-5', name: 'CX-5' },
      { slug: 'cx-60', name: 'CX-60' },
      { slug: 'cx-7', name: 'CX-7' },
      { slug: 'cx-9', name: 'CX-9' },
      { slug: 'mx-3', name: 'MX-3' },
      { slug: 'mx-5', name: 'MX-5' },
      { slug: 'rx-8', name: 'RX-8' },
      { slug: 'tribute', name: 'Tribute' },
    ],
  },
  {
    slug: 'kia', name: 'Kia', nameSlug: 'kia', priority: 'P2',
    system: 'Hyundai/Kia Smart Key',
    models: [
      { slug: 'carens', name: 'Carens' },
      { slug: 'carnival', name: 'Carnival' },
      { slug: 'ceed', name: 'Ceed' },
      { slug: 'cerato', name: 'Cerato' },
      { slug: 'ev6', name: 'EV6' },
      { slug: 'ev9', name: 'EV9' },
      { slug: 'niro', name: 'Niro' },
      { slug: 'optima', name: 'Optima' },
      { slug: 'picanto', name: 'Picanto' },
      { slug: 'proceed', name: 'ProCeed' },
      { slug: 'rio', name: 'Rio' },
      { slug: 'sorento', name: 'Sorento' },
      { slug: 'soul', name: 'Soul' },
      { slug: 'sportage', name: 'Sportage' },
      { slug: 'stinger', name: 'Stinger' },
      { slug: 'stonic', name: 'Stonic' },
      { slug: 'venga', name: 'Venga' },
      { slug: 'xceed', name: 'XCeed' },
    ],
  },
  {
    slug: 'hyundai', name: 'Hyundai', nameSlug: 'hyundai', priority: 'P2',
    system: 'Hyundai/Kia Smart Key',
    models: [
      { slug: 'atos', name: 'Atos' },
      { slug: 'bayon', name: 'Bayon' },
      { slug: 'coupe', name: 'Coupe' },
      { slug: 'elantra', name: 'Elantra' },
      { slug: 'excel', name: 'Excel' },
      { slug: 'galloper', name: 'Galloper' },
      { slug: 'getz', name: 'Getz' },
      { slug: 'grandeur', name: 'Grandeur' },
      { slug: 'h-1', name: 'H-1' },
      { slug: 'h200', name: 'H200' },
      { slug: 'i10', name: 'i10' },
      { slug: 'i20', name: 'i20' },
      { slug: 'i30', name: 'i30' },
      { slug: 'i40', name: 'i40' },
      { slug: 'ioniq', name: 'Ioniq' },
      { slug: 'ioniq-5', name: 'Ioniq 5' },
      { slug: 'ioniq-6', name: 'Ioniq 6' },
      { slug: 'ix20', name: 'ix20' },
      { slug: 'ix35', name: 'ix35' },
      { slug: 'kona', name: 'Kona' },
      { slug: 'matrix', name: 'Matrix' },
      { slug: 'nexo', name: 'NEXO' },
      { slug: 'santa-fe', name: 'Santa Fe' },
      { slug: 'sonata', name: 'Sonata' },
      { slug: 'terracan', name: 'Terracan' },
      { slug: 'trajet', name: 'Trajet' },
      { slug: 'tucson', name: 'Tucson' },
      { slug: 'veloster', name: 'Veloster' },
    ],
  },
  {
    slug: 'nissan', name: 'Nissan', nameSlug: 'nissan', priority: 'P2',
    system: 'Nissan NATS / BCM',
    models: [
      { slug: '200sx', name: '200SX' },
      { slug: '350z', name: '350Z' },
      { slug: '370z', name: '370Z' },
      { slug: 'almera', name: 'Almera' },
      { slug: 'almera-tino', name: 'Almera Tino' },
      { slug: 'ariya', name: 'Ariya' },
      { slug: 'cube', name: 'Cube' },
      { slug: 'evalia', name: 'Evalia' },
      { slug: 'gt-r', name: 'GT-R' },
      { slug: 'interstar', name: 'Interstar' },
      { slug: 'juke', name: 'Juke' },
      { slug: 'kubistar', name: 'Kubistar' },
      { slug: 'leaf', name: 'Leaf' },
      { slug: 'maxima', name: 'Maxima' },
      { slug: 'micra', name: 'Micra' },
      { slug: 'murano', name: 'Murano' },
      { slug: 'navara', name: 'Navara' },
      { slug: 'note', name: 'Note' },
      { slug: 'nv200', name: 'NV200' },
      { slug: 'nv250', name: 'NV250' },
      { slug: 'nv300', name: 'NV300' },
      { slug: 'nv400', name: 'NV400' },
      { slug: 'pathfinder', name: 'Pathfinder' },
      { slug: 'patrol', name: 'Patrol' },
      { slug: 'pixo', name: 'Pixo' },
      { slug: 'primastar', name: 'Primastar' },
      { slug: 'primera', name: 'Primera' },
      { slug: 'qashqai', name: 'Qashqai' },
      { slug: 'qashqai2', name: 'Qashqai+2' },
      { slug: 'serena', name: 'Serena' },
      { slug: 'skyline', name: 'Skyline' },
      { slug: 'sunny', name: 'Sunny' },
      { slug: 'terrano', name: 'Terrano' },
      { slug: 'townstar', name: 'Townstar' },
      { slug: 'x-trail', name: 'X-Trail' },
    ],
  },
  {
    slug: 'honda', name: 'Honda', nameSlug: 'honda', priority: 'P2',
    system: 'Honda Immobiliser System',
    models: [
      { slug: 'accord', name: 'Accord' },
      { slug: 'civic', name: 'Civic' },
      { slug: 'cr-v', name: 'CR-V' },
      { slug: 'cr-z', name: 'CR-Z' },
      { slug: 'fr-v', name: 'FR-V' },
      { slug: 'hr-v', name: 'HR-V' },
      { slug: 'insight', name: 'Insight' },
      { slug: 'jazz', name: 'Jazz' },
      { slug: 'legend', name: 'Legend' },
      { slug: 'logo', name: 'Logo' },
      { slug: 'nsx', name: 'NSX' },
      { slug: 'prelude', name: 'Prelude' },
      { slug: 's2000', name: 'S2000' },
      { slug: 'stream', name: 'Stream' },
      { slug: 'e', name: 'e' },
    ],
  },
  {
    slug: 'land-rover', name: 'Land Rover', nameSlug: 'land-rover', priority: 'P3',
    system: 'JLR KVM / RFA / BCM',
    models: [
      { slug: 'defender', name: 'Defender' },
      { slug: 'discovery', name: 'Discovery' },
      { slug: 'discovery-sport', name: 'Discovery Sport' },
      { slug: 'freelander', name: 'Freelander' },
      { slug: 'range-rover', name: 'Range Rover' },
      { slug: 'range-rover-evoque', name: 'Range Rover Evoque' },
      { slug: 'range-rover-sport', name: 'Range Rover Sport' },
      { slug: 'range-rover-velar', name: 'Range Rover Velar' },
    ],
  },
  {
    slug: 'porsche', name: 'Porsche', nameSlug: 'porsche', priority: 'P3',
    system: 'Porsche KESSY / BCM',
    models: [
      { slug: '911', name: '911' },
      { slug: '968', name: '968' },
      { slug: 'boxster', name: 'Boxster' },
      { slug: 'panamera', name: 'Panamera' },
      { slug: 'macan', name: 'Macan' },
      { slug: 'cayenne', name: 'Cayenne' },
      { slug: 'cayman', name: 'Cayman' },
    ],
  },
  {
    slug: 'tesla', name: 'Tesla', nameSlug: 'tesla', priority: 'P3',
    system: 'Tesla Key Card / NFC',
    models: [
      { slug: 'cybertruck', name: 'Cybertruck' },
      { slug: 'model-3', name: 'Model 3' },
      { slug: 'model-s', name: 'Model S' },
      { slug: 'model-x', name: 'Model X' },
      { slug: 'model-y', name: 'Model Y' },
      { slug: 'roadster', name: 'Roadster' },
    ],
  },
  {
    slug: 'lexus', name: 'Lexus', nameSlug: 'lexus', priority: 'P2',
    system: 'Toyota/Lexus Smart Key',
    models: [
      { slug: 'ct', name: 'CT' },
      { slug: 'es', name: 'ES' },
      { slug: 'gs', name: 'GS' },
      { slug: 'is', name: 'IS' },
      { slug: 'lc', name: 'LC' },
      { slug: 'lfa', name: 'LFA' },
      { slug: 'ls', name: 'LS' },
      { slug: 'nx', name: 'NX' },
      { slug: 'rc', name: 'RC' },
      { slug: 'rx', name: 'RX' },
      { slug: 'rz', name: 'RZ' },
      { slug: 'sc', name: 'SC' },
      { slug: 'ux', name: 'UX' },
    ],
  },
  {
    slug: 'mini', name: 'Mini', nameSlug: 'mini', priority: 'P2',
    system: 'BMW CAS / FEM',
    models: [
      { slug: 'clubman', name: 'Clubman' },
      { slug: 'convertible', name: 'Convertible' },
      { slug: 'cooper', name: 'Cooper' },
      { slug: 'countryman', name: 'Countryman' },
      { slug: 'coupe', name: 'Coupe' },
      { slug: 'paceman', name: 'Paceman' },
      { slug: 'roadster', name: 'Roadster' },
    ],
  },
  {
    slug: 'citroen', name: 'Citroën', nameSlug: 'citroen', priority: 'P2',
    system: 'PSA BSI / CAN Bus',
    models: [
      { slug: 'ami', name: 'AMI' },
      { slug: 'berlingo', name: 'Berlingo' },
      { slug: 'c-crosser', name: 'C-Crosser' },
      { slug: 'c-elyse', name: 'C-Elysée' },
      { slug: 'c-zero', name: 'C-Zero' },
      { slug: 'c1', name: 'C1' },
      { slug: 'c2', name: 'C2' },
      { slug: 'c3', name: 'C3' },
      { slug: 'c3-aircross', name: 'C3 Aircross' },
      { slug: 'c3-picasso', name: 'C3 Picasso' },
      { slug: 'c4', name: 'C4' },
      { slug: 'c4-aircross', name: 'C4 Aircross' },
      { slug: 'c4-cactus', name: 'C4 Cactus' },
      { slug: 'c4-picasso', name: 'C4 Picasso' },
      { slug: 'c4-spacetourer', name: 'C4 SpaceTourer' },
      { slug: 'c5', name: 'C5' },
      { slug: 'c5-aircross', name: 'C5 Aircross' },
      { slug: 'c5-x', name: 'C5 X' },
      { slug: 'c6', name: 'C6' },
      { slug: 'c8', name: 'C8' },
      { slug: 'ds3', name: 'DS3' },
      { slug: 'ds4', name: 'DS4' },
      { slug: 'ds5', name: 'DS5' },
      { slug: 'e-mehari', name: 'E-Mehari' },
      { slug: 'grand-c4-picasso', name: 'Grand C4 Picasso' },
      { slug: 'grand-c4-spacetourer', name: 'Grand C4 SpaceTourer' },
      { slug: 'jumper', name: 'Jumper' },
      { slug: 'jumpy', name: 'Jumpy' },
      { slug: 'nemo', name: 'Nemo' },
      { slug: 'saxo', name: 'Saxo' },
      { slug: 'spacetourer', name: 'SpaceTourer' },
      { slug: 'xsara', name: 'Xsara' },
      { slug: 'xsara-picasso', name: 'Xsara Picasso' },
    ],
  },
  {
    slug: 'alfa-romeo', name: 'Alfa Romeo', nameSlug: 'alfa-romeo', priority: 'P3',
    system: 'Marelli / CODE / RFHUB',
    models: [
      { slug: '145', name: '145' },
      { slug: '146', name: '146' },
      { slug: '147', name: '147' },
      { slug: '156', name: '156' },
      { slug: '159', name: '159' },
      { slug: '166', name: '166' },
      { slug: '4c', name: '4C' },
      { slug: '8c', name: '8C' },
      { slug: 'brera', name: 'Brera' },
      { slug: 'giulia', name: 'Giulia' },
      { slug: 'giulietta', name: 'Giulietta' },
      { slug: 'gt', name: 'GT' },
      { slug: 'gtv', name: 'GTV' },
      { slug: 'mito', name: 'MiTo' },
      { slug: 'spider', name: 'Spider' },
      { slug: 'stelvio', name: 'Stelvio' },
      { slug: 'tonale', name: 'Tonale' },
    ],
  },
  {
    slug: 'chery', name: 'Chery', nameSlug: 'chery', priority: 'P3',
    system: 'Chery Immo / Smart Key',
    models: [
      { slug: 'tiggo', name: 'Tiggo' },
      { slug: 'qq', name: 'QQ' },
      { slug: 'arrizo', name: 'Arrizo' }
    ],
  },
  {
    slug: 'chevrolet', name: 'Chevrolet', nameSlug: 'chevrolet', priority: 'P3',
    system: 'GM Global A / Global B',
    models: [
      { slug: 'spark', name: 'Spark' },
      { slug: 'matiz', name: 'Matiz' },
      { slug: 'captiva', name: 'Captiva' },
      { slug: 'cruze', name: 'Cruze' },
      { slug: 'corvette', name: 'Corvette' }
    ],
  },
  {
    slug: 'dacia', name: 'Dacia', nameSlug: 'dacia', priority: 'P3',
    system: 'Renault UCH / HFM',
    models: [
      { slug: 'duster', name: 'Duster' },
      { slug: 'sandero', name: 'Sandero' },
      { slug: 'logan', name: 'Logan' },
      { slug: 'spring', name: 'Spring' }
    ],
  },
  {
    slug: 'daewoo', name: 'Daewoo', nameSlug: 'daewoo', priority: 'P3',
    system: 'GM / Megamos',
    models: [
      { slug: 'matiz', name: 'Matiz' },
      { slug: 'kalos', name: 'Kalos' },
      { slug: 'lanos', name: 'Lanos' }
    ],
  },
  {
    slug: 'daf', name: 'DAF', nameSlug: 'daf', priority: 'P3',
    system: 'DAF Immo (Truck)',
    models: [
      { slug: 'xf', name: 'XF' },
      { slug: 'cf', name: 'CF' },
      { slug: 'lf', name: 'LF' }
    ],
  },
  {
    slug: 'daihatsu', name: 'Daihatsu', nameSlug: 'daihatsu', priority: 'P3',
    system: 'Toyota Immo / 4C / 4D',
    models: [
      { slug: 'cuore', name: 'Cuore' },
      { slug: 'sirion', name: 'Sirion' },
      { slug: 'terios', name: 'Terios' }
    ],
  },
  {
    slug: 'dodge', name: 'Dodge', nameSlug: 'dodge', priority: 'P3',
    system: 'FOBIK / RFHUB',
    models: [
      { slug: 'ram', name: 'RAM' },
      { slug: 'challenger', name: 'Challenger' },
      { slug: 'charger', name: 'Charger' },
      { slug: 'caliber', name: 'Caliber' }
    ],
  },
  {
    slug: 'infiniti', name: 'Infiniti', nameSlug: 'infiniti', priority: 'P3',
    system: 'Nissan NATS / BCM',
    models: [
      { slug: 'q50', name: 'Q50' },
      { slug: 'q30', name: 'Q30' },
      { slug: 'fx35', name: 'FX35' }
    ],
  },
  {
    slug: 'isuzu', name: 'Isuzu', nameSlug: 'isuzu', priority: 'P3',
    system: 'Isuzu Immo / GM',
    models: [
      { slug: 'd-max', name: 'D-Max' },
      { slug: 'n-series', name: 'N-Series' }
    ],
  },
  {
    slug: 'iveco', name: 'Iveco', nameSlug: 'iveco', priority: 'P3',
    system: 'Fiat CODE / BSI',
    models: [
      { slug: 'daily', name: 'Daily' },
      { slug: 'eurocargo', name: 'Eurocargo' }
    ],
  },
  {
    slug: 'jaguar', name: 'Jaguar', nameSlug: 'jaguar', priority: 'P3',
    system: 'KVM / BCM / JLR',
    models: [
      { slug: 'f-type', name: 'F-Type' },
      { slug: 'xf', name: 'XF' },
      { slug: 'xe', name: 'XE' },
      { slug: 'f-pace', name: 'F-Pace' }
    ],
  },
  {
    slug: 'lancia', name: 'Lancia', nameSlug: 'lancia', priority: 'P3',
    system: 'Fiat CODE / BSI',
    models: [
      { slug: 'ypsilon', name: 'Ypsilon' },
      { slug: 'delta', name: 'Delta' }
    ],
  },
  {
    slug: 'maserati', name: 'Maserati', nameSlug: 'maserati', priority: 'P3',
    system: 'Marelli / RFHUB',
    models: [
      { slug: 'ghibli', name: 'Ghibli' },
      { slug: 'levante', name: 'Levante' },
      { slug: 'quattroporte', name: 'Quattroporte' }
    ],
  },
  {
    slug: 'mitsubishi', name: 'Mitsubishi', nameSlug: 'mitsubishi', priority: 'P3',
    system: 'ETACS / KOS',
    models: [
      { slug: 'outlander', name: 'Outlander' },
      { slug: 'space-star', name: 'Space Star' },
      { slug: 'colt', name: 'Colt' },
      { slug: 'asx', name: 'ASX' }
    ],
  },
  {
    slug: 'rolls-royce', name: 'Rolls Royce', nameSlug: 'rolls-royce', priority: 'P3',
    system: 'BMW CAS / FEM / BDC',
    models: [
      { slug: 'phantom', name: 'Phantom' },
      { slug: 'ghost', name: 'Ghost' },
      { slug: 'cullinan', name: 'Cullinan' }
    ],
  },
  {
    slug: 'rover', name: 'Rover', nameSlug: 'rover', priority: 'P3',
    system: 'Lucas / Pektron',
    models: [
      { slug: '75', name: '75' },
      { slug: '45', name: '45' },
      { slug: '25', name: '25' }
    ],
  },
  {
    slug: 'saab', name: 'Saab', nameSlug: 'saab', priority: 'P3',
    system: 'CIM / TWICE',
    models: [
      { slug: '9-3', name: '9-3' },
      { slug: '9-5', name: '9-5' }
    ],
  },
  {
    slug: 'smart', name: 'Smart', nameSlug: 'smart', priority: 'P3',
    system: 'SAM / DAS',
    models: [
      { slug: 'fortwo', name: 'Fortwo' },
      { slug: 'forfour', name: 'Forfour' }
    ],
  },
  {
    slug: 'ssangyong', name: 'SsangYong', nameSlug: 'ssangyong', priority: 'P3',
    system: 'Delphi / REKES',
    models: [
      { slug: 'rexton', name: 'Rexton' },
      { slug: 'korando', name: 'Korando' },
      { slug: 'tivoli', name: 'Tivoli' }
    ],
  },
  {
    slug: 'subaru', name: 'Subaru', nameSlug: 'subaru', priority: 'P3',
    system: 'Subaru Smart Key / Immo',
    models: [
      { slug: 'impreza', name: 'Impreza' },
      { slug: 'forester', name: 'Forester' },
      { slug: 'outback', name: 'Outback' }
    ],
  },
  {
    slug: 'suzuki', name: 'Suzuki', nameSlug: 'suzuki', priority: 'P3',
    system: 'Suzuki Immo / Keyless',
    models: [
      { slug: 'swift', name: 'Swift' },
      { slug: 'alto', name: 'Alto' },
      { slug: 'vitara', name: 'Vitara' },
      { slug: 'ignis', name: 'Ignis' }
    ],
  },
  {
    slug: 'bentley', name: 'Bentley', nameSlug: 'bentley', priority: 'P3',
    system: 'VW Group / KESSY',
    models: [
      { slug: 'continental-gt', name: 'Continental GT' },
      { slug: 'bentayga', name: 'Bentayga' },
      { slug: 'flying-spur', name: 'Flying Spur' }
    ],
  }
];

/**
 * How many makes we actually serve.
 *
 * This number was typed by hand in six places — the /merken title, its meta
 * description, its H1, an H2, the footer and the navigation — and it had
 * drifted: the list carried duplicate Tesla and Lexus entries, so "59 merken"
 * was right by luck while BRANDS.length said 61. Deriving it means the copy
 * cannot disagree with the data again.
 *
 * Not the same as the logo grid on the home page, which shows a curated subset
 * of makes we happen to have artwork for.
 */
export const BRAND_COUNT = BRANDS.length;
