const fs = require('fs');
const path = 'src/config/cities.ts';
let code = fs.readFileSync(path, 'utf8');

const newCities = `  { slug:"maastricht", city:"Maastricht", region:"Limburg", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Maastricht", nlSearches:130, priority:"P2", subAreas:["Maastricht Centrum", "Heer", "Wyck", "Randwyck"], geo:{lat:"50.8514",lng:"5.6910"}, popularBrands:["BMW","Volkswagen","Audi"], commonJob:"Sleutel kwijt in het historische centrum", localFact:"Maastricht trekt jaarlijks miljoenen toeristen en studenten. Of u nu geparkeerd staat in een krappe garage in het centrum of op de campus van de Universiteit, wij zijn snel ter plaatse.", avgJobDuration:"30-55 min" },
  { slug:"venlo", city:"Venlo", region:"Limburg", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Venlo", nlSearches:100, priority:"P2", subAreas:["Venlo Centrum", "Blerick", "Tegelen", "Maasboulevard"], geo:{lat:"51.3704",lng:"6.1724"}, popularBrands:["Volkswagen","Opel","Renault"], commonJob:"Reservesleutel na winkelen aan de grens", localFact:"Venlo is een druk knooppunt voor grensoverschrijdend winkelverkeer. Mocht u na een bezoek aan de Maasboulevard uw sleutel kwijt zijn, dan maken wij direct een nieuwe \u2014 zonder sleepkosten.", avgJobDuration:"30-50 min" },
  { slug:"sittard-geleen", city:"Sittard-Geleen", region:"Limburg", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Sittard-Geleen", nlSearches:90, priority:"P2", subAreas:["Sittard", "Geleen", "Born", "Lindenheuvel"], geo:{lat:"51.0033",lng:"5.8528"}, popularBrands:["Ford","Peugeot","Toyota"], commonJob:"Sleutel bijmaken industrie- en winkelgebieden", localFact:"Sittard-Geleen is het industri\u00eble en commerci\u00eble hart op het smalste stukje van Nederland. Wij bedienen zowel de drukke binnenstad als de bedrijventerreinen rondom de Chemelot campus.", avgJobDuration:"25-45 min" },
  { slug:"heerlen", city:"Heerlen", region:"Limburg", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Heerlen", nlSearches:85, priority:"P2", subAreas:["Heerlen Centrum", "Hoensbroek", "Heerlerheide", "Welten"], geo:{lat:"50.8882",lng:"5.9795"}, popularBrands:["Volkswagen","Renault","Kia"], commonJob:"Transponder sleutel inleren na storing", localFact:"Als centraal knooppunt van de voormalige mijnstreek in Zuid-Limburg lossen wij in Heerlen dagelijks startonderbreker-storingen op, gewoon bij u voor de deur.", avgJobDuration:"30-60 min" },
  { slug:"roermond", city:"Roermond", region:"Limburg", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Roermond", nlSearches:95, priority:"P2", subAreas:["Roermond Centrum", "Designer Outlet", "Maasniel", "Herten"], geo:{lat:"51.1913",lng:"5.9878"}, popularBrands:["Mercedes","Audi","BMW"], commonJob:"Sleutel kwijt bij de Designer Outlet", localFact:"Veel van onze noodoproepen uit Roermond komen vanaf het enorme parkeerterrein van de Designer Outlet. Geen paniek: wij openen uw auto en programmeren direct een nieuwe sleutel.", avgJobDuration:"45-60 min" },
  { slug:"eindhoven", city:"Eindhoven", region:"Noord-Brabant", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Eindhoven", nlSearches:250, priority:"P2", subAreas:["Eindhoven Centrum", "Strijp-S", "Woensel", "High Tech Campus"], geo:{lat:"51.4416",lng:"5.4697"}, popularBrands:["Tesla","Volkswagen","Audi"], commonJob:"Keyless entry storingen en nieuwe smart keys", localFact:"In de licht- en technologiestad Eindhoven programmeren wij dagelijks geavanceerde smart keys voor leaserijders op de High Tech Campus en bewoners in Strijp-S.", avgJobDuration:"30-50 min" },
  { slug:"helmond", city:"Helmond", region:"Noord-Brabant", country:"NL", lang:"NL", travelTime:"30-60 min", keyword:"autosleutel programmeren Helmond", nlSearches:110, priority:"P2", subAreas:["Helmond Centrum", "Brouwhuis", "Dierdonk", "Rijpelberg"], geo:{lat:"51.4817",lng:"5.6611"}, popularBrands:["Toyota","Ford","Opel"], commonJob:"Sleutelbehuizing of reservesleutel aan huis", localFact:"Helmond is een echte gezinsstad met uitgestrekte wijken. Wij komen met onze mobiele service gewoon op uw eigen oprit de nieuwe autosleutel frezen en inleren.", avgJobDuration:"25-45 min" }`;

// insert before the last closing bracket
code = code.replace(/\];\s*$/, `,\n${newCities}\n];\n`);
fs.writeFileSync(path, code);
