const fs = require('fs');

const catList = [
"/Autoschluessel",
"/Autoschluessel-Funkschluessel",
"/geeignet-fuer-Alfa-Romeo",
"/geeignet-fuer-Audi",
"/geeignet-fuer-Bentley",
"/geeignet-fuer-BMW",
"/geeignet-fuer-Buick",
"/geeignet-fuer-Chrysler",
"/geeignet-fuer-Citroen",
"/geeignet-fuer-Dacia",
"/geeignet-fuer-Dodge",
"/geeignet-fuer-Fiat",
"/geeignet-fuer-Ford",
"/geeignet-fuer-GM",
"/geeignet-fuer-Honda",
"/geeignet-fuer-Hyundai",
"/geeignet-fuer-Jaguar",
"/geeignet-fuer-Jeep",
"/geeignet-fuer-Kia",
"/geeignet-fuer-Land-Rover",
"/geeignet-fuer-Lexus_1",
"/geeignet-fuer-Maserati",
"/geeignet-fuer-Mazda",
"/geeignet-fuer-Mercedes-Benz",
"/geeignet-fuer-Mini",
"/geeignet-fuer-Mitsubishi",
"/geeignet-fuer-Nissan",
"/geeignet-fuer-Opel",
"/geeignet-fuer-Peugeot",
"/geeignet-fuer-Porsche",
"/geeignet-fuer-Renault",
"/geeignet-fuer-Saab",
"/geeignet-fuer-Seat",
"/geeignet-fuer-Skoda",
"/geeignet-fuer-Smart",
"/geeignet-fuer-Subaru",
"/geeignet-fuer-Suzuki",
"/geeignet-fuer-Toyota",
"/geeignet-fuer-Volkswagen",
"/geeignet-fuer-Volvo",
"/Autoschluessel-ohne-Wegfahrsperre",
"/Autoschluesselblatt-Spitze",
"/Boards-fuer-Funkschluessel-PCB",
"/Funkschluessel-Gehaeuse",
"/geeignet-fuer-ALFA-ROMEO_1",
"/geeignet-fuer-AUDI_1",
"/geeignet-fuer-BMW_1",
"/geeignet-fuer-CADILLAC_1",
"/geeignet-fuer-CHEVROLET_1",
"/geeignet-fuer-CHRYSLER_1",
"/geeignet-fuer-CITROEN_1",
"/geeignet-fuer-DACIA_1",
"/geeignet-fuer-Ferrari_1",
"/geeignet-fuer-FIAT_1",
"/geeignet-fuer-FORD_1",
"/geeignet-fuer-HONDA_1",
"/geeignet-fuer-HYUNDAI_1",
"/geeignet-fuer-JAGUAR_1",
"/geeignet-fuer-JEEP_1",
"/geeignet-fuer-KIA_1",
"/geeignet-fuer-LAND-ROVER_1",
"/geeignet-fuer-LEXUS",
"/geeignet-fuer-MAZDA_1",
"/geeignet-fuer-MERCEDES-BENZ_1",
"/geeignet-fuer-MINI_1",
"/geeignet-fuer-MITSUBISHI_1",
"/geeignet-fuer-NISSAN_1",
"/geeignet-fuer-OPEL_1",
"/geeignet-fuer-PEUGEOT_1",
"/geeignet-fuer-PORSCHE_1",
"/geeignet-fuer-RENAULT_1",
"/geeignet-fuer-ROVER",
"/geeignet-fuer-SAAB_1",
"/geeignet-fuer-SEAT_1",
"/geeignet-fuer-SKODA_1",
"/geeignet-fuer-SMART_1",
"/geeignet-fuer-SSANGYONG",
"/geeignet-fuer-SUZUKI_1",
"/geeignet-fuer-TOYOTA_1",
"/geeignet-fuer-VOLKSWAGEN_1",
"/geeignet-fuer-VOLVO_1",
"/Notschluessel",
"/Transponder",
"/Transponderschluessel",
"/Zubehoer-Werkzeug",
"/Anlageschluessel",
"/Bahnenschluessel",
"/Bohrmuldenschluessel",
"/Buntbartschluessel",
"/Keilbartschluessel",
"/Kreuzbartschluessel",
"/Dornschluessel-Neubautenschluessel",
"/Moebelschluessel",
"/Motorradschluessel",
"/Stahlschluessel-Vollbart",
"/Tresorschluessel",
"/Universal-Anlageschluessel",
"/Zylinderschluessel"
];

let file = fs.readFileSync('scripts/a-key-scraper/scrape-akey.mjs', 'utf8');

// Replace CATEGORIES array
file = file.replace(/const CATEGORIES = \[[\s\S]*?\];/m, `const CATEGORIES = ${JSON.stringify(catList, null, 2)};`);

// Save
fs.writeFileSync('scripts/a-key-scraper/scrape-akey.mjs', file);
