// ============================================================
// BRANDS CONFIG — 59 Car Brands
// Each brand: slug, name, priority, system, models
// Expanded with Year Ranges for SEO
// ============================================================

export type Brand = {
  slug: string;
  name: string;
  nameSlug: string; // for URL: /merken/[nameSlug]
  priority: 'P1' | 'P2' | 'P3';
  system: string;   // ECU/immobilizer system
  excerpt: string;
  models?: BrandModel[];
  customH1?: string;
  customMetaTitle?: string;
  customSeoBlurb?: string; // model-specific SEO paragraph for long-tail keywords
  customFaqs?: { q: string; a: string }[];
  specialIntents?: { slug: string; name: string; type: string }[];
};

export type BrandModel = {
  slug: string;
  name: string;
  generations?: string;
  years: string; // e.g. "2011–2024" or "2010, 2011, 2012, 2013, 2014, 2015"
};

export const BRANDS: Brand[] = [
  {
    slug: 'bmw', name: 'BMW', nameSlug: 'bmw', priority: 'P1',
    system: 'CAS2 / CAS3+ / CAS4+ / FEM / BDC',
    excerpt: 'BMW sleutel programmering voor alle series. CAS, FEM en BDC systemen. 1/3/5/7 Serie, X1–X7, M-series, i-series.',
    customSeoBlurb: 'Wij helpen u met de BMW X1 sleutel bijmaken, BMW X2 sleutel bij laten maken en BMW sleutel bijmaken kosten transparant berekenen. De BMW X1 (E84, F48) en X2 (F39) gebruiken het BDC-systeem. Ook de 1 Serie, 3 Serie, X3 en X5 sleutels leren wij in op locatie. De BMW sleutel bijmaken kosten liggen bij ons tot 50% lager dan bij de BMW-dealer.',
    models: [
      { slug: '1-serie', name: '1 Serie', years: 'Alle bouwjaren' },
      { slug: '2-serie', name: '2 Serie', years: 'Alle bouwjaren' },
      { slug: '3-serie', name: '3 Serie', years: 'Alle bouwjaren' },
      { slug: '4-serie', name: '4 Serie', years: 'Alle bouwjaren' },
      { slug: '5-serie', name: '5 Serie', years: 'Alle bouwjaren' },
      { slug: '6-serie', name: '6 Serie', years: 'Alle bouwjaren' },
      { slug: '7-serie', name: '7 Serie', years: 'Alle bouwjaren' },
      { slug: '8-serie', name: '8 Serie', years: 'Alle bouwjaren' },
      { slug: 'i3', name: 'i3', years: 'Alle bouwjaren' },
      { slug: 'i4', name: 'i4', years: 'Alle bouwjaren' },
      { slug: 'i5', name: 'i5', years: 'Alle bouwjaren' },
      { slug: 'i7', name: 'i7', years: 'Alle bouwjaren' },
      { slug: 'i8', name: 'i8', years: 'Alle bouwjaren' },
      { slug: 'ix', name: 'iX', years: 'Alle bouwjaren' },
      { slug: 'ix1', name: 'iX1', years: 'Alle bouwjaren' },
      { slug: 'ix2', name: 'iX2', years: 'Alle bouwjaren' },
      { slug: 'ix3', name: 'iX3', years: 'Alle bouwjaren' },
      { slug: 'x1', name: 'X1', years: 'Alle bouwjaren' },
      { slug: 'x2', name: 'X2', years: 'Alle bouwjaren' },
      { slug: 'x3', name: 'X3', years: 'Alle bouwjaren' },
      { slug: 'x4', name: 'X4', years: 'Alle bouwjaren' },
      { slug: 'x5', name: 'X5', years: 'Alle bouwjaren' },
      { slug: 'x6', name: 'X6', years: 'Alle bouwjaren' },
      { slug: 'x7', name: 'X7', years: 'Alle bouwjaren' },
      { slug: 'z3', name: 'Z3', years: 'Alle bouwjaren' },
      { slug: 'z4', name: 'Z4', years: 'Alle bouwjaren' },
      { slug: 'm2', name: 'M2', years: 'Alle bouwjaren' },
      { slug: 'm3', name: 'M3', years: 'Alle bouwjaren' },
      { slug: 'm4', name: 'M4', years: 'Alle bouwjaren' },
      { slug: 'm5', name: 'M5', years: 'Alle bouwjaren' },
      { slug: 'm6', name: 'M6', years: 'Alle bouwjaren' },
      { slug: 'm8', name: 'M8', years: 'Alle bouwjaren' },
    ],
    specialIntents: [{ slug: 'display-key-inleren', name: 'Display Key', type: 'programming' }],
  },
  {
    slug: 'mercedes', name: 'Mercedes-Benz', nameSlug: 'mercedes', priority: 'P1',
    system: 'IR / HFM / NEC / EIS / ESL',
    excerpt: 'Mercedes sleutel programmering. W204, W205, W213, Sprinter, Vito. EIS/ESL bench programmering.',
    customSeoBlurb: 'Heeft u een Mercedes Benz CLK sleutel bijmaken nodig, of wilt u de Mercedes Benz ML autosleutel bijmaken of de Mercedes Benz SL Klasse autosleutel bijmaken? Ook de Mercedes Benz CL Klasse autosleutel bij laten maken behoort tot ons dagelijks werk. Wij werken met EIS/ESL bench-programmering voor alle modellen, van de A-Klasse tot de S-Klasse, CLA, GLA en GLC.',
    models: [
      { slug: 'a-klasse', name: 'A-Klasse', years: 'Alle bouwjaren' },
      { slug: 'b-klasse', name: 'B-Klasse', years: 'Alle bouwjaren' },
      { slug: 'c-klasse', name: 'C-Klasse', years: 'Alle bouwjaren' },
      { slug: 'cla', name: 'CLA', years: 'Alle bouwjaren' },
      { slug: 'clk', name: 'CLK', years: 'Alle bouwjaren' },
      { slug: 'cls', name: 'CLS', years: 'Alle bouwjaren' },
      { slug: 'e-klasse', name: 'E-Klasse', years: 'Alle bouwjaren' },
      { slug: 'g-klasse', name: 'G-Klasse', years: 'Alle bouwjaren' },
      { slug: 'gl', name: 'GL', years: 'Alle bouwjaren' },
      { slug: 'gla', name: 'GLA', years: 'Alle bouwjaren' },
      { slug: 'glb', name: 'GLB', years: 'Alle bouwjaren' },
      { slug: 'glc', name: 'GLC', years: 'Alle bouwjaren' },
      { slug: 'gle', name: 'GLE', years: 'Alle bouwjaren' },
      { slug: 'glk', name: 'GLK', years: 'Alle bouwjaren' },
      { slug: 'gls', name: 'GLS', years: 'Alle bouwjaren' },
      { slug: 'm-klasse', name: 'M-Klasse', years: 'Alle bouwjaren' },
      { slug: 'r-klasse', name: 'R-Klasse', years: 'Alle bouwjaren' },
      { slug: 's-klasse', name: 'S-Klasse', years: 'Alle bouwjaren' },
      { slug: 'sl', name: 'SL', years: 'Alle bouwjaren' },
      { slug: 'slc', name: 'SLC', years: 'Alle bouwjaren' },
      { slug: 'slk', name: 'SLK', years: 'Alle bouwjaren' },
      { slug: 'sls-amg', name: 'SLS AMG', years: 'Alle bouwjaren' },
      { slug: 'sprinter', name: 'Sprinter', years: 'Alle bouwjaren' },
      { slug: 'v-klasse', name: 'V-Klasse', years: 'Alle bouwjaren' },
      { slug: 'viano', name: 'Viano', years: 'Alle bouwjaren' },
      { slug: 'vito', name: 'Vito', years: 'Alle bouwjaren' },
      { slug: 'eqe', name: 'EQE', years: 'Alle bouwjaren' },
      { slug: 'eqs', name: 'EQS', years: 'Alle bouwjaren' },
      { slug: 'eqc', name: 'EQC', years: 'Alle bouwjaren' },
      { slug: 'eqa', name: 'EQA', years: 'Alle bouwjaren' },
      { slug: 'eqb', name: 'EQB', years: 'Alle bouwjaren' },
    ],
    specialIntents: [{ slug: 'contactslot-eis-reparatie', name: 'Contactslot / EIS', type: 'repair' }],
  },
  {
    slug: 'volkswagen', name: 'Volkswagen', nameSlug: 'volkswagen', priority: 'P1',
    system: 'MQB / MLB / PQ35 / SFD',
    excerpt: 'VW sleutel programmering. Golf 7/8, Tiguan, Polo, Passat. SFD ontgrendeling specialist.',
    customSeoBlurb: 'Populaire zoekopdrachten bij ons: Volkswagen Eos sleutel bij laten maken, Volkswagen Jetta sleutel bij laten maken en Volkswagen Transporter sleutel bij laten maken. De VW Eos (2006-2015) en VW Jetta (2005-2018) gebruiken het PQ35-platform. De Transporter T5/T6 werkt met MQB. Wij leren alle VW sleutels in op locatie.',
    models: [
      { slug: 'caddy', name: 'Caddy', years: 'Alle bouwjaren' },
      { slug: 'caravelle', name: 'Caravelle', years: 'Alle bouwjaren' },
      { slug: 'crafter', name: 'Crafter', years: 'Alle bouwjaren' },
      { slug: 'cross-golf', name: 'Cross Golf', years: 'Alle bouwjaren' },
      { slug: 'eos', name: 'Eos', years: 'Alle bouwjaren' },
      { slug: 'euro-van', name: 'Euro Van', years: 'Alle bouwjaren' },
      { slug: 'fox', name: 'Fox', years: 'Alle bouwjaren' },
      { slug: 'golf', name: 'Golf', years: 'Alle bouwjaren' },
      { slug: 'golf-5', name: 'Golf 5', years: 'Alle bouwjaren' },
      { slug: 'golf-6', name: 'Golf 6', years: 'Alle bouwjaren' },
      { slug: 'golf-7', name: 'Golf 7', years: 'Alle bouwjaren' },
      { slug: 'golf-8', name: 'Golf 8', years: 'Alle bouwjaren' },
      { slug: 'golf-cabrio', name: 'Golf Cabrio', years: 'Alle bouwjaren' },
      { slug: 'golf-gti', name: 'Golf Gti', years: 'Alle bouwjaren' },
      { slug: 'golf-plus', name: 'Golf Plus', years: 'Alle bouwjaren' },
      { slug: 'id3', name: 'ID.3', years: 'Alle bouwjaren' },
      { slug: 'id4', name: 'ID.4', years: 'Alle bouwjaren' },
      { slug: 'jetta', name: 'Jetta', years: 'Alle bouwjaren' },
      { slug: 'kombi', name: 'Kombi', years: 'Alle bouwjaren' },
      { slug: 'lavida', name: 'Lavida', years: 'Alle bouwjaren' },
      { slug: 'lt28', name: 'LT28', years: 'Alle bouwjaren' },
      { slug: 'lupo', name: 'Lupo', years: 'Alle bouwjaren' },
      { slug: 'maggiolino', name: 'Maggiolino', years: 'Alle bouwjaren' },
      { slug: 'magotan', name: 'Magotan', years: 'Alle bouwjaren' },
      { slug: 'multivan', name: 'Multivan', years: 'Alle bouwjaren' },
      { slug: 'nouvelle', name: 'Nouvelle', years: 'Alle bouwjaren' },
      { slug: 'coccinelle', name: 'Coccinelle', years: 'Alle bouwjaren' },
      { slug: 'passat', name: 'Passat', years: 'Alle bouwjaren' },
      { slug: 'passat-w8', name: 'Passat W8', years: 'Alle bouwjaren' },
      { slug: 'polo', name: 'Polo', years: 'Alle bouwjaren' },
      { slug: 'polo-6r', name: 'Polo 6R', years: 'Alle bouwjaren' },
      { slug: 'rabbit', name: 'Rabbit', years: 'Alle bouwjaren' },
      { slug: 'routan', name: 'Routan', years: 'Alle bouwjaren' },
      { slug: 'sagitar', name: 'Sagitar', years: 'Alle bouwjaren' },
      { slug: 'saveiro', name: 'Saveiro', years: 'Alle bouwjaren' },
      { slug: 'scirocco', name: 'Scirocco', years: 'Alle bouwjaren' },
      { slug: 'sharan', name: 'Sharan', years: 'Alle bouwjaren' },
      { slug: 'tiguan', name: 'Tiguan', years: 'Alle bouwjaren' },
      { slug: 'touareg', name: 'Touareg', years: 'Alle bouwjaren' },
      { slug: 'touran', name: 'Touran', years: 'Alle bouwjaren' },
      { slug: 'transporter', name: 'Transporter', years: 'Alle bouwjaren' },
      { slug: 'up', name: 'Up', years: 'Alle bouwjaren' },
      { slug: 'vento', name: 'Vento', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'audi', name: 'Audi', nameSlug: 'audi', priority: 'P1',
    system: 'MMI / MIB / VW Group',
    excerpt: 'Audi sleutel programmering. A3, A4, A6, Q3, Q5, Q7. VW Group platform specialist.',
    customSeoBlurb: 'Veel klanten vragen ons voor Audi A6 sleutel bij laten maken en Audi S3 sleutel bij laten maken. De Audi A6 autosleutel bijmaken (C6, C7, C8) vereist MLB-platform programmering. De Audi S3 sleutel bijmaken werkt met hetzelfde platform als de A3. Altijd op locatie, met 12 maanden garantie.',
    models: [
      { slug: 'a1', name: 'A1', years: 'Alle bouwjaren' },
      { slug: 'a2', name: 'A2', years: 'Alle bouwjaren' },
      { slug: 'a3', name: 'A3', years: 'Alle bouwjaren' },
      { slug: 'a4', name: 'A4', years: 'Alle bouwjaren' },
      { slug: 'a5', name: 'A5', years: 'Alle bouwjaren' },
      { slug: 'a6', name: 'A6', years: 'Alle bouwjaren' },
      { slug: 'a7', name: 'A7', years: 'Alle bouwjaren' },
      { slug: 'a8', name: 'A8', years: 'Alle bouwjaren' },
      { slug: 'q2', name: 'Q2', years: 'Alle bouwjaren' },
      { slug: 'q3', name: 'Q3', years: 'Alle bouwjaren' },
      { slug: 'q5', name: 'Q5', years: 'Alle bouwjaren' },
      { slug: 'q7', name: 'Q7', years: 'Alle bouwjaren' },
      { slug: 'q8', name: 'Q8', years: 'Alle bouwjaren' },
      { slug: 'r8', name: 'R8', years: 'Alle bouwjaren' },
      { slug: 'tt', name: 'TT', years: 'Alle bouwjaren' },
      { slug: 'e-tron', name: 'e-tron', years: 'Alle bouwjaren' },
      { slug: 'q4-e-tron', name: 'Q4 e-tron', years: 'Alle bouwjaren' },
      { slug: 'e-tron-gt', name: 'e-tron GT', years: 'Alle bouwjaren' },
      { slug: 's1', name: 'S1', years: 'Alle bouwjaren' },
      { slug: 's3', name: 'S3', years: 'Alle bouwjaren' },
      { slug: 's4', name: 'S4', years: 'Alle bouwjaren' },
      { slug: 's5', name: 'S5', years: 'Alle bouwjaren' },
      { slug: 's6', name: 'S6', years: 'Alle bouwjaren' },
      { slug: 's7', name: 'S7', years: 'Alle bouwjaren' },
      { slug: 's8', name: 'S8', years: 'Alle bouwjaren' },
      { slug: 'rs3', name: 'RS3', years: 'Alle bouwjaren' },
      { slug: 'rs4', name: 'RS4', years: 'Alle bouwjaren' },
      { slug: 'rs5', name: 'RS5', years: 'Alle bouwjaren' },
      { slug: 'rs6', name: 'RS6', years: 'Alle bouwjaren' },
      { slug: 'rs7', name: 'RS7', years: 'Alle bouwjaren' },
      { slug: 'rs-q3', name: 'RS Q3', years: 'Alle bouwjaren' },
      { slug: 'rs-q8', name: 'RS Q8', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'volvo', name: 'Volvo', nameSlug: 'volvo', priority: 'P2',
    system: 'Volvo VIDA / DICE / CEM',
    excerpt: 'Volvo sleutel programmering. V40, V60, XC60, XC90, S60. CEM module specialist.',
    models: [
      { slug: 'c30', name: 'C30', years: 'Alle bouwjaren' },
      { slug: 'c70', name: 'C70', years: 'Alle bouwjaren' },
      { slug: 's40', name: 'S40', years: 'Alle bouwjaren' },
      { slug: 's60', name: 'S60', years: 'Alle bouwjaren' },
      { slug: 's70', name: 'S70', years: 'Alle bouwjaren' },
      { slug: 's80', name: 'S80', years: 'Alle bouwjaren' },
      { slug: 's90', name: 'S90', years: 'Alle bouwjaren' },
      { slug: 'v40', name: 'V40', years: 'Alle bouwjaren' },
      { slug: 'v50', name: 'V50', years: 'Alle bouwjaren' },
      { slug: 'v60', name: 'V60', years: 'Alle bouwjaren' },
      { slug: 'v70', name: 'V70', years: 'Alle bouwjaren' },
      { slug: 'v90', name: 'V90', years: 'Alle bouwjaren' },
      { slug: 'xc40', name: 'XC40', years: 'Alle bouwjaren' },
      { slug: 'xc60', name: 'XC60', years: 'Alle bouwjaren' },
      { slug: 'xc70', name: 'XC70', years: 'Alle bouwjaren' },
      { slug: 'xc90', name: 'XC90', years: 'Alle bouwjaren' },
      { slug: 'ex30', name: 'EX30', years: 'Alle bouwjaren' },
      { slug: 'ex90', name: 'EX90', years: 'Alle bouwjaren' },
      { slug: 'c40', name: 'C40', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'toyota', name: 'Toyota', nameSlug: 'toyota', priority: 'P1',
    system: 'Smart Key / G chip',
    excerpt: 'Toyota sleutel programmering specialist.',
    models: [
      { slug: 'auris', name: 'Auris', years: 'Alle bouwjaren' },
      { slug: 'avensis', name: 'Avensis', years: 'Alle bouwjaren' },
      { slug: 'aygo', name: 'Aygo', years: 'Alle bouwjaren' },
      { slug: 'c-hr', name: 'C-HR', years: 'Alle bouwjaren' },
      { slug: 'camry', name: 'Camry', years: 'Alle bouwjaren' },
      { slug: 'celica', name: 'Celica', years: 'Alle bouwjaren' },
      { slug: 'corolla', name: 'Corolla', years: 'Alle bouwjaren' },
      { slug: 'corolla-cross', name: 'Corolla Cross', years: 'Alle bouwjaren' },
      { slug: 'gt86', name: 'GT86', years: 'Alle bouwjaren' },
      { slug: 'highlander', name: 'Highlander', years: 'Alle bouwjaren' },
      { slug: 'hilux', name: 'Hilux', years: 'Alle bouwjaren' },
      { slug: 'iq', name: 'IQ', years: 'Alle bouwjaren' },
      { slug: 'land-cruiser', name: 'Land Cruiser', years: 'Alle bouwjaren' },
      { slug: 'mr2', name: 'MR2', years: 'Alle bouwjaren' },
      { slug: 'prius', name: 'Prius', years: 'Alle bouwjaren' },
      { slug: 'proace', name: 'Proace', years: 'Alle bouwjaren' },
      { slug: 'proace-city', name: 'Proace City', years: 'Alle bouwjaren' },
      { slug: 'rav4', name: 'RAV4', years: 'Alle bouwjaren' },
      { slug: 'supra', name: 'Supra', years: 'Alle bouwjaren' },
      { slug: 'urban-cruiser', name: 'Urban Cruiser', years: 'Alle bouwjaren' },
      { slug: 'verso', name: 'Verso', years: 'Alle bouwjaren' },
      { slug: 'yaris', name: 'Yaris', years: 'Alle bouwjaren' },
      { slug: 'yaris-cross', name: 'Yaris Cross', years: 'Alle bouwjaren' },
      { slug: 'bz4x', name: 'bZ4X', years: 'Alle bouwjaren' },
    ],
    specialIntents: [{ slug: 'hybride-sleutel-vervangen', name: 'Hybride Sleutel', type: 'repair' }],
  },
  {
    slug: 'ford', name: 'Ford', nameSlug: 'ford', priority: 'P1',
    system: 'Ford PATS / Passive Anti-Theft System',
    excerpt: 'Ford sleutel programmering specialist. Fiesta, Focus, Mondeo, Transit, Kuga. PATS systemen.',
    models: [
      { slug: 'b-max', name: 'B-Max', years: 'Alle bouwjaren' },
      { slug: 'c-max', name: 'C-Max', years: 'Alle bouwjaren' },
      { slug: 'cougar', name: 'Cougar', years: 'Alle bouwjaren' },
      { slug: 'courier', name: 'Courier', years: 'Alle bouwjaren' },
      { slug: 'ecosport', name: 'EcoSport', years: 'Alle bouwjaren' },
      { slug: 'edge', name: 'Edge', years: 'Alle bouwjaren' },
      { slug: 'escape', name: 'Escape', years: 'Alle bouwjaren' },
      { slug: 'escort', name: 'Escort', years: 'Alle bouwjaren' },
      { slug: 'explorer', name: 'Explorer', years: 'Alle bouwjaren' },
      { slug: 'f-150', name: 'F-150', years: 'Alle bouwjaren' },
      { slug: 'fiesta', name: 'Fiesta', years: 'Alle bouwjaren' },
      { slug: 'focus', name: 'Focus', years: 'Alle bouwjaren' },
      { slug: 'fusion', name: 'Fusion', years: 'Alle bouwjaren' },
      { slug: 'galaxy', name: 'Galaxy', years: 'Alle bouwjaren' },
      { slug: 'grand-c-max', name: 'Grand C-Max', years: 'Alle bouwjaren' },
      { slug: 'ka', name: 'KA', years: 'Alle bouwjaren' },
      { slug: 'ka', name: 'KA+', years: 'Alle bouwjaren' },
      { slug: 'kuga', name: 'Kuga', years: 'Alle bouwjaren' },
      { slug: 'mondeo', name: 'Mondeo', years: 'Alle bouwjaren' },
      { slug: 'mustang', name: 'Mustang', years: 'Alle bouwjaren' },
      { slug: 'mustang-mach-e', name: 'Mustang Mach-E', years: 'Alle bouwjaren' },
      { slug: 'puma', name: 'Puma', years: 'Alle bouwjaren' },
      { slug: 'ranger', name: 'Ranger', years: 'Alle bouwjaren' },
      { slug: 's-max', name: 'S-Max', years: 'Alle bouwjaren' },
      { slug: 'tourneo', name: 'Tourneo', years: 'Alle bouwjaren' },
      { slug: 'transit', name: 'Transit', years: 'Alle bouwjaren' },
      { slug: 'transit-connect', name: 'Transit Connect', years: 'Alle bouwjaren' },
      { slug: 'transit-courier', name: 'Transit Courier', years: 'Alle bouwjaren' },
      { slug: 'transit-custom', name: 'Transit Custom', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'opel', name: 'Opel', nameSlug: 'opel', priority: 'P1',
    system: 'Opel Immobiliser I / II / III',
    excerpt: 'Opel sleutel programmering specialist. Corsa, Astra, Insignia, Vivaro. PIN-code extractie.',
    customSeoBlurb: 'Wij verzorgen regelmatig Opel Crossland autosleutel bijmaken en Opel Vivaro autosleutel bijmaken. De Opel Crossland (2017+) gebruikt het PSA-platform met PIN-code extractie. De Opel Vivaro is een populaire bestelwagen waarvoor wij de sleutel op locatie bijmaken. Autosleutel bijmaken Opel Corsa, Astra, Insignia en Mokka is ook ons standaard aanbod.',
    models: [
      { slug: 'agila', name: 'Agila', years: 'Alle bouwjaren' },
      { slug: 'amperia', name: 'Amperia', years: 'Alle bouwjaren' },
      { slug: 'antara', name: 'Antara', years: 'Alle bouwjaren' },
      { slug: 'astra', name: 'Astra', years: 'Alle bouwjaren' },
      { slug: 'calibra', name: 'Calibra', years: 'Alle bouwjaren' },
      { slug: 'combo', name: 'Combo', years: 'Alle bouwjaren' },
      { slug: 'corsa', name: 'Corsa', years: 'Alle bouwjaren' },
      { slug: 'crossland', name: 'Crossland', years: 'Alle bouwjaren' },
      { slug: 'frontera', name: 'Frontera', years: 'Alle bouwjaren' },
      { slug: 'insignia', name: 'Insignia', years: 'Alle bouwjaren' },
      { slug: 'meriva', name: 'Meriva', years: 'Alle bouwjaren' },
      { slug: 'mokka', name: 'Mokka', years: 'Alle bouwjaren' },
      { slug: 'movano', name: 'Movano', years: 'Alle bouwjaren' },
      { slug: 'omega', name: 'Omega', years: 'Alle bouwjaren' },
      { slug: 'signum', name: 'Signum', years: 'Alle bouwjaren' },
      { slug: 'karl', name: 'Karl', years: 'Alle bouwjaren' },
      { slug: 'sintra', name: 'Sintra', years: 'Alle bouwjaren' },
      { slug: 'speedster', name: 'Speedster', years: 'Alle bouwjaren' },
      { slug: 'tigra', name: 'Tigra', years: 'Alle bouwjaren' },
      { slug: 'vectra', name: 'Vectra', years: 'Alle bouwjaren' },
      { slug: 'vivaro', name: 'Vivaro', years: 'Alle bouwjaren' },
      { slug: 'zafira', name: 'Zafira', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'renault', name: 'Renault', nameSlug: 'renault', priority: 'P2',
    system: 'Renault Card Key / UCH',
    excerpt: 'Renault kaart sleutel specialist. Clio, Captur, Megane, Scenic, Trafic. Kaart programmering.',
    customSeoBlurb: 'Een veelgevraagde dienst is de Renault Laguna autosleutel bijmaken. De Renault Laguna II en III (1994-2015) werkt met de bekende kaartsleutel en UCH-module. Wij lezen de pincode uit en programmeren direct een nieuwe kaartsleutel op locatie. Ook voor de Clio, Megane, Trafic en Captur kunt u bij ons terecht.',
    models: [
      { slug: 'arkana', name: 'Arkana', years: 'Alle bouwjaren' },
      { slug: 'austral', name: 'Austral', years: 'Alle bouwjaren' },
      { slug: 'avantime', name: 'Avantime', years: 'Alle bouwjaren' },
      { slug: 'captur', name: 'Captur', years: 'Alle bouwjaren' },
      { slug: 'clio', name: 'Clio', years: 'Alle bouwjaren' },
      { slug: 'clio-ii', name: 'Clio II', years: 'Alle bouwjaren' },
      { slug: 'clio-iii', name: 'Clio III', years: 'Alle bouwjaren' },
      { slug: 'clio-iv', name: 'Clio IV', years: 'Alle bouwjaren' },
      { slug: 'coach', name: 'Coach', years: 'Alle bouwjaren' },
      { slug: 'espace', name: 'Espace', years: 'Alle bouwjaren' },
      { slug: 'espace-iii', name: 'Espace III', years: 'Alle bouwjaren' },
      { slug: 'espace-iv', name: 'Espace IV', years: 'Alle bouwjaren' },
      { slug: 'fluence', name: 'Fluence', years: 'Alle bouwjaren' },
      { slug: 'kadjar', name: 'Kadjar', years: 'Alle bouwjaren' },
      { slug: 'kangoo', name: 'Kangoo', years: 'Alle bouwjaren' },
      { slug: 'koleos', name: 'Koleos', years: 'Alle bouwjaren' },
      { slug: 'kyron', name: 'Kyron', years: 'Alle bouwjaren' },
      { slug: 'laguna', name: 'Laguna', years: 'Alle bouwjaren' },
      { slug: 'laguna-ii', name: 'Laguna II', years: 'Alle bouwjaren' },
      { slug: 'laguna-iii', name: 'Laguna III', years: 'Alle bouwjaren' },
      { slug: 'latitude', name: 'Latitude', years: 'Alle bouwjaren' },
      { slug: 'master', name: 'Master', years: 'Alle bouwjaren' },
      { slug: 'megane', name: 'Megane', years: 'Alle bouwjaren' },
      { slug: 'megane-e-tech', name: 'Megane E-Tech', years: 'Alle bouwjaren' },
      { slug: 'megane-ii', name: 'Megane II', years: 'Alle bouwjaren' },
      { slug: 'megane-iii', name: 'Megane III', years: 'Alle bouwjaren' },
      { slug: 'megane-iv', name: 'Megane IV', years: 'Alle bouwjaren' },
      { slug: 'modus', name: 'Modus', years: 'Alle bouwjaren' },
      { slug: 'safrane', name: 'Safrane', years: 'Alle bouwjaren' },
      { slug: 'scenic', name: 'Scenic', years: 'Alle bouwjaren' },
      { slug: 'talisman', name: 'Talisman', years: 'Alle bouwjaren' },
      { slug: 'trafic', name: 'Trafic', years: 'Alle bouwjaren' },
      { slug: 'twingo', name: 'Twingo', years: 'Alle bouwjaren' },
      { slug: 'twizy', name: 'Twizy', years: 'Alle bouwjaren' },
      { slug: 'zoe', name: 'Zoe', years: 'Alle bouwjaren' },
    ],
    specialIntents: [{ slug: 'keycard-reparatie-vervangen', name: 'Keycard', type: 'repair' }],
  },
  {
    slug: 'peugeot', name: 'Peugeot', nameSlug: 'peugeot', priority: 'P2',
    system: 'PSA BSI / PIN extractie',
    excerpt: 'Peugeot sleutel programmering specialist. 208, 308, 508, Partner. BSI programmering.',
    customSeoBlurb: 'Heeft u een extra sleutel nodig? Wij verzorgen regelmatig een Peugeot 607 sleutel bij laten maken, Peugeot 5008 autosleutel bijmaken, Peugeot 406 autosleutel bijmaken en Peugeot Expert sleutels. De Peugeot 607 (1999-2010) en 406 (1995-2004) zijn oudere modellen. De Peugeot 5008 en Expert gebruiken het modernere BSI-systeem. Wij lezen de pin-code uit en programmeren de sleutel op uw locatie. Ook voor de Peugeot 206 sleutel bijmaken kosten kunt u direct bij ons terecht voor een scherpe all-in prijs.',
    customFaqs: [
      {
        q: 'Wat zijn de Peugeot 206 sleutel bijmaken kosten?',
        a: 'De Peugeot 206 sleutel bijmaken kosten vallen bij ons aanzienlijk lager uit dan bij de dealer. Voor een standaard mechanische transpondersleutel bent u bij ons al vanaf €120,- klaar. Een klapsleutel met afstandsbediening is iets duurder, maar nog steeds tot wel 50% goedkoper dan de dealerprijs. Neem contact op voor een vaste prijsopgave.'
      },
      {
        q: 'Kan ik een Peugeot 406 autosleutel bijmaken als ik alle sleutels kwijt ben?',
        a: 'Ja, wij kunnen zonder problemen een Peugeot 406 autosleutel bijmaken, zelfs in een All Keys Lost (AKL) situatie. Onze monteurs komen naar uw locatie, decoderen het portierslot om de nieuwe sleutel te frezen, en lezen de beveiligingscode uit de computer om de nieuwe transponder te programmeren.'
      },
      {
        q: 'Ondersteunen jullie ook een Peugeot 5008 autosleutel bijmaken op locatie?',
        a: 'Zeker. Voor een Peugeot 5008 autosleutel bijmaken – ongeacht of het om een standaard transponder, een klapsleutel of een moderne Smart Key gaat – komen wij met onze servicebus naar u toe. Wij programmeren de sleutel rechtstreeks via de OBD2-poort in het BSI-systeem van de auto.'
      },
      {
        q: 'Wat is de werkwijze om een Peugeot 607 sleutel bij laten maken?',
        a: 'Wilt u een reserve Peugeot 607 sleutel bij laten maken? Onze specialist komt naar uw auto, leest de chipgegevens uit en freest de sleutelbaard nauwkeurig met een CNC-machine. Binnen 30 minuten is uw nieuwe Peugeot 607 sleutel volledig geprogrammeerd en klaar voor gebruik.'
      }
    ],
    models: [
      { slug: '106', name: '106', years: 'Alle bouwjaren' },
      { slug: '107', name: '107', years: 'Alle bouwjaren' },
      { slug: '108', name: '108', years: 'Alle bouwjaren' },
      { slug: '206', name: '206', years: 'Alle bouwjaren' },
      { slug: '206-plus', name: '206+', years: 'Alle bouwjaren' },
      { slug: '206-cabrio', name: '206 Cabrio', years: 'Alle bouwjaren' },
      { slug: '207', name: '207', years: 'Alle bouwjaren' },
      { slug: '208', name: '208', years: 'Alle bouwjaren' },
      { slug: '301', name: '301', years: 'Alle bouwjaren' },
      { slug: '306', name: '306', years: 'Alle bouwjaren' },
      { slug: '306-sb', name: '306 SB', years: 'Alle bouwjaren' },
      { slug: '306-sc', name: '306 SC', years: 'Alle bouwjaren' },
      { slug: '307', name: '307', years: 'Alle bouwjaren' },
      { slug: '308', name: '308', years: 'Alle bouwjaren' },
      { slug: '406', name: '406', years: 'Alle bouwjaren' },
      { slug: '406-sb', name: '406 SB', years: 'Alle bouwjaren' },
      { slug: '406-sc', name: '406 SC', years: 'Alle bouwjaren' },
      { slug: '406-sv', name: '406 SV', years: 'Alle bouwjaren' },
      { slug: '407', name: '407', years: 'Alle bouwjaren' },
      { slug: '607', name: '607', years: 'Alle bouwjaren' },
      { slug: '806', name: '806', years: 'Alle bouwjaren' },
      { slug: '806-sb', name: '806 SB', years: 'Alle bouwjaren' },
      { slug: '806-sc', name: '806 SC', years: 'Alle bouwjaren' },
      { slug: '807', name: '807', years: 'Alle bouwjaren' },
      { slug: '1007', name: '1007', years: 'Alle bouwjaren' },
      { slug: '2008', name: '2008', years: 'Alle bouwjaren' },
      { slug: '3008', name: '3008', years: 'Alle bouwjaren' },
      { slug: '4007', name: '4007', years: 'Alle bouwjaren' },
      { slug: '5008', name: '5008', years: 'Alle bouwjaren' },
      { slug: '508', name: '508', years: 'Alle bouwjaren' },
      { slug: 'bipper', name: 'Bipper', years: 'Alle bouwjaren' },
      { slug: 'boxer', name: 'Boxer', years: 'Alle bouwjaren' },
      { slug: 'expert', name: 'Expert', years: 'Alle bouwjaren' },
      { slug: 'partner', name: 'Partner', years: 'Alle bouwjaren' },
      { slug: 'ranch', name: 'Ranch', years: 'Alle bouwjaren' },
      { slug: 'rcz', name: 'RCZ', years: 'Alle bouwjaren' },
      { slug: 'traveller', name: 'Traveller', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'fiat', name: 'Fiat', nameSlug: 'fiat', priority: 'P2',
    system: 'Fiat Code 2 / Delphi / Marelli',
    excerpt: 'Fiat sleutel programmering specialist. 500, Punto, Ducato, Panda. Body computer specialist.',
    models: [
      { slug: '124-spider', name: '124 Spider', years: 'Alle bouwjaren' },
      { slug: '500', name: '500', years: 'Alle bouwjaren' },
      { slug: '500c', name: '500C', years: 'Alle bouwjaren' },
      { slug: '500l', name: '500L', years: 'Alle bouwjaren' },
      { slug: '500x', name: '500X', years: 'Alle bouwjaren' },
      { slug: '600', name: '600', years: 'Alle bouwjaren' },
      { slug: 'barchetta', name: 'Barchetta', years: 'Alle bouwjaren' },
      { slug: 'bravo', name: 'Bravo', years: 'Alle bouwjaren' },
      { slug: 'croma', name: 'Croma', years: 'Alle bouwjaren' },
      { slug: 'doblo', name: 'Doblo', years: 'Alle bouwjaren' },
      { slug: 'ducato', name: 'Ducato', years: 'Alle bouwjaren' },
      { slug: 'fiorino', name: 'Fiorino', years: 'Alle bouwjaren' },
      { slug: 'freemont', name: 'Freemont', years: 'Alle bouwjaren' },
      { slug: 'grande-punto', name: 'Grande Punto', years: 'Alle bouwjaren' },
      { slug: 'idea', name: 'Idea', years: 'Alle bouwjaren' },
      { slug: 'multipla', name: 'Multipla', years: 'Alle bouwjaren' },
      { slug: 'palio', name: 'Palio', years: 'Alle bouwjaren' },
      { slug: 'panda', name: 'Panda', years: 'Alle bouwjaren' },
      { slug: 'punto', name: 'Punto', years: 'Alle bouwjaren' },
      { slug: 'punto-evo', name: 'Punto Evo', years: 'Alle bouwjaren' },
      { slug: 'qubo', name: 'Qubo', years: 'Alle bouwjaren' },
      { slug: 'scudo', name: 'Scudo', years: 'Alle bouwjaren' },
      { slug: 'sedici', name: 'Sedici', years: 'Alle bouwjaren' },
      { slug: 'seicento', name: 'Seicento', years: 'Alle bouwjaren' },
      { slug: 'stilo', name: 'Stilo', years: 'Alle bouwjaren' },
      { slug: 'talento', name: 'Talento', years: 'Alle bouwjaren' },
      { slug: 'tipo', name: 'Tipo', years: 'Alle bouwjaren' },
      { slug: 'ulysse', name: 'Ulysse', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'seat', name: 'Seat', nameSlug: 'seat', priority: 'P2',
    system: 'VAG Immobiliser / MQB',
    excerpt: 'Seat sleutel programmering specialist. Ibiza, Leon, Ateca. VAG Groep platform.',
    customSeoBlurb: 'Populaire aanvragen zijn Seat Alhambra sleutel bij laten maken en Seat Arosa sleutel bij laten maken. De Seat Alhambra (1996-2020) is een gezinsauto op het VAG-platform. De Seat Arosa (1997-2004) is een compacte auto waarvoor wij nog altijd sleutels bijmaken. Wij programmeren Ibiza, Leon, Arona, Ateca en Tarraco via OBD2.',
    models: [
      { slug: 'alhambra', name: 'Alhambra', years: 'Alle bouwjaren' },
      { slug: 'altea', name: 'Altea', years: 'Alle bouwjaren' },
      { slug: 'altea-xl', name: 'Altea XL', years: 'Alle bouwjaren' },
      { slug: 'arona', name: 'Arona', years: 'Alle bouwjaren' },
      { slug: 'arosa', name: 'Arosa', years: 'Alle bouwjaren' },
      { slug: 'ateca', name: 'Ateca', years: 'Alle bouwjaren' },
      { slug: 'cordoba', name: 'Cordoba', years: 'Alle bouwjaren' },
      { slug: 'exeo', name: 'Exeo', years: 'Alle bouwjaren' },
      { slug: 'ibiza', name: 'Ibiza', years: 'Alle bouwjaren' },
      { slug: 'leon', name: 'Leon', years: 'Alle bouwjaren' },
      { slug: 'mii', name: 'Mii', years: 'Alle bouwjaren' },
      { slug: 'tarraco', name: 'Tarraco', years: 'Alle bouwjaren' },
      { slug: 'toledo', name: 'Toledo', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'skoda', name: 'Skoda', nameSlug: 'skoda', priority: 'P2',
    system: 'VAG Immobiliser / MQB / SFD',
    excerpt: 'Skoda sleutel programmering specialist. Octavia, Fabia, Superb. VAG Groep platform.',
    models: [
      { slug: 'citigo', name: 'Citigo', years: 'Alle bouwjaren' },
      { slug: 'enyaq', name: 'Enyaq', years: 'Alle bouwjaren' },
      { slug: 'fabia', name: 'Fabia', years: 'Alle bouwjaren' },
      { slug: 'kamiq', name: 'Kamiq', years: 'Alle bouwjaren' },
      { slug: 'karoq', name: 'Karoq', years: 'Alle bouwjaren' },
      { slug: 'kodiaq', name: 'Kodiaq', years: 'Alle bouwjaren' },
      { slug: 'octavia', name: 'Octavia', years: 'Alle bouwjaren' },
      { slug: 'praktik', name: 'Praktik', years: 'Alle bouwjaren' },
      { slug: 'rapid', name: 'Rapid', years: 'Alle bouwjaren' },
      { slug: 'roomster', name: 'Roomster', years: 'Alle bouwjaren' },
      { slug: 'scala', name: 'Scala', years: 'Alle bouwjaren' },
      { slug: 'superb', name: 'Superb', years: 'Alle bouwjaren' },
      { slug: 'yeti', name: 'Yeti', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'mazda', name: 'Mazda', nameSlug: 'mazda', priority: 'P2',
    system: 'Mazda PATS / Mitsubishi System',
    excerpt: 'Mazda sleutel programmering specialist. Mazda 2, 3, 6, CX-5. Smart key specialist.',
    customSeoBlurb: 'Wij ontvangen veel aanvragen voor Mazda 3 autosleutel bij laten maken, Mazda CX-3 autosleutel bij laten maken en Mazda 2 autosleutel bij laten maken. De Mazda 3 is een van de populairste modellen in Nederland. De CX-3 en Mazda 2 gebruiken het PATS-systeem. Wij programmeren alle Mazda sleutels direct op locatie.',
    models: [
      { slug: 'mazda-121', name: 'Mazda 121', years: 'Alle bouwjaren' },
      { slug: 'mazda-2', name: 'Mazda 2', years: 'Alle bouwjaren' },
      { slug: 'mazda-3', name: 'Mazda 3', years: 'Alle bouwjaren' },
      { slug: 'mazda-323', name: 'Mazda 323', years: 'Alle bouwjaren' },
      { slug: 'mazda-5', name: 'Mazda 5', years: 'Alle bouwjaren' },
      { slug: 'mazda-6', name: 'Mazda 6', years: 'Alle bouwjaren' },
      { slug: 'mazda-626', name: 'Mazda 626', years: 'Alle bouwjaren' },
      { slug: 'bt-50', name: 'BT-50', years: 'Alle bouwjaren' },
      { slug: 'cx-3', name: 'CX-3', years: 'Alle bouwjaren' },
      { slug: 'cx-30', name: 'CX-30', years: 'Alle bouwjaren' },
      { slug: 'cx-5', name: 'CX-5', years: 'Alle bouwjaren' },
      { slug: 'cx-60', name: 'CX-60', years: 'Alle bouwjaren' },
      { slug: 'cx-7', name: 'CX-7', years: 'Alle bouwjaren' },
      { slug: 'cx-9', name: 'CX-9', years: 'Alle bouwjaren' },
      { slug: 'mx-3', name: 'MX-3', years: 'Alle bouwjaren' },
      { slug: 'mx-5', name: 'MX-5', years: 'Alle bouwjaren' },
      { slug: 'rx-8', name: 'RX-8', years: 'Alle bouwjaren' },
      { slug: 'tribute', name: 'Tribute', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'kia', name: 'Kia', nameSlug: 'kia', priority: 'P2',
    system: 'Hyundai/Kia Smart Key',
    excerpt: 'Kia sleutel programmering specialist. Picanto, Rio, Sportage, Niro. PIN-code specialist.',
    customSeoBlurb: 'Een autosleutel bijmaken Kia is een van onze specialiteiten. Wij kunnen snel en voordelig een kia autosleutel bijmaken voor alle modellen, direct op locatie. Bijvoorbeeld een kia picanto autosleutel bijmaken of een kia rio autosleutel bijmaken doen wij dagelijks. Zoekt u specifiek naar autosleutel bijmaken kia rio of kia cee\'d autosleutel bijmaken (ook wel kia ceed autosleutel bijmaken)? Onze monteurs helpen u snel, ook voor een kia autosleutel bijmaken nijmegen en omstreken. Naast de bekende modellen, programmeren wij ook de rest van de vloot. Denk hierbij aan een kia sportage autosleutel bijmaken, kia sorento autosleutel bijmaken, kia optima autosleutel bijmaken, en kia soul autosleutel bijmaken. Ook voor de ruimere modellen zoals een kia carens autosleutel bijmaken, kia carnival autosleutel bijmaken en kia sedona autosleutel bijmaken hebben wij de juiste chips op voorraad. Heeft u een zeldzamer of ouder model? Geen zorgen, ook een kia amanti autosleutel bijmaken, kia clarence autosleutel bijmaken, kia forte autosleutel bijmaken, of kia pride autosleutel bijmaken is voor ons geen probleem. Klanten vragen ons vaak naar de kosten autosleutel bijmaken kia. Omdat wij op locatie werken, is de autosleutel bijmaken prijs kia bij ons vrijwel altijd voordeliger dan bij de merkdealer. Wilt u veilig een autosleutel kia bijmaken? Neem direct contact op voor een exacte prijsopgave.',
    models: [
      { slug: 'carens', name: 'Carens', years: 'Alle bouwjaren' },
      { slug: 'carnival', name: 'Carnival', years: 'Alle bouwjaren' },
      { slug: 'ceed', name: 'Ceed', years: 'Alle bouwjaren' },
      { slug: 'cerato', name: 'Cerato', years: 'Alle bouwjaren' },
      { slug: 'ev6', name: 'EV6', years: 'Alle bouwjaren' },
      { slug: 'ev9', name: 'EV9', years: 'Alle bouwjaren' },
      { slug: 'niro', name: 'Niro', years: 'Alle bouwjaren' },
      { slug: 'optima', name: 'Optima', years: 'Alle bouwjaren' },
      { slug: 'picanto', name: 'Picanto', years: 'Alle bouwjaren' },
      { slug: 'proceed', name: 'ProCeed', years: 'Alle bouwjaren' },
      { slug: 'rio', name: 'Rio', years: 'Alle bouwjaren' },
      { slug: 'sorento', name: 'Sorento', years: 'Alle bouwjaren' },
      { slug: 'soul', name: 'Soul', years: 'Alle bouwjaren' },
      { slug: 'sportage', name: 'Sportage', years: 'Alle bouwjaren' },
      { slug: 'stinger', name: 'Stinger', years: 'Alle bouwjaren' },
      { slug: 'stonic', name: 'Stonic', years: 'Alle bouwjaren' },
      { slug: 'venga', name: 'Venga', years: 'Alle bouwjaren' },
      { slug: 'xceed', name: 'XCeed', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'hyundai', name: 'Hyundai', nameSlug: 'hyundai', priority: 'P2',
    system: 'Hyundai/Kia Smart Key',
    excerpt: 'Hyundai sleutel programmering specialist. i10, i20, i30, Tucson, Kona.',
    customSeoBlurb: 'Veelgevraagd zijn: Hyundai Santamo autosleutel bij laten maken, Hyundai Getz autosleutel bijmaken, Hyundai Atos Prime autosleutel bij laten maken en Hyundai Excel sleutel bijmaken. De Santamo (1996-2003) en Excel (1985-1999) zijn oudere modellen waarvoor wij nog sleutels maken. De Getz en Atos Prime programmeren wij dagelijks. Ook voor de i10, i20, i30, Tucson en Kona kunt u bij ons terecht.',
    models: [
      { slug: 'atos', name: 'Atos', years: 'Alle bouwjaren' },
      { slug: 'bayon', name: 'Bayon', years: 'Alle bouwjaren' },
      { slug: 'coupe', name: 'Coupe', years: 'Alle bouwjaren' },
      { slug: 'elantra', name: 'Elantra', years: 'Alle bouwjaren' },
      { slug: 'excel', name: 'Excel', years: 'Alle bouwjaren' },
      { slug: 'galloper', name: 'Galloper', years: 'Alle bouwjaren' },
      { slug: 'getz', name: 'Getz', years: 'Alle bouwjaren' },
      { slug: 'grandeur', name: 'Grandeur', years: 'Alle bouwjaren' },
      { slug: 'h-1', name: 'H-1', years: 'Alle bouwjaren' },
      { slug: 'h200', name: 'H200', years: 'Alle bouwjaren' },
      { slug: 'i10', name: 'i10', years: 'Alle bouwjaren' },
      { slug: 'i20', name: 'i20', years: 'Alle bouwjaren' },
      { slug: 'i30', name: 'i30', years: 'Alle bouwjaren' },
      { slug: 'i40', name: 'i40', years: 'Alle bouwjaren' },
      { slug: 'ioniq', name: 'Ioniq', years: 'Alle bouwjaren' },
      { slug: 'ioniq-5', name: 'Ioniq 5', years: 'Alle bouwjaren' },
      { slug: 'ioniq-6', name: 'Ioniq 6', years: 'Alle bouwjaren' },
      { slug: 'ix20', name: 'ix20', years: 'Alle bouwjaren' },
      { slug: 'ix35', name: 'ix35', years: 'Alle bouwjaren' },
      { slug: 'kona', name: 'Kona', years: 'Alle bouwjaren' },
      { slug: 'matrix', name: 'Matrix', years: 'Alle bouwjaren' },
      { slug: 'nexo', name: 'NEXO', years: 'Alle bouwjaren' },
      { slug: 'santa-fe', name: 'Santa Fe', years: 'Alle bouwjaren' },
      { slug: 'sonata', name: 'Sonata', years: 'Alle bouwjaren' },
      { slug: 'terracan', name: 'Terracan', years: 'Alle bouwjaren' },
      { slug: 'trajet', name: 'Trajet', years: 'Alle bouwjaren' },
      { slug: 'tucson', name: 'Tucson', years: 'Alle bouwjaren' },
      { slug: 'veloster', name: 'Veloster', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'nissan', name: 'Nissan', nameSlug: 'nissan', priority: 'P2',
    system: 'Nissan NATS / BCM',
    excerpt: 'Nissan sleutel programmering specialist. Micra, Qashqai, Juke, Leaf.',
    customSeoBlurb: 'Wij verzorgen dagelijks Nissan Primastar autosleutel bijmaken, Nissan Qashqai autosleutel bij laten maken, Nissan Juke autosleutel bij laten maken, Nissan sleutel bijmaken, Nissan 350Z autosleutel bij laten maken, Nissan Maxima autosleutel bijmaken en Nissan Sentra autosleutel bij laten maken. De Nissan Primastar (2001-2014) deelt het Renault Trafic-platform. De 350Z, Maxima en Sentra hebben NATS-beveiliging. Wij programmeren ook sleutel met transponder direct op locatie.',
    models: [
      { slug: '200sx', name: '200SX', years: 'Alle bouwjaren' },
      { slug: '350z', name: '350Z', years: 'Alle bouwjaren' },
      { slug: '370z', name: '370Z', years: 'Alle bouwjaren' },
      { slug: 'almera', name: 'Almera', years: 'Alle bouwjaren' },
      { slug: 'almera-tino', name: 'Almera Tino', years: 'Alle bouwjaren' },
      { slug: 'ariya', name: 'Ariya', years: 'Alle bouwjaren' },
      { slug: 'cube', name: 'Cube', years: 'Alle bouwjaren' },
      { slug: 'evalia', name: 'Evalia', years: 'Alle bouwjaren' },
      { slug: 'gt-r', name: 'GT-R', years: 'Alle bouwjaren' },
      { slug: 'interstar', name: 'Interstar', years: 'Alle bouwjaren' },
      { slug: 'juke', name: 'Juke', years: 'Alle bouwjaren' },
      { slug: 'kubistar', name: 'Kubistar', years: 'Alle bouwjaren' },
      { slug: 'leaf', name: 'Leaf', years: 'Alle bouwjaren' },
      { slug: 'maxima', name: 'Maxima', years: 'Alle bouwjaren' },
      { slug: 'micra', name: 'Micra', years: 'Alle bouwjaren' },
      { slug: 'murano', name: 'Murano', years: 'Alle bouwjaren' },
      { slug: 'navara', name: 'Navara', years: 'Alle bouwjaren' },
      { slug: 'note', name: 'Note', years: 'Alle bouwjaren' },
      { slug: 'nv200', name: 'NV200', years: 'Alle bouwjaren' },
      { slug: 'nv250', name: 'NV250', years: 'Alle bouwjaren' },
      { slug: 'nv300', name: 'NV300', years: 'Alle bouwjaren' },
      { slug: 'nv400', name: 'NV400', years: 'Alle bouwjaren' },
      { slug: 'pathfinder', name: 'Pathfinder', years: 'Alle bouwjaren' },
      { slug: 'patrol', name: 'Patrol', years: 'Alle bouwjaren' },
      { slug: 'pixo', name: 'Pixo', years: 'Alle bouwjaren' },
      { slug: 'primastar', name: 'Primastar', years: 'Alle bouwjaren' },
      { slug: 'primera', name: 'Primera', years: 'Alle bouwjaren' },
      { slug: 'qashqai', name: 'Qashqai', years: 'Alle bouwjaren' },
      { slug: 'qashqai2', name: 'Qashqai+2', years: 'Alle bouwjaren' },
      { slug: 'serena', name: 'Serena', years: 'Alle bouwjaren' },
      { slug: 'skyline', name: 'Skyline', years: 'Alle bouwjaren' },
      { slug: 'sunny', name: 'Sunny', years: 'Alle bouwjaren' },
      { slug: 'terrano', name: 'Terrano', years: 'Alle bouwjaren' },
      { slug: 'townstar', name: 'Townstar', years: 'Alle bouwjaren' },
      { slug: 'x-trail', name: 'X-Trail', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'honda', name: 'Honda', nameSlug: 'honda', priority: 'P2',
    system: 'Honda Immobiliser System',
    excerpt: 'Honda sleutel programmering specialist. Civic, Jazz, CR-V.',
    models: [
      { slug: 'accord', name: 'Accord', years: 'Alle bouwjaren' },
      { slug: 'civic', name: 'Civic', years: 'Alle bouwjaren' },
      { slug: 'cr-v', name: 'CR-V', years: 'Alle bouwjaren' },
      { slug: 'cr-z', name: 'CR-Z', years: 'Alle bouwjaren' },
      { slug: 'fr-v', name: 'FR-V', years: 'Alle bouwjaren' },
      { slug: 'hr-v', name: 'HR-V', years: 'Alle bouwjaren' },
      { slug: 'insight', name: 'Insight', years: 'Alle bouwjaren' },
      { slug: 'jazz', name: 'Jazz', years: 'Alle bouwjaren' },
      { slug: 'legend', name: 'Legend', years: 'Alle bouwjaren' },
      { slug: 'logo', name: 'Logo', years: 'Alle bouwjaren' },
      { slug: 'nsx', name: 'NSX', years: 'Alle bouwjaren' },
      { slug: 'prelude', name: 'Prelude', years: 'Alle bouwjaren' },
      { slug: 's2000', name: 'S2000', years: 'Alle bouwjaren' },
      { slug: 'stream', name: 'Stream', years: 'Alle bouwjaren' },
      { slug: 'e', name: 'e', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'land-rover', name: 'Land Rover', nameSlug: 'land-rover', priority: 'P3',
    system: 'JLR KVM / RFA / BCM',
    excerpt: 'Land Rover sleutel specialist. Range Rover, Discovery, Evoque. KVM module specialist.',
    customSeoBlurb: 'Wij ontvangen regelmatig aanvragen voor Land Rover Freelander sleutel bijmaken en Range Rover Sport autosleutel bij laten maken. De Freelander (1997-2014) heeft een KVM-systeem dat directe OBD-programmering vereist. De Range Rover Sport (2005+) gebruikt een modern RFA-module systeem. Wij werken met JLR-software voor alle Land Rover modellen.',
    models: [
      { slug: 'defender', name: 'Defender', years: 'Alle bouwjaren' },
      { slug: 'discovery', name: 'Discovery', years: 'Alle bouwjaren' },
      { slug: 'discovery-sport', name: 'Discovery Sport', years: 'Alle bouwjaren' },
      { slug: 'freelander', name: 'Freelander', years: 'Alle bouwjaren' },
      { slug: 'range-rover', name: 'Range Rover', years: 'Alle bouwjaren' },
      { slug: 'range-rover-evoque', name: 'Range Rover Evoque', years: 'Alle bouwjaren' },
      { slug: 'range-rover-sport', name: 'Range Rover Sport', years: 'Alle bouwjaren' },
      { slug: 'range-rover-velar', name: 'Range Rover Velar', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'porsche', name: 'Porsche', nameSlug: 'porsche', priority: 'P3',
    system: 'Porsche KESSY / BCM',
    excerpt: 'Porsche sleutel specialist. 911, Cayenne, Macan, Panamera.',
    models: [
      { slug: '911', name: '911', years: 'Alle bouwjaren' },
      { slug: '968', name: '968', years: 'Alle bouwjaren' },
      { slug: 'boxster', name: 'Boxster', years: 'Alle bouwjaren' },
      { slug: 'panamera', name: 'Panamera', years: 'Alle bouwjaren' },
      { slug: 'macan', name: 'Macan', years: 'Alle bouwjaren' },
      { slug: 'cayenne', name: 'Cayenne', years: 'Alle bouwjaren' },
      { slug: 'cayman', name: 'Cayman', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'tesla', name: 'Tesla', nameSlug: 'tesla', priority: 'P3',
    system: 'Tesla Key Card / NFC',
    excerpt: 'Tesla sleutel kaart & fob specialist. Model 3, Y, S, X.',
    models: [
      { slug: 'cybertruck', name: 'Cybertruck', years: 'Alle bouwjaren' },
      { slug: 'model-3', name: 'Model 3', years: 'Alle bouwjaren' },
      { slug: 'model-s', name: 'Model S', years: 'Alle bouwjaren' },
      { slug: 'model-x', name: 'Model X', years: 'Alle bouwjaren' },
      { slug: 'model-y', name: 'Model Y', years: 'Alle bouwjaren' },
      { slug: 'roadster', name: 'Roadster', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'lexus', name: 'Lexus', nameSlug: 'lexus', priority: 'P2',
    system: 'Toyota/Lexus Smart Key',
    excerpt: 'Lexus sleutel specialist. RX, NX, IS, ES.',
    models: [
      { slug: 'ct', name: 'CT', years: 'Alle bouwjaren' },
      { slug: 'es', name: 'ES', years: 'Alle bouwjaren' },
      { slug: 'gs', name: 'GS', years: 'Alle bouwjaren' },
      { slug: 'is', name: 'IS', years: 'Alle bouwjaren' },
      { slug: 'lc', name: 'LC', years: 'Alle bouwjaren' },
      { slug: 'lfa', name: 'LFA', years: 'Alle bouwjaren' },
      { slug: 'ls', name: 'LS', years: 'Alle bouwjaren' },
      { slug: 'nx', name: 'NX', years: 'Alle bouwjaren' },
      { slug: 'rc', name: 'RC', years: 'Alle bouwjaren' },
      { slug: 'rx', name: 'RX', years: 'Alle bouwjaren' },
      { slug: 'rz', name: 'RZ', years: 'Alle bouwjaren' },
      { slug: 'sc', name: 'SC', years: 'Alle bouwjaren' },
      { slug: 'ux', name: 'UX', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'mini', name: 'Mini', nameSlug: 'mini', priority: 'P2',
    system: 'BMW CAS / FEM',
    excerpt: 'Mini sleutel specialist. Cooper, One, Countryman.',
    models: [
      { slug: 'clubman', name: 'Clubman', years: 'Alle bouwjaren' },
      { slug: 'convertible', name: 'Convertible', years: 'Alle bouwjaren' },
      { slug: 'cooper', name: 'Cooper', years: 'Alle bouwjaren' },
      { slug: 'countryman', name: 'Countryman', years: 'Alle bouwjaren' },
      { slug: 'coupe', name: 'Coupe', years: 'Alle bouwjaren' },
      { slug: 'paceman', name: 'Paceman', years: 'Alle bouwjaren' },
      { slug: 'roadster', name: 'Roadster', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'citroen', name: 'Citroën', nameSlug: 'citroen', priority: 'P2',
    system: 'PSA BSI / CAN Bus',
    excerpt: 'Citroën sleutel specialist. C1, C3, C4, Berlingo.',
    models: [
      { slug: 'ami', name: 'AMI', years: 'Alle bouwjaren' },
      { slug: 'berlingo', name: 'Berlingo', years: 'Alle bouwjaren' },
      { slug: 'c-crosser', name: 'C-Crosser', years: 'Alle bouwjaren' },
      { slug: 'c-elyse', name: 'C-Elysée', years: 'Alle bouwjaren' },
      { slug: 'c-zero', name: 'C-Zero', years: 'Alle bouwjaren' },
      { slug: 'c1', name: 'C1', years: 'Alle bouwjaren' },
      { slug: 'c2', name: 'C2', years: 'Alle bouwjaren' },
      { slug: 'c3', name: 'C3', years: 'Alle bouwjaren' },
      { slug: 'c3-aircross', name: 'C3 Aircross', years: 'Alle bouwjaren' },
      { slug: 'c3-picasso', name: 'C3 Picasso', years: 'Alle bouwjaren' },
      { slug: 'c4', name: 'C4', years: 'Alle bouwjaren' },
      { slug: 'c4-aircross', name: 'C4 Aircross', years: 'Alle bouwjaren' },
      { slug: 'c4-cactus', name: 'C4 Cactus', years: 'Alle bouwjaren' },
      { slug: 'c4-picasso', name: 'C4 Picasso', years: 'Alle bouwjaren' },
      { slug: 'c4-spacetourer', name: 'C4 SpaceTourer', years: 'Alle bouwjaren' },
      { slug: 'c5', name: 'C5', years: 'Alle bouwjaren' },
      { slug: 'c5-aircross', name: 'C5 Aircross', years: 'Alle bouwjaren' },
      { slug: 'c5-x', name: 'C5 X', years: 'Alle bouwjaren' },
      { slug: 'c6', name: 'C6', years: 'Alle bouwjaren' },
      { slug: 'c8', name: 'C8', years: 'Alle bouwjaren' },
      { slug: 'ds3', name: 'DS3', years: 'Alle bouwjaren' },
      { slug: 'ds4', name: 'DS4', years: 'Alle bouwjaren' },
      { slug: 'ds5', name: 'DS5', years: 'Alle bouwjaren' },
      { slug: 'e-mehari', name: 'E-Mehari', years: 'Alle bouwjaren' },
      { slug: 'grand-c4-picasso', name: 'Grand C4 Picasso', years: 'Alle bouwjaren' },
      { slug: 'grand-c4-spacetourer', name: 'Grand C4 SpaceTourer', years: 'Alle bouwjaren' },
      { slug: 'jumper', name: 'Jumper', years: 'Alle bouwjaren' },
      { slug: 'jumpy', name: 'Jumpy', years: 'Alle bouwjaren' },
      { slug: 'nemo', name: 'Nemo', years: 'Alle bouwjaren' },
      { slug: 'saxo', name: 'Saxo', years: 'Alle bouwjaren' },
      { slug: 'spacetourer', name: 'SpaceTourer', years: 'Alle bouwjaren' },
      { slug: 'xsara', name: 'Xsara', years: 'Alle bouwjaren' },
      { slug: 'xsara-picasso', name: 'Xsara Picasso', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'alfa-romeo', name: 'Alfa Romeo', nameSlug: 'alfa-romeo', priority: 'P3',
    system: 'Marelli / CODE / RFHUB',
    excerpt: 'Alfa Romeo autosleutel programmering op locatie. Giulia, Stelvio, Giulietta, MiTo.',
    customSeoBlurb: 'Heeft u een nieuwe Alfa Romeo autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Alfa Romeo. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Giulia; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: '145', name: '145', years: 'Alle bouwjaren' },
      { slug: '146', name: '146', years: 'Alle bouwjaren' },
      { slug: '147', name: '147', years: 'Alle bouwjaren' },
      { slug: '156', name: '156', years: 'Alle bouwjaren' },
      { slug: '159', name: '159', years: 'Alle bouwjaren' },
      { slug: '166', name: '166', years: 'Alle bouwjaren' },
      { slug: '4c', name: '4C', years: 'Alle bouwjaren' },
      { slug: '8c', name: '8C', years: 'Alle bouwjaren' },
      { slug: 'brera', name: 'Brera', years: 'Alle bouwjaren' },
      { slug: 'giulia', name: 'Giulia', years: 'Alle bouwjaren' },
      { slug: 'giulietta', name: 'Giulietta', years: 'Alle bouwjaren' },
      { slug: 'gt', name: 'GT', years: 'Alle bouwjaren' },
      { slug: 'gtv', name: 'GTV', years: 'Alle bouwjaren' },
      { slug: 'mito', name: 'MiTo', years: 'Alle bouwjaren' },
      { slug: 'spider', name: 'Spider', years: 'Alle bouwjaren' },
      { slug: 'stelvio', name: 'Stelvio', years: 'Alle bouwjaren' },
      { slug: 'tonale', name: 'Tonale', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'buick', name: 'Buick', nameSlug: 'buick', priority: 'P3',
    system: 'GM PASS-Key / PK3 / Global A',
    excerpt: 'Buick autosleutel programmering op locatie. Encore, Envision, Regal.',
    customSeoBlurb: 'Heeft u een nieuwe Buick autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Buick. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Encore; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'encore', name: 'Encore', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'envision', name: 'Envision', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'regal', name: 'Regal', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'cadillac', name: 'Cadillac', nameSlug: 'cadillac', priority: 'P3',
    system: 'GM Global A / Global B / PK3',
    excerpt: 'Cadillac autosleutel programmering op locatie. Escalade, CTS, XT5, ATS.',
    customSeoBlurb: 'Heeft u een nieuwe Cadillac autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Cadillac. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Escalade; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'escalade', name: 'Escalade', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'cts', name: 'CTS', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'xt5', name: 'XT5', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'ats', name: 'ATS', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'chery', name: 'Chery', nameSlug: 'chery', priority: 'P3',
    system: 'Chery Immo / Smart Key',
    excerpt: 'Chery autosleutel programmering op locatie. Tiggo, QQ, Arrizo.',
    customSeoBlurb: 'Heeft u een nieuwe Chery autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Chery. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Tiggo; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'tiggo', name: 'Tiggo', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'qq', name: 'QQ', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'arrizo', name: 'Arrizo', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'chevrolet', name: 'Chevrolet', nameSlug: 'chevrolet', priority: 'P3',
    system: 'GM Global A / Global B',
    excerpt: 'Chevrolet autosleutel programmering op locatie. Spark, Matiz, Captiva, Cruze, Corvette.',
    customSeoBlurb: 'Heeft u een nieuwe Chevrolet autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Chevrolet. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Spark; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'spark', name: 'Spark', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'matiz', name: 'Matiz', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'captiva', name: 'Captiva', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'cruze', name: 'Cruze', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'corvette', name: 'Corvette', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'chrysler', name: 'Chrysler', nameSlug: 'chrysler', priority: 'P3',
    system: 'FOBIK / SKIM / SKREEM',
    excerpt: 'Chrysler autosleutel programmering op locatie. 300C, Voyager, PT Cruiser.',
    customSeoBlurb: 'Heeft u een nieuwe Chrysler autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Chrysler. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw 300C; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: '300c', name: '300C', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'voyager', name: 'Voyager', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'pt-cruiser', name: 'PT Cruiser', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'cobra', name: 'Cobra', nameSlug: 'cobra', priority: 'P3',
    system: 'Aftermarket Immo / Basic',
    excerpt: 'Cobra autosleutel programmering op locatie. AC Cobra.',
    customSeoBlurb: 'Heeft u een nieuwe Cobra autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Cobra. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw AC Cobra; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'ac-cobra', name: 'AC Cobra', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'dacia', name: 'Dacia', nameSlug: 'dacia', priority: 'P3',
    system: 'Renault UCH / HFM',
    excerpt: 'Dacia autosleutel programmering op locatie. Duster, Sandero, Logan, Spring.',
    customSeoBlurb: 'Heeft u een nieuwe Dacia autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Dacia. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Duster; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'duster', name: 'Duster', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'sandero', name: 'Sandero', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'logan', name: 'Logan', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'spring', name: 'Spring', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'daewoo', name: 'Daewoo', nameSlug: 'daewoo', priority: 'P3',
    system: 'GM / Megamos',
    excerpt: 'Daewoo autosleutel programmering op locatie. Matiz, Kalos, Lanos.',
    customSeoBlurb: 'Heeft u een nieuwe Daewoo autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Daewoo. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Matiz; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'matiz', name: 'Matiz', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'kalos', name: 'Kalos', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'lanos', name: 'Lanos', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'daf', name: 'DAF', nameSlug: 'daf', priority: 'P3',
    system: 'DAF Immo (Truck)',
    excerpt: 'DAF autosleutel programmering op locatie. XF, CF, LF.',
    customSeoBlurb: 'Heeft u een nieuwe DAF autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw DAF. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw XF; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'xf', name: 'XF', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'cf', name: 'CF', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'lf', name: 'LF', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'daihatsu', name: 'Daihatsu', nameSlug: 'daihatsu', priority: 'P3',
    system: 'Toyota Immo / 4C / 4D',
    excerpt: 'Daihatsu autosleutel programmering op locatie. Cuore, Sirion, Terios.',
    customSeoBlurb: 'Heeft u een nieuwe Daihatsu autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Daihatsu. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Cuore; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'cuore', name: 'Cuore', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'sirion', name: 'Sirion', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'terios', name: 'Terios', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'dodge', name: 'Dodge', nameSlug: 'dodge', priority: 'P3',
    system: 'FOBIK / RFHUB',
    excerpt: 'Dodge autosleutel programmering op locatie. RAM, Challenger, Charger, Caliber.',
    customSeoBlurb: 'Heeft u een nieuwe Dodge autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Dodge. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw RAM; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'ram', name: 'RAM', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'challenger', name: 'Challenger', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'charger', name: 'Charger', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'caliber', name: 'Caliber', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'ferrari', name: 'Ferrari', nameSlug: 'ferrari', priority: 'P3',
    system: 'Marelli / CODE / Keyless',
    excerpt: 'Ferrari autosleutel programmering op locatie. 458, 488, California, F430.',
    customSeoBlurb: 'Heeft u een nieuwe Ferrari autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Ferrari. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw 458; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: '458', name: '458', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: '488', name: '488', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'california', name: 'California', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'f430', name: 'F430', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'holden', name: 'Holden', nameSlug: 'holden', priority: 'P3',
    system: 'GM Global A',
    excerpt: 'Holden autosleutel programmering op locatie. Commodore, Colorado.',
    customSeoBlurb: 'Heeft u een nieuwe Holden autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Holden. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Commodore; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'commodore', name: 'Commodore', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'colorado', name: 'Colorado', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'infiniti', name: 'Infiniti', nameSlug: 'infiniti', priority: 'P3',
    system: 'Nissan NATS / BCM',
    excerpt: 'Infiniti autosleutel programmering op locatie. Q50, Q30, FX35.',
    customSeoBlurb: 'Heeft u een nieuwe Infiniti autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Infiniti. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Q50; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'q50', name: 'Q50', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'q30', name: 'Q30', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'fx35', name: 'FX35', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'isuzu', name: 'Isuzu', nameSlug: 'isuzu', priority: 'P3',
    system: 'Isuzu Immo / GM',
    excerpt: 'Isuzu autosleutel programmering op locatie. D-Max, N-Series.',
    customSeoBlurb: 'Heeft u een nieuwe Isuzu autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Isuzu. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw D-Max; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'd-max', name: 'D-Max', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'n-series', name: 'N-Series', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'iveco', name: 'Iveco', nameSlug: 'iveco', priority: 'P3',
    system: 'Fiat CODE / BSI',
    excerpt: 'Iveco autosleutel programmering op locatie. Daily, Eurocargo.',
    customSeoBlurb: 'Heeft u een nieuwe Iveco autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Iveco. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Daily; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'daily', name: 'Daily', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'eurocargo', name: 'Eurocargo', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'jaguar', name: 'Jaguar', nameSlug: 'jaguar', priority: 'P3',
    system: 'KVM / BCM / JLR',
    excerpt: 'Jaguar autosleutel programmering op locatie. F-Type, XF, XE, F-Pace.',
    customSeoBlurb: 'Heeft u een nieuwe Jaguar autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Jaguar. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw F-Type; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'f-type', name: 'F-Type', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'xf', name: 'XF', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'xe', name: 'XE', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'f-pace', name: 'F-Pace', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'lada', name: 'Lada', nameSlug: 'lada', priority: 'P3',
    system: 'Renault UCH / Basic',
    excerpt: 'Lada autosleutel programmering op locatie. Niva, Vesta.',
    customSeoBlurb: 'Heeft u een nieuwe Lada autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Lada. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Niva; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'niva', name: 'Niva', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'vesta', name: 'Vesta', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'lancia', name: 'Lancia', nameSlug: 'lancia', priority: 'P3',
    system: 'Fiat CODE / BSI',
    excerpt: 'Lancia autosleutel programmering op locatie. Ypsilon, Delta.',
    customSeoBlurb: 'Heeft u een nieuwe Lancia autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Lancia. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Ypsilon; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'ypsilon', name: 'Ypsilon', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'delta', name: 'Delta', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'lexus', name: 'Lexus', nameSlug: 'lexus', priority: 'P3',
    system: 'Toyota Smart Key / Immo',
    excerpt: 'Lexus autosleutel programmering op locatie. CT200h, RX, IS, NX.',
    customSeoBlurb: 'Heeft u een nieuwe Lexus autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Lexus. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw CT200h; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'ct', name: 'CT', years: 'Alle bouwjaren' },
      { slug: 'es', name: 'ES', years: 'Alle bouwjaren' },
      { slug: 'gs', name: 'GS', years: 'Alle bouwjaren' },
      { slug: 'is', name: 'IS', years: 'Alle bouwjaren' },
      { slug: 'lc', name: 'LC', years: 'Alle bouwjaren' },
      { slug: 'lfa', name: 'LFA', years: 'Alle bouwjaren' },
      { slug: 'ls', name: 'LS', years: 'Alle bouwjaren' },
      { slug: 'nx', name: 'NX', years: 'Alle bouwjaren' },
      { slug: 'rc', name: 'RC', years: 'Alle bouwjaren' },
      { slug: 'rx', name: 'RX', years: 'Alle bouwjaren' },
      { slug: 'rz', name: 'RZ', years: 'Alle bouwjaren' },
      { slug: 'sc', name: 'SC', years: 'Alle bouwjaren' },
      { slug: 'ux', name: 'UX', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'lincoln', name: 'Lincoln', nameSlug: 'lincoln', priority: 'P3',
    system: 'Ford PATS / BCM',
    excerpt: 'Lincoln autosleutel programmering op locatie. Navigator, Aviator, MKX.',
    customSeoBlurb: 'Heeft u een nieuwe Lincoln autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Lincoln. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Navigator; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'navigator', name: 'Navigator', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'aviator', name: 'Aviator', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'mkx', name: 'MKX', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'maserati', name: 'Maserati', nameSlug: 'maserati', priority: 'P3',
    system: 'Marelli / RFHUB',
    excerpt: 'Maserati autosleutel programmering op locatie. Ghibli, Levante, Quattroporte.',
    customSeoBlurb: 'Heeft u een nieuwe Maserati autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Maserati. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Ghibli; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'ghibli', name: 'Ghibli', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'levante', name: 'Levante', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'quattroporte', name: 'Quattroporte', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'mclaren', name: 'McLaren', nameSlug: 'mclaren', priority: 'P3',
    system: 'McLaren Smart Key',
    excerpt: 'McLaren autosleutel programmering op locatie. 570S, 720S, MP4-12C.',
    customSeoBlurb: 'Heeft u een nieuwe McLaren autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw McLaren. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw 570S; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: '570s', name: '570S', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: '720s', name: '720S', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'mp4-12c', name: 'MP4-12C', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'mitsubishi', name: 'Mitsubishi', nameSlug: 'mitsubishi', priority: 'P3',
    system: 'ETACS / KOS',
    excerpt: 'Mitsubishi autosleutel programmering op locatie. Outlander, Space Star, Colt, ASX.',
    customSeoBlurb: 'Heeft u een nieuwe Mitsubishi autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Mitsubishi. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Outlander; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'outlander', name: 'Outlander', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'space-star', name: 'Space Star', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'colt', name: 'Colt', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'asx', name: 'ASX', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'oldsmobile', name: 'Oldsmobile', nameSlug: 'oldsmobile', priority: 'P3',
    system: 'GM PASS-Key',
    excerpt: 'Oldsmobile autosleutel programmering op locatie. Aurora, Alero.',
    customSeoBlurb: 'Heeft u een nieuwe Oldsmobile autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Oldsmobile. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Aurora; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'aurora', name: 'Aurora', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'alero', name: 'Alero', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'proton', name: 'Proton', nameSlug: 'proton', priority: 'P3',
    system: 'Bosch / Megamos',
    excerpt: 'Proton autosleutel programmering op locatie. Wira, Gen-2.',
    customSeoBlurb: 'Heeft u een nieuwe Proton autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Proton. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Wira; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'wira', name: 'Wira', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'gen-2', name: 'Gen-2', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'rolls-royce', name: 'Rolls Royce', nameSlug: 'rolls-royce', priority: 'P3',
    system: 'BMW CAS / FEM / BDC',
    excerpt: 'Rolls Royce autosleutel programmering op locatie. Phantom, Ghost, Cullinan.',
    customSeoBlurb: 'Heeft u een nieuwe Rolls Royce autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Rolls Royce. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Phantom; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'phantom', name: 'Phantom', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'ghost', name: 'Ghost', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'cullinan', name: 'Cullinan', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'rover', name: 'Rover', nameSlug: 'rover', priority: 'P3',
    system: 'Lucas / Pektron',
    excerpt: 'Rover autosleutel programmering op locatie. 75, 45, 25.',
    customSeoBlurb: 'Heeft u een nieuwe Rover autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Rover. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw 75; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: '75', name: '75', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: '45', name: '45', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: '25', name: '25', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'saab', name: 'Saab', nameSlug: 'saab', priority: 'P3',
    system: 'CIM / TWICE',
    excerpt: 'Saab autosleutel programmering op locatie. 9-3, 9-5.',
    customSeoBlurb: 'Heeft u een nieuwe Saab autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Saab. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw 9-3; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: '9-3', name: '9-3', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: '9-5', name: '9-5', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'smart', name: 'Smart', nameSlug: 'smart', priority: 'P3',
    system: 'SAM / DAS',
    excerpt: 'Smart autosleutel programmering op locatie. Fortwo, Forfour.',
    customSeoBlurb: 'Heeft u een nieuwe Smart autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Smart. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Fortwo; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'fortwo', name: 'Fortwo', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'forfour', name: 'Forfour', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'ssangyong', name: 'SsangYong', nameSlug: 'ssangyong', priority: 'P3',
    system: 'Delphi / REKES',
    excerpt: 'SsangYong autosleutel programmering op locatie. Rexton, Korando, Tivoli.',
    customSeoBlurb: 'Heeft u een nieuwe SsangYong autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw SsangYong. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Rexton; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'rexton', name: 'Rexton', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'korando', name: 'Korando', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'tivoli', name: 'Tivoli', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'subaru', name: 'Subaru', nameSlug: 'subaru', priority: 'P3',
    system: 'Subaru Smart Key / Immo',
    excerpt: 'Subaru autosleutel programmering op locatie. Impreza, Forester, Outback.',
    customSeoBlurb: 'Heeft u een nieuwe Subaru autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Subaru. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Impreza; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'impreza', name: 'Impreza', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'forester', name: 'Forester', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'outback', name: 'Outback', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'suzuki', name: 'Suzuki', nameSlug: 'suzuki', priority: 'P3',
    system: 'Suzuki Immo / Keyless',
    excerpt: 'Suzuki autosleutel programmering op locatie. Swift, Alto, Vitara, Ignis.',
    customSeoBlurb: 'Heeft u een nieuwe Suzuki autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Suzuki. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Swift; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'swift', name: 'Swift', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'alto', name: 'Alto', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'vitara', name: 'Vitara', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'ignis', name: 'Ignis', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  },
  {
    slug: 'tesla', name: 'Tesla', nameSlug: 'tesla', priority: 'P3',
    system: 'NFC / BLE / RFID',
    excerpt: 'Tesla autosleutel programmering op locatie. Model S, Model 3, Model X, Model Y.',
    customSeoBlurb: 'Heeft u een nieuwe Tesla autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Tesla. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Model S; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'cybertruck', name: 'Cybertruck', years: 'Alle bouwjaren' },
      { slug: 'model-3', name: 'Model 3', years: 'Alle bouwjaren' },
      { slug: 'model-s', name: 'Model S', years: 'Alle bouwjaren' },
      { slug: 'model-x', name: 'Model X', years: 'Alle bouwjaren' },
      { slug: 'model-y', name: 'Model Y', years: 'Alle bouwjaren' },
      { slug: 'roadster', name: 'Roadster', years: 'Alle bouwjaren' },
    ],
  },
  {
    slug: 'gmc', name: 'GMC', nameSlug: 'gmc', priority: 'P3',
    system: 'GM Global A / PK3',
    excerpt: 'GMC autosleutel programmering op locatie. Sierra, Yukon, Acadia.',
    customSeoBlurb: 'Heeft u een nieuwe GMC autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw GMC. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Sierra; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'sierra', name: 'Sierra', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'yukon', name: 'Yukon', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'acadia', name: 'Acadia', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  }
,
  {
    slug: 'bentley', name: 'Bentley', nameSlug: 'bentley', priority: 'P3',
    system: 'VW Group / KESSY',
    excerpt: 'Bentley autosleutel programmering op locatie. Continental GT, Bentayga, Flying Spur.',
    customSeoBlurb: 'Heeft u een nieuwe Bentley autosleutel nodig? Wij maken direct ter plaatse een nieuwe sleutel of smart key voor uw Bentley. Of u nu al uw sleutels kwijt bent of gewoon een reservesleutel zoekt voor uw Continental GT; wij bieden dealer-kwaliteit voor een lagere prijs.',
    models: [
      { slug: 'continental-gt', name: 'Continental GT', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'bentayga', name: 'Bentayga', years: '2016, 2017, 2018, 2019, 2020, 2021, 2022' },
      { slug: 'flying-spur', name: 'Flying Spur', years: '2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022' }
    ],
  }
];
