export type City = {
  slug: string; city: string; region: string; country: 'NL' | 'BE' | 'DE';
  lang: 'NL' | 'FR' | 'VL'; travelTime: string; keyword: string; nlSearches: number; priority: 'P1'|'P2'|'P3';
  subAreas: string[]; reviewQuote: string; reviewAuthor: string; reviewCar: string;
  geo: { lat: string; lng: string };
};

export const CITIES: City[] = [
  { slug:"utrecht", city:"Utrecht", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Utrecht", nlSearches:480, priority:"P1", subAreas:[], reviewQuote:"Audi Q5 keyless entry defect. Gerepareerd in 45 minuten. Indrukwekkend.", reviewAuthor:"H. Janssen", reviewCar:"Audi Q5", geo:{"lat":"52.0907","lng":"5.1214"} },
  { slug:"utrecht-centrum", city:"Utrecht Centrum", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Utrecht Centrum", nlSearches:100, priority:"P2", subAreas:[], reviewQuote:"Snelle service in het centrum.", reviewAuthor:"M. de Boer", reviewCar:"BMW 3 Serie", geo:{"lat":"52.0907","lng":"5.1214"} },
  { slug:"utrecht-zuid", city:"Utrecht Zuid", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Utrecht Zuid", nlSearches:100, priority:"P2", subAreas:[], reviewQuote:"Top service in Zuid.", reviewAuthor:"K. Visser", reviewCar:"VW Golf", geo:{"lat":"52.0907","lng":"5.1214"} },
  { slug:"amsterdam", city:"Amsterdam", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"45-60 min", keyword:"autosleutel programmeren Amsterdam", nlSearches:1320, priority:"P1", subAreas:[], reviewQuote:"Porsche Cayenne sleutel kwijt in Amsterdam. Came all the way, fixed in 2 hours. Worth it.", reviewAuthor:"T. Bakker", reviewCar:"Porsche Cayenne", geo:{"lat":"52.3676","lng":"4.9041"} },
  { slug:"amsterdam-centrum", city:"Amsterdam Centrum", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"45-60 min", keyword:"autosleutel programmeren Amsterdam Centrum", nlSearches:200, priority:"P2", subAreas:[], reviewQuote:"Midden in Amsterdam gestrand. Snel geholpen.", reviewAuthor:"J. Smit", reviewCar:"Audi A3", geo:{"lat":"52.3676","lng":"4.9041"} },
  { slug:"amsterdam-zuid", city:"Amsterdam Zuid", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"45-60 min", keyword:"autosleutel programmeren Amsterdam Zuid", nlSearches:200, priority:"P2", subAreas:[], reviewQuote:"Zuid as service top.", reviewAuthor:"R. de Vries", reviewCar:"Tesla Model 3", geo:{"lat":"52.3676","lng":"4.9041"} },
  { slug:"amersfoort", city:"Amersfoort", region:"Utrecht", country:"NL", lang:"NL", travelTime:"30-35 min", keyword:"autosleutel programmeren Amersfoort", nlSearches:245, priority:"P1", subAreas:[], reviewQuote:"Kia Sportage sleutel kwijt. Snel en professioneel.", reviewAuthor:"D. Meijer", reviewCar:"Kia Sportage", geo:{"lat":"52.1561","lng":"5.3878"} },
  { slug:"almere", city:"Almere", region:"Flevoland", country:"NL", lang:"NL", travelTime:"35-45 min", keyword:"autosleutel programmeren Almere", nlSearches:323, priority:"P1", subAreas:[], reviewQuote:"Tesla Model Y keycard programmering. Unieke specialist.", reviewAuthor:"O. van Leeuwen", reviewCar:"Tesla Model Y", geo:{"lat":"52.3702","lng":"5.2176"} },
  { slug:"ede", city:"Ede", region:"Gelderland", country:"NL", lang:"NL", travelTime:"40-50 min", keyword:"autosleutel programmeren Ede", nlSearches:150, priority:"P1", subAreas:[], reviewQuote:"Nieuwe sleutel voor mijn bedrijfsbus op locatie gemaakt.", reviewAuthor:"L. Vermeer", reviewCar:"Ford Transit", geo:{"lat":"52.0435","lng":"5.6666"} },
  { slug:"nieuwegein", city:"Nieuwegein", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Nieuwegein", nlSearches:100, priority:"P1", subAreas:[], reviewQuote:"Zeer snelle service in Nieuwegein.", reviewAuthor:"B. Janssen", reviewCar:"Opel Corsa", geo:{"lat":"52.0305","lng":"5.0934"} },
  { slug:"veenendaal", city:"Veenendaal", region:"Utrecht", country:"NL", lang:"NL", travelTime:"35-45 min", keyword:"autosleutel programmeren Veenendaal", nlSearches:90, priority:"P1", subAreas:[], reviewQuote:"Snel ter plaatse in Veenendaal.", reviewAuthor:"G. Peters", reviewCar:"VW Polo", geo:{"lat":"52.0286","lng":"5.5552"} },
  { slug:"zeist", city:"Zeist", region:"Utrecht", country:"NL", lang:"NL", travelTime:"18-22 min", keyword:"autosleutel programmeren Zeist", nlSearches:120, priority:"P1", subAreas:[], reviewQuote:"Top service in Zeist voor mijn BMW.", reviewAuthor:"H. van Dijk", reviewCar:"BMW 5 Serie", geo:{"lat":"52.0886","lng":"5.2359"} },
  { slug:"houten", city:"Houten", region:"Utrecht", country:"NL", lang:"NL", travelTime:"18-22 min", keyword:"autosleutel programmeren Houten", nlSearches:80, priority:"P1", subAreas:[], reviewQuote:"Goede hulp in Houten.", reviewAuthor:"M. Bos", reviewCar:"Peugeot 208", geo:{"lat":"52.0270","lng":"5.1654"} },
  { slug:"soest", city:"Soest", region:"Utrecht", country:"NL", lang:"NL", travelTime:"35-40 min", keyword:"autosleutel programmeren Soest", nlSearches:70, priority:"P1", subAreas:[], reviewQuote:"Sleutel ter plaatse geprogrammeerd in Soest. Uitstekende service.", reviewAuthor:"J. de Ruiter", reviewCar:"VW Polo", geo:{"lat":"52.1736","lng":"5.2913"} },
  { slug:"hilversum", city:"Hilversum", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"35-42 min", keyword:"autosleutel programmeren Hilversum", nlSearches:135, priority:"P1", subAreas:[], reviewQuote:"Snelle service in Hilversum, nieuwe reservesleutel voor mijn Ford.", reviewAuthor:"T. Bos", reviewCar:"Ford Fiesta", geo:{"lat":"52.2292","lng":"5.1669"} },
  { slug:"gouda", city:"Gouda", region:"Zuid-Holland", country:"NL", lang:"NL", travelTime:"40-50 min", keyword:"autosleutel programmeren Gouda", nlSearches:110, priority:"P1", subAreas:[], reviewQuote:"Golf 7 sleutel kwijt in Gouda. Autosleutel24 hielp ons binnen 45 minuten.", reviewAuthor:"M. Verhoeven", reviewCar:"VW Golf 7", geo:{"lat":"52.0116","lng":"4.7105"} },
  { slug:"woerden", city:"Woerden", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Woerden", nlSearches:60, priority:"P1", subAreas:[], reviewQuote:"Mijn Seat sleutel was kapot, vlot opgelost in Woerden.", reviewAuthor:"P. de Wit", reviewCar:"Seat Ibiza", geo:{"lat":"52.0863","lng":"4.8838"} },
  { slug:"de-bilt", city:"De Bilt", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-18 min", keyword:"autosleutel programmeren De Bilt", nlSearches:50, priority:"P1", subAreas:[], reviewQuote:"Snelle reservesleutel in De Bilt.", reviewAuthor:"K. Jansen", reviewCar:"Volvo V40", geo:{"lat":"52.1093","lng":"5.1833"} },
  { slug:"maarssen", city:"Maarssen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Maarssen", nlSearches:45, priority:"P1", subAreas:[], reviewQuote:"Vriendelijk en snel geholpen in Maarssen.", reviewAuthor:"A. Willems", reviewCar:"Renault Clio", geo:{"lat":"52.1408","lng":"5.0396"} },
  { slug:"culemborg", city:"Culemborg", region:"Gelderland", country:"NL", lang:"NL", travelTime:"35-45 min", keyword:"autosleutel programmeren Culemborg", nlSearches:43, priority:"P1", subAreas:[], reviewQuote:"Mercedes sleutel bijgemaakt in Culemborg. Vakman!", reviewAuthor:"A. Bakker", reviewCar:"Mercedes C-Klasse", geo:{"lat":"51.9542","lng":"5.2289"} },
  { slug:"leusden", city:"Leusden", region:"Utrecht", country:"NL", lang:"NL", travelTime:"32-38 min", keyword:"autosleutel programmeren Leusden", nlSearches:45, priority:"P1", subAreas:[], reviewQuote:"Autosleutel bijgemaakt in Leusden binnen een half uur.", reviewAuthor:"G. Hendriks", reviewCar:"Opel Corsa", geo:{"lat":"52.1326","lng":"5.4294"} },
  { slug:"baarn", city:"Baarn", region:"Utrecht", country:"NL", lang:"NL", travelTime:"38-45 min", keyword:"autosleutel programmeren Baarn", nlSearches:40, priority:"P1", subAreas:[], reviewQuote:"Zeer tevreden over de service in Baarn.", reviewAuthor:"L. de Groot", reviewCar:"Skoda Octavia", geo:{"lat":"52.2125","lng":"5.2933"} },
  { slug:"wijk-bij-duurstede", city:"Wijk bij Duurstede", region:"Utrecht", country:"NL", lang:"NL", travelTime:"30-35 min", keyword:"autosleutel programmeren Wijk bij Duurstede", nlSearches:35, priority:"P1", subAreas:[], reviewQuote:"Nieuwe sleutel perfect ingeleerd.", reviewAuthor:"S. Mulder", reviewCar:"Toyota Aygo", geo:{"lat":"51.9723","lng":"5.3444"} },
  { slug:"ijsselstein", city:"IJsselstein", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren IJsselstein", nlSearches:60, priority:"P1", subAreas:[], reviewQuote:"Mijn autosleutel was gestolen. Snel nieuwe gekregen in IJsselstein.", reviewAuthor:"N. Visser", reviewCar:"Ford Focus", geo:{"lat":"52.0200","lng":"5.0428"} },
  { slug:"vianen", city:"Vianen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"22-28 min", keyword:"autosleutel programmeren Vianen", nlSearches:30, priority:"P1", subAreas:[], reviewQuote:"Bedrijfswagen sleutel vlot bijgemaakt in Vianen.", reviewAuthor:"W. Brouwer", reviewCar:"Mercedes Sprinter", geo:{"lat":"51.9930","lng":"5.0933"} },
  { slug:"bunnik", city:"Bunnik", region:"Utrecht", country:"NL", lang:"NL", travelTime:"18-22 min", keyword:"autosleutel programmeren Bunnik", nlSearches:25, priority:"P1", subAreas:[], reviewQuote:"Prima service in Bunnik.", reviewAuthor:"E. de Jong", reviewCar:"VW Up", geo:{"lat":"52.0667","lng":"5.2000"} },
  { slug:"oudewater", city:"Oudewater", region:"Utrecht", country:"NL", lang:"NL", travelTime:"30-35 min", keyword:"autosleutel programmeren Oudewater", nlSearches:20, priority:"P1", subAreas:[], reviewQuote:"Top monteur, sleutel werkt weer als nieuw.", reviewAuthor:"T. Dekker", reviewCar:"Nissan Qashqai", geo:{"lat":"52.0238","lng":"4.8736"} },
  { slug:"montfoort", city:"Montfoort", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Montfoort", nlSearches:20, priority:"P1", subAreas:[], reviewQuote:"Snel opgelost in Montfoort.", reviewAuthor:"C. Koster", reviewCar:"Fiat 500", geo:{"lat":"52.0444","lng":"4.9494"} },
  { slug:"lopik", city:"Lopik", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Lopik", nlSearches:15, priority:"P1", subAreas:[], reviewQuote:"Vakkundig en vriendelijk in Lopik.", reviewAuthor:"J. van der Berg", reviewCar:"Renault Trafic", geo:{"lat":"51.9723","lng":"4.9453"} },
  { slug:"breukelen", city:"Breukelen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Breukelen", nlSearches:35, priority:"P1", subAreas:[], reviewQuote:"Sleutel bijmaken was snel geregeld.", reviewAuthor:"F. Hoekstra", reviewCar:"Volvo XC60", geo:{"lat":"52.1717","lng":"4.9986"} },
  { slug:"abcoude", city:"Abcoude", region:"Utrecht", country:"NL", lang:"NL", travelTime:"18-22 min", keyword:"autosleutel programmeren Abcoude", nlSearches:20, priority:"P1", subAreas:[], reviewQuote:"Aanrader in Abcoude.", reviewAuthor:"A. de Ruiter", reviewCar:"Audi A1", geo:{"lat":"52.2725","lng":"4.9703"} },
  { slug:"mijdrecht", city:"Mijdrecht", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Mijdrecht", nlSearches:30, priority:"P1", subAreas:[], reviewQuote:"Goeie service voor mijn bedrijfsauto.", reviewAuthor:"M. Sanders", reviewCar:"VW Transporter", geo:{"lat":"52.2047","lng":"4.8647"} },
  { slug:"vinkeveen", city:"Vinkeveen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"30-35 min", keyword:"autosleutel programmeren Vinkeveen", nlSearches:25, priority:"P1", subAreas:[], reviewQuote:"Perfect geholpen in Vinkeveen.", reviewAuthor:"L. van Dijk", reviewCar:"Mini Cooper", geo:{"lat":"52.2117","lng":"4.9367"} },
  { slug:"gooise-meren", city:"Gooise Meren", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"40-50 min", keyword:"autosleutel programmeren Gooise Meren", nlSearches:60, priority:"P1", subAreas:[], reviewQuote:"Snel ter plekke in 't Gooi.", reviewAuthor:"P. Heinen", reviewCar:"BMW X3", geo:{"lat":"52.2858","lng":"5.1328"} },
  { slug:"amstelveen", city:"Amstelveen", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"40-50 min", keyword:"autosleutel programmeren Amstelveen", nlSearches:90, priority:"P1", subAreas:[], reviewQuote:"Nieuwe sleutel voor mijn leaseauto, snel en met factuur.", reviewAuthor:"R. Bakker", reviewCar:"Skoda Superb", geo:{"lat":"52.3022","lng":"4.8625"} },
  { slug:"diemen", city:"Diemen", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"35-45 min", keyword:"autosleutel programmeren Diemen", nlSearches:50, priority:"P1", subAreas:[], reviewQuote:"Sleutel kapot in Diemen, top geregeld.", reviewAuthor:"K. Visser", reviewCar:"Toyota Yaris", geo:{"lat":"52.3392","lng":"4.9606"} },
  { slug:"alphen-aan-den-rijn", city:"Alphen aan den Rijn", region:"Zuid-Holland", country:"NL", lang:"NL", travelTime:"45-55 min", keyword:"autosleutel programmeren Alphen aan den Rijn", nlSearches:112, priority:"P1", subAreas:[], reviewQuote:"Goede monteur, werkt snel.", reviewAuthor:"J. de Boer", reviewCar:"Ford Kuga", geo:{"lat":"52.1289","lng":"4.6603"} },
  { slug:"barneveld", city:"Barneveld", region:"Gelderland", country:"NL", lang:"NL", travelTime:"45-55 min", keyword:"autosleutel programmeren Barneveld", nlSearches:60, priority:"P1", subAreas:[], reviewQuote:"Vriendelijk en snel geholpen in Barneveld.", reviewAuthor:"S. Jansen", reviewCar:"Renault Kangoo", geo:{"lat":"52.1389","lng":"5.5867"} },
  { slug:"nijkerk", city:"Nijkerk", region:"Gelderland", country:"NL", lang:"NL", travelTime:"40-50 min", keyword:"autosleutel programmeren Nijkerk", nlSearches:45, priority:"P1", subAreas:[], reviewQuote:"Uitstekende noodservice in Nijkerk.", reviewAuthor:"D. Vos", reviewCar:"Peugeot Boxer", geo:{"lat":"52.2217","lng":"5.4853"} },
  { slug:"huizen", city:"Huizen", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"35-45 min", keyword:"autosleutel programmeren Huizen", nlSearches:85, priority:"P1", subAreas:[], reviewQuote:"Mijn Kia sleutel deed het niet meer. Ter plaatse in Huizen geprogrammeerd.", reviewAuthor:"M. de Jong", reviewCar:"Kia Picanto", geo:{"lat":"52.2989","lng":"5.2536"} },
  { slug:"amsterdam-oost", city:"Amsterdam Oost", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"45-60 min", keyword:"autosleutel programmeren Amsterdam Oost", nlSearches:150, priority:"P2", subAreas:[], reviewQuote:"In Amsterdam Oost gestrand met defecte sleutel. Binnen no-time opgelost.", reviewAuthor:"L. Peters", reviewCar:"Volvo V60", geo:{"lat":"52.3567","lng":"4.9286"} }
];


