export type City = {
  slug: string; city: string; region: string; country: "NL" | "BE" | "DE";
  lang: "NL" | "FR" | "VL"; travelTime: string; keyword: string; nlSearches: number; priority: "P1"|"P2"|"P3";
  subAreas: string[]; reviewQuote: string; reviewAuthor: string; reviewCar: string;
  geo: { lat: string; lng: string };
  customH1?: string;
  customMetaTitle?: string;
  customMetaDesc?: string;
  popularBrands?: string[];
  commonJob?: string;
  localFact?: string;
  avgJobDuration?: string;
};

export const CITIES: City[] = [
  { slug:"bussum", city:"Bussum", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"10-20 min", keyword:"autosleutel programmeren Bussum", nlSearches:210, priority:"P1", subAreas:["Bussum Centrum","Spiegel","Brediuskwartier","Eng","Zuid"], reviewQuote:"Bussum centrum autosleutel bijgemaakt ter plaatse. Topservice!", reviewAuthor:"K. van Leeuwen", reviewCar:"BMW 3 Serie", geo:{lat:"52.2740",lng:"5.1611"}, popularBrands:["BMW","Audi","Mercedes-Benz"], commonJob:"Smart key & keyless entry inleren", localFact:"In 't Gooi rijden relatief veel premium voertuigen. Wij zien dagelijks BMW, Audi en Mercedes waarvoor dealer-niveau programmering vereist is.", avgJobDuration:"30-45 min" },
  { slug:"utrecht", city:"Utrecht", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Utrecht", nlSearches:480, priority:"P1", subAreas:["Utrecht Centrum","Leidsche Rijn","Overvecht","Kanaleneiland","Lunetten","Vleuten-De Meern","Oost","West","Zuid"], reviewQuote:"Audi Q5 keyless entry defect. Gerepareerd in 45 minuten. Indrukwekkend.", reviewAuthor:"H. Janssen", reviewCar:"Audi Q5", geo:{lat:"52.0907",lng:"5.1214"}, popularBrands:["Volkswagen","Toyota","Opel"], commonJob:"Autosleutel kwijt in parkeergarage — noodopening & nieuwe sleutel", localFact:"Utrecht heeft veel drukke parkeergarages (Hoog Catharijne, Jaarbeursplein). Wij worden regelmatig gebeld door bestuurders die hun sleutel in de auto hebben laten liggen of kwijt zijn na een bezoek aan de binnenstad.", avgJobDuration:"25-40 min" },
  { slug:"hilversum", city:"Hilversum", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"15-25 min", keyword:"autosleutel programmeren Hilversum", nlSearches:185, priority:"P1", subAreas:["Centrum","Noord","Oost","Zuid","Media Park","Kerkelanden"], reviewQuote:"Snelle service in Hilversum, nieuwe reservesleutel voor mijn Ford.", reviewAuthor:"T. Bos", reviewCar:"Ford Fiesta", geo:{lat:"52.2292",lng:"5.1669"}, popularBrands:["BMW","Mercedes-Benz","Volvo"], commonJob:"Reservesleutel bijmaken voor leaseauto of zakelijke auto", localFact:"Rondom het Media Park in Hilversum rijden veel lease- en zakelijke voertuigen. Een extra sleutel bijmaken is hier een veelgevraagde dienst — snel, zonder ritje naar de dealer.", avgJobDuration:"30-45 min" },
  { slug:"amsterdam", city:"Amsterdam", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"25-35 min", keyword:"autosleutel programmeren Amsterdam", nlSearches:1320, priority:"P1", subAreas:["Amsterdam Centrum","Amsterdam Zuid","Amsterdam West","Amsterdam Oost","Amsterdam Noord","Zuidoost","Nieuw-West"], reviewQuote:"Porsche Cayenne autosleutel kwijt in Amsterdam. Fixed in 2 hours. Worth it.", reviewAuthor:"T. Bakker", reviewCar:"Porsche Cayenne", geo:{lat:"52.3676",lng:"4.9041"}, customH1:"Autosleutel Bijmaken Amsterdam Noord, Zuid & Centrum — Autosleutel Reparatie Amsterdam", customMetaTitle:"Autosleutel Bijmaken Amsterdam Noord & Reparatie | Autosleutel24", customMetaDesc:"Autosleutel bijmaken Amsterdam Noord, Zuid of Centrum? Snel, goedkoper dan de dealer. Bel direct!", popularBrands:["BMW","Tesla","Audi"], commonJob:"Keyless entry storing & smart key herprogrammering", localFact:"In Amsterdam rijden relatief veel Teslas en keyless-entry voertuigen. Door de drukte in de stad is een mobiele service bijzonder praktisch — wij komen direct naar uw parkeerplek, thuis of kantoor.", avgJobDuration:"35-55 min" },
  { slug:"rotterdam", city:"Rotterdam", region:"Zuid-Holland", country:"NL", lang:"NL", travelTime:"45-60 min", keyword:"autosleutel programmeren Rotterdam", nlSearches:900, priority:"P1", subAreas:["Rotterdam Centrum","Kop van Zuid","Kralingen","Delfshaven","Overschie","IJsselmonde","Zuid"], reviewQuote:"Snelle service in Rotterdam voor mijn BMW.", reviewAuthor:"S. de Jong", reviewCar:"BMW 3 Serie", geo:{lat:"51.9225",lng:"4.4791"}, popularBrands:["Volkswagen","Ford","Opel"], commonJob:"Bedrijfswagen sleutel bijmaken & transponder programmeren", localFact:"Rotterdam heeft een grote haven- en logistiekbranche. Wij leveren regelmatig reserve sleutels voor bedrijfsbussen op het terrein — snel ter plaatse zonder werkonderbreking.", avgJobDuration:"35-50 min" },
  { slug:"den-haag", city:"Den Haag", region:"Zuid-Holland", country:"NL", lang:"NL", travelTime:"45-60 min", keyword:"autosleutel programmeren Den Haag", nlSearches:850, priority:"P1", subAreas:["Centrum","Scheveningen","Kijkduin","Loosduinen","Segbroek","Escamp"], reviewQuote:"Binnen een uur in Den Haag. Top service!", reviewAuthor:"M. Visser", reviewCar:"Audi A4", geo:{lat:"52.0705",lng:"4.3007"}, popularBrands:["Mercedes-Benz","BMW","Volvo"], commonJob:"Contactslot reparatie & sleutel bijmaken", localFact:"In Den Haag rijden veel overheidsmedewerkers met premium leaseautos. Contactslotstoringen en kapotte sleutelkoppen zijn hier veelvoorkomende klachten die wij snel oplossen.", avgJobDuration:"35-50 min" },
  { slug:"amersfoort", city:"Amersfoort", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Amersfoort", nlSearches:245, priority:"P1", subAreas:["Vathorst","Kattenbroek","Nieuwland","Schothorst","Liendert","Hoogland","Randenbroek"], reviewQuote:"Kia Sportage autosleutel kwijt. Snel en professioneel.", reviewAuthor:"D. Meijer", reviewCar:"Kia Sportage", geo:{lat:"52.1561",lng:"5.3878"}, popularBrands:["Volkswagen","Seat","Dacia"], commonJob:"Reserve sleutel bijmaken — jong gezin, een sleutel te weinig", localFact:"Amersfoort groeit snel met nieuwe woonwijken als Vathorst. Jonge gezinnen met een autosleutel bellen ons regelmatig voor een betaalbare reserve — zonder afspraak bij de dealer.", avgJobDuration:"25-40 min" },
  { slug:"arnhem", city:"Arnhem", region:"Gelderland", country:"NL", lang:"NL", travelTime:"30-45 min", keyword:"autosleutel programmeren Arnhem", nlSearches:450, priority:"P1", subAreas:["Centrum","Noord","Zuid","Presikhaaf","Elden","Schuytgraaf"], reviewQuote:"Geweldig geholpen in Arnhem met een nieuwe autosleutel.", reviewAuthor:"J. de Vries", reviewCar:"Volkswagen Golf", geo:{lat:"51.9851",lng:"5.8987"}, popularBrands:["Volkswagen","Opel","Renault"], commonJob:"Transponder sleutel programmeren — defecte chip", localFact:"In Arnhem zien wij veel middenklasse voertuigen met verouderde transponder-systemen. Een defecte chip of gesleten sleutelblad zijn klachten die wij dagelijks ter plaatse oplossen.", avgJobDuration:"30-45 min" },
  { slug:"nijmegen", city:"Nijmegen", region:"Gelderland", country:"NL", lang:"NL", travelTime:"35-50 min", keyword:"autosleutel programmeren Nijmegen", nlSearches:410, priority:"P1", subAreas:["Centrum","Lindenholt","Dukenburg","Oud-West","Nijmegen-Oost"], reviewQuote:"Snel ter plaatse in Nijmegen voor mijn BMW sleutel.", reviewAuthor:"T. Hendriks", reviewCar:"BMW 1 Serie", geo:{lat:"51.8427",lng:"5.8607"}, popularBrands:["Volkswagen","Peugeot","Renault"], commonJob:"Noodopening & goedkopere sleutel dan dealer", localFact:"Nijmegen is een echte studentenstad. Wij ontvangen hier regelmatig spoedoproepen van jonge bestuurders met een krap budget — wij bieden altijd een eerlijke all-in prijs, goedkoper dan de dealer.", avgJobDuration:"30-45 min" },
  { slug:"apeldoorn", city:"Apeldoorn", region:"Gelderland", country:"NL", lang:"NL", travelTime:"35-45 min", keyword:"autosleutel programmeren Apeldoorn", nlSearches:380, priority:"P1", subAreas:["Centrum","Zuid","De Maten","Osseveld","Woudhuis","Ugchelen"], reviewQuote:"Binnen een uur in Apeldoorn. Top service!", reviewAuthor:"M. Bakker", reviewCar:"Ford Focus", geo:{lat:"52.2112",lng:"5.9699"}, popularBrands:["Volkswagen","Ford","Skoda"], commonJob:"Sleutel bijmaken ter plaatse op de oprit of parkeerplaats", localFact:"Apeldoorn bestaat grotendeels uit ruime woonwijken met opritten — ideaal voor onze mobiele service. Wij werken hier regelmatig rechtstreeks bij mensen thuis.", avgJobDuration:"30-45 min" },
  { slug:"almere", city:"Almere", region:"Flevoland", country:"NL", lang:"NL", travelTime:"20-30 min", keyword:"autosleutel programmeren Almere", nlSearches:323, priority:"P1", subAreas:["Almere Stad","Almere Buiten","Almere Haven","Almere Poort","Almere Hout","Pampus"], reviewQuote:"Tesla Model Y keycard programmering. Unieke specialist.", reviewAuthor:"O. van Leeuwen", reviewCar:"Tesla Model Y", geo:{lat:"52.3702",lng:"5.2176"}, popularBrands:["Toyota","Kia","Hyundai"], commonJob:"Smart key programmering Aziatische merken", localFact:"Almere is een van de jongste steden van Nederland met veel Aziatische automodellen zoals Toyota, Kia en Hyundai. Wij programmeren de bijbehorende sleutels direct op locatie.", avgJobDuration:"25-40 min" },
  { slug:"nieuwegein", city:"Nieuwegein", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Nieuwegein", nlSearches:150, priority:"P1", subAreas:["Cityplaza","Jutphaas","Vreeswijk","Batau Noord","Galecop","Fokkerweide"], reviewQuote:"Zeer snelle service in Nieuwegein.", reviewAuthor:"B. Janssen", reviewCar:"Opel Corsa", geo:{lat:"52.0305",lng:"5.0934"}, popularBrands:["Opel","Volkswagen","Ford"], commonJob:"Noodopening parkeergarage Cityplaza & sleutel bijmaken", localFact:"Bij het winkelcentrum Cityplaza in Nieuwegein worden wij regelmatig gebeld voor sleutels die vergeten zijn in de auto. Wij staan u binnen 20 minuten bij.", avgJobDuration:"20-35 min" },
  { slug:"zeist", city:"Zeist", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Zeist", nlSearches:140, priority:"P1", subAreas:["Zeist Centrum","Kerckebosch","Vollenhove","Brugakker"], reviewQuote:"Top service in Zeist voor mijn BMW.", reviewAuthor:"H. van Dijk", reviewCar:"BMW 5 Serie", geo:{lat:"52.0886",lng:"5.2359"}, popularBrands:["BMW","Mercedes-Benz","Audi"], commonJob:"BMW sleutel programmeren & sleutelbehuizing vervangen", localFact:"Zeist is een groene forensengemeente met veel premium-rijders. BMW en Mercedes zijn hier populair, en wij programmeren de bijbehorende sleutels dagelijks ter plaatse.", avgJobDuration:"30-45 min" },
  { slug:"houten", city:"Houten", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Houten", nlSearches:120, priority:"P1", subAreas:["Houten Centrum","Castellum","Zuid","Noord"], reviewQuote:"Goede hulp in Houten.", reviewAuthor:"M. Bos", reviewCar:"Peugeot 208", geo:{lat:"52.0270",lng:"5.1654"}, popularBrands:["Peugeot","Volkswagen","Renault"], commonJob:"Reserve sleutel bijmaken gezinsauto", localFact:"Houten is een compact, fietsvriendelijke gemeente. Een tweede sleutel is hier een slimme investering die wij direct op locatie regelen.", avgJobDuration:"20-35 min" },
  { slug:"breukelen", city:"Breukelen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Breukelen", nlSearches:95, priority:"P1", subAreas:["Breukelen Noord","Breukelen Centrum","Nieuwer Ter Aa","Kockengen"], reviewQuote:"Autosleutel bijmaken was snel geregeld.", reviewAuthor:"F. Hoekstra", reviewCar:"Volvo XC60", geo:{lat:"52.1717",lng:"4.9986"}, popularBrands:["Volvo","BMW","Mercedes-Benz"], commonJob:"Volvo & Scandinavische merken sleutel programmeren", localFact:"Breukelen ligt aan de snelweg A2 en herbergt veel forensenwoningen. Wij worden hier ook gebeld voor voertuigen gestrand langs de A2 — wij rijden direct naar uw locatie.", avgJobDuration:"25-40 min" },

  { slug:"naarden", city:"Naarden", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"10-15 min", keyword:"autosleutel programmeren Naarden", nlSearches:95, priority:"P2", subAreas:["Vesting","Bos van Bredius","Naarderbos","Vierhoven"], reviewQuote:"Vesting Naarden autosleutel kwijt, monteur was er binnen 20 min.", reviewAuthor:"S. de Wit", reviewCar:"Audi A4", geo:{lat:"52.2952",lng:"5.1616"}, popularBrands:["Audi","BMW","Mercedes-Benz"], commonJob:"Smart key inleren premium auto", localFact:"Naarden Vesting trekt veel toeristen en bezoekers — wij worden regelmatig gebeld door mensen die gestrand zijn na een uitje." },
  { slug:"gooise-meren", city:"Gooise Meren", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"10-20 min", keyword:"autosleutel programmeren Gooise Meren", nlSearches:80, priority:"P2", subAreas:["Bussum","Naarden","Muiden","Muiderberg"], reviewQuote:"Snel ter plekke in t Gooi.", reviewAuthor:"P. Heinen", reviewCar:"BMW X3", geo:{lat:"52.2858",lng:"5.1328"}, popularBrands:["BMW","Audi","Mercedes-Benz"], commonJob:"Premium sleutel programmeren", localFact:"t Gooi heeft hoge autobezitdichtheid met premium merken — onze mobiele service past perfect in dit rijke woongebied." },
  { slug:"huizen", city:"Huizen", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Huizen", nlSearches:85, priority:"P2", subAreas:["Huizen Centrum","Gooium","Oostermeent","Zenderwijk"], reviewQuote:"Mijn Kia sleutel deed het niet meer. Ter plaatse in Huizen geprogrammeerd.", reviewAuthor:"M. de Jong", reviewCar:"Kia Picanto", geo:{lat:"52.2989",lng:"5.2536"}, popularBrands:["Kia","Hyundai","Toyota"], commonJob:"Kia & Hyundai smart key programmeren", localFact:"Huizen heeft veel jonge gezinnen met Aziatische voertuigen — wij programmeren deze sleutels snel en goedkoper dan de dealer." },
  { slug:"utrecht-centrum", city:"Utrecht Centrum", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Utrecht Centrum", nlSearches:100, priority:"P2", subAreas:["Binnenstad","Oudwijk","Wittevrouwen","Tolsteeg","Lombok"], reviewQuote:"Snelle service in het centrum.", reviewAuthor:"M. de Boer", reviewCar:"BMW 3 Serie", geo:{lat:"52.0907",lng:"5.1214"}, popularBrands:["Volkswagen","Toyota","BMW"], commonJob:"Noodopening & sleutel bijmaken binnenstad", localFact:"In het Utrechtse centrum werken wij ook in parkeergarages — wij lopen desnoods te voet naar uw voertuig in een smalle binnenstedelijke straat." },
  { slug:"utrecht-zuid", city:"Utrecht Zuid", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Utrecht Zuid", nlSearches:100, priority:"P2", subAreas:["Hoograven","Lunetten","Tolsteeg","Bokkenbuurt"], reviewQuote:"Top service in Zuid.", reviewAuthor:"K. Visser", reviewCar:"VW Golf", geo:{lat:"52.0700",lng:"5.1214"}, popularBrands:["Volkswagen","Opel","Renault"], commonJob:"Sleutel bijmaken bij u thuis", localFact:"Utrecht Zuid bestaat uit rustige woonwijken. Wij parkeren direct voor de deur en voeren de werkzaamheden op de oprit of straat uit." },
  { slug:"amsterdam-centrum", city:"Amsterdam Centrum", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"25-35 min", keyword:"autosleutel programmeren Amsterdam Centrum", nlSearches:180, priority:"P2", subAreas:["Grachtengordel","Jordaan","De Wallen","Nieuwmarkt","Plantage"], reviewQuote:"Midden in Amsterdam gestrand. Snel geholpen.", reviewAuthor:"J. Smit", reviewCar:"Audi A3", geo:{lat:"52.3676",lng:"4.9041"}, popularBrands:["BMW","Audi","Volkswagen"], commonJob:"Noodopening & keyless storing centrum", localFact:"In het Amsterdamse centrum werken wij ook in parkeergarages onder grachtenpanden — u hoeft nergens naartoe, wij komen naar u toe." },
  { slug:"amsterdam-zuid", city:"Amsterdam Zuid", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"25-35 min", keyword:"autosleutel programmeren Amsterdam Zuid", nlSearches:180, priority:"P2", subAreas:["De Pijp","Zuidas","Rivierenbuurt","Oud-Zuid","Buitenveldert"], reviewQuote:"Zuidas service top.", reviewAuthor:"R. de Vries", reviewCar:"Tesla Model 3", geo:{lat:"52.3400",lng:"4.9041"}, popularBrands:["Tesla","BMW","Audi"], commonJob:"Tesla key card & zakelijke sleutel Zuidas", localFact:"De Zuidas is Amsterdams zakenhart met veel lease- en EV-rijders. Tesla key cards en zakelijke sleutels programmeren wij snel en discreet ter plaatse." },
  { slug:"amsterdam-oost", city:"Amsterdam Oost", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"25-35 min", keyword:"autosleutel programmeren Amsterdam Oost", nlSearches:150, priority:"P2", subAreas:["Watergraafsmeer","Indische Buurt","IJburg","Oostpoort"], reviewQuote:"In Amsterdam Oost gestrand met defecte sleutel. Binnen no-time opgelost.", reviewAuthor:"L. Peters", reviewCar:"Volvo V60", geo:{lat:"52.3567",lng:"4.9286"}, popularBrands:["Volvo","Volkswagen","Opel"], commonJob:"Defecte sleutelbehuizing vervangen", localFact:"Amsterdam Oost groeit snel. Wij bedienen zowel de nieuwbouw op IJburg als de oudere straten in de Indische Buurt — altijd op locatie, altijd schadevrij." },
  { slug:"soest", city:"Soest", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Soest", nlSearches:90, priority:"P2", subAreas:["Soestdijk","Smitsveen","Overhees","Soesterberg"], reviewQuote:"Sleutel ter plaatse geprogrammeerd in Soest. Uitstekende service.", reviewAuthor:"J. de Ruiter", reviewCar:"VW Polo", geo:{lat:"52.1736",lng:"5.2913"}, popularBrands:["Volkswagen","Seat","Ford"], commonJob:"Sleutel bijmaken middenklasse voertuig", localFact:"Soest en Soestdijk zijn groene forensengemeenten nabij de A28 — wij zijn er snel bij voor een sleutel die niet meer werkt." },
  { slug:"baarn", city:"Baarn", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Baarn", nlSearches:70, priority:"P2", subAreas:["Baarn Centrum","Oosterhei","Eemdal","Hooge Vuursche"], reviewQuote:"Zeer tevreden over de service in Baarn.", reviewAuthor:"L. de Groot", reviewCar:"Skoda Octavia", geo:{lat:"52.2125",lng:"5.2933"}, popularBrands:["Skoda","Volkswagen","BMW"], commonJob:"Sleutel bijmaken & transponder inleren", localFact:"Baarn is een rustige villawijk nabij paleis Soestdijk. Wij werken hier voor bewoners met luxe of oudere voertuigen die een sleutelspecialist nodig hebben." },
  { slug:"woerden", city:"Woerden", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Woerden", nlSearches:80, priority:"P2", subAreas:["Woerden Centrum","Schilderskwartier","Molenvliet","Waterrijk"], reviewQuote:"Mijn Seat sleutel was kapot, vlot opgelost in Woerden.", reviewAuthor:"P. de Wit", reviewCar:"Seat Ibiza", geo:{lat:"52.0863",lng:"4.8838"}, popularBrands:["Seat","Volkswagen","Renault"], commonJob:"Kapotte sleutelbehuizing & sleutel repareren", localFact:"Woerden ligt op het knooppunt van Utrecht en Den Haag. Sleutelreparaties worden hier snel en ter plaatse uitgevoerd." },
  { slug:"de-bilt", city:"De Bilt", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren De Bilt", nlSearches:70, priority:"P2", subAreas:["De Bilt Centrum","Bilthoven","Maartensdijk","Groenekan"], reviewQuote:"Snelle reservesleutel in De Bilt.", reviewAuthor:"K. Jansen", reviewCar:"Volvo V40", geo:{lat:"52.1093",lng:"5.1833"}, popularBrands:["Volvo","BMW","Volkswagen"], commonJob:"Reserve sleutel bijmaken bij u thuis", localFact:"De Bilt en Bilthoven zijn rustige, groene woonkernen. Wij komen direct naar uw woning voor een reserve sleutel — zonder afspraak vooraf." },
  { slug:"maarssen", city:"Maarssen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Maarssen", nlSearches:65, priority:"P2", subAreas:["Maarssen-Dorp","Maarssenbroek","Op Buuren","Zandweg-Oostwaard"], reviewQuote:"Vriendelijk en snel geholpen in Maarssen.", reviewAuthor:"A. Willems", reviewCar:"Renault Clio", geo:{lat:"52.1408",lng:"5.0396"}, popularBrands:["Renault","Volkswagen","Opel"], commonJob:"Transponder sleutel programmeren", localFact:"Maarssen is een groene woonplaats aan de Vecht. Wij zijn er snel bij voor een sleutel die niet meer werkt." },
  { slug:"ijsselstein", city:"IJsselstein", region:"Utrecht", country:"NL", lang:"NL", travelTime:"18-22 min", keyword:"autosleutel programmeren IJsselstein", nlSearches:60, priority:"P2", subAreas:["IJsselstein Centrum","Achterveld","Zenderpark","Kasteelkwartier"], reviewQuote:"Mijn autosleutel was gestolen. Snel nieuwe gekregen in IJsselstein.", reviewAuthor:"N. Visser", reviewCar:"Ford Focus", geo:{lat:"52.0200",lng:"5.0428"}, popularBrands:["Ford","Volkswagen","Opel"], commonJob:"Noodsleutel na diefstal of verlies", localFact:"Na een autodiefstal blokkeren wij de oude sleutel digitaal en programmeren direct een nieuwe — ook in IJsselstein, binnen 25 minuten ter plaatse." },
  { slug:"vianen", city:"Vianen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"18-25 min", keyword:"autosleutel programmeren Vianen", nlSearches:50, priority:"P2", subAreas:["Vianen Centrum","Monnikenhof","Hoef en Haag","Zederik"], reviewQuote:"Bedrijfswagen sleutel vlot bijgemaakt in Vianen.", reviewAuthor:"W. Brouwer", reviewCar:"Mercedes Sprinter", geo:{lat:"51.9930",lng:"5.0933"}, popularBrands:["Mercedes-Benz","Volkswagen","Ford"], commonJob:"Bedrijfswagen sleutel bijmaken bij bedrijventerrein", localFact:"Vianen heeft grote bedrijventerreinen aan de A2. Wij leveren reserve sleutels voor bestelwagens direct op het terrein — minimale bedrijfsonderbreking." },
  { slug:"bunnik", city:"Bunnik", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Bunnik", nlSearches:45, priority:"P2", subAreas:["Bunnik Centrum","Odijk","Werkhoven"], reviewQuote:"Prima service in Bunnik.", reviewAuthor:"E. de Jong", reviewCar:"VW Up", geo:{lat:"52.0667",lng:"5.2000"}, popularBrands:["Volkswagen","Opel","Toyota"], commonJob:"Kleine auto sleutel bijmaken — betaalbaar", localFact:"Bunnik is een kleine gemeente vlak bij Utrecht. Wij zijn er binnen 20 minuten — ideaal als u geen tijd heeft voor een afspraak bij de dealer." },
  { slug:"abcoude", city:"Abcoude", region:"Utrecht", country:"NL", lang:"NL", travelTime:"15-20 min", keyword:"autosleutel programmeren Abcoude", nlSearches:40, priority:"P2", subAreas:["Abcoude Centrum","Baambrugge","Stokkelaarsbrug"], reviewQuote:"Aanrader in Abcoude.", reviewAuthor:"A. de Ruiter", reviewCar:"Audi A1", geo:{lat:"52.2725",lng:"4.9703"}, popularBrands:["Audi","Volkswagen","BMW"], commonJob:"Sleutel bijmaken woonhuis op oprit", localFact:"Abcoude is een klein dorp tussen Amsterdam en Utrecht. Wij bezoeken beide aangrenzende regio's dagelijks en zijn ook snel bij de kleinste kernen." },
  { slug:"vinkeveen", city:"Vinkeveen", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Vinkeveen", nlSearches:40, priority:"P2", subAreas:["Vinkeveen Centrum","Vinkeveense Plassen","Waverveen","Demmerik"], reviewQuote:"Perfect geholpen in Vinkeveen.", reviewAuthor:"L. van Dijk", reviewCar:"Mini Cooper", geo:{lat:"52.2117",lng:"4.9367"}, popularBrands:["Mini","Volkswagen","Renault"], commonJob:"Sleutel bijmaken recreatiegebied", localFact:"Vinkeveen is populair als recreatiegebied. Wij worden in de zomer regelmatig gebeld door bezoekers die hun sleutel kwijt zijn bij de plassen." },
  { slug:"mijdrecht", city:"Mijdrecht", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Mijdrecht", nlSearches:40, priority:"P2", subAreas:["Mijdrecht Centrum","Proostdijland","Twistvlied","Wickelhof"], reviewQuote:"Goeie service voor mijn bedrijfsauto.", reviewAuthor:"M. Sanders", reviewCar:"VW Transporter", geo:{lat:"52.2047",lng:"4.8647"}, popularBrands:["Volkswagen","Ford","Mercedes-Benz"], commonJob:"Bedrijfsbus sleutel dupliceren", localFact:"Mijdrecht is omgeven door agrarisch en bedrijfsgebied. Wij bedienen hier zowel particulieren als ondernemers met bestelwagens." },
  { slug:"lopik", city:"Lopik", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Lopik", nlSearches:35, priority:"P2", subAreas:["Lopik-dorp","Benschop","Polsbroek","Jaarsveld"], reviewQuote:"Vakkundig en vriendelijk in Lopik.", reviewAuthor:"J. van der Berg", reviewCar:"Renault Trafic", geo:{lat:"51.9723",lng:"4.9453"}, popularBrands:["Renault","Peugeot","Ford"], commonJob:"Transponder inleren oudere bestelwagen", localFact:"Lopik is een landelijke gemeente. Wij rijden ook naar de meest afgelegen kernen — geen extra reiskosten, vaste all-in prijs." },
  { slug:"montfoort", city:"Montfoort", region:"Utrecht", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Montfoort", nlSearches:35, priority:"P2", subAreas:["Montfoort Centrum","Linschoten","Heeswijk"], reviewQuote:"Snel opgelost in Montfoort.", reviewAuthor:"C. Koster", reviewCar:"Fiat 500", geo:{lat:"52.0444",lng:"4.9494"}, popularBrands:["Fiat","Opel","Volkswagen"], commonJob:"Sleutelbehuizing vervangen & sleutel bijmaken", localFact:"Montfoort is een historische vestingstad. Wij zijn er snel bij — ook als u de enige sleutel bent kwijtgeraakt." },
  { slug:"oudewater", city:"Oudewater", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Oudewater", nlSearches:30, priority:"P2", subAreas:["Oudewater Centrum","Hekendorp","Papekop","Driebruggen"], reviewQuote:"Top monteur, sleutel werkt weer als nieuw.", reviewAuthor:"T. Dekker", reviewCar:"Nissan Qashqai", geo:{lat:"52.0238",lng:"4.8736"}, popularBrands:["Nissan","Volkswagen","Toyota"], commonJob:"Sleutel programmeren Nissan & Japanse merken", localFact:"Oudewater is een kleine historische stad. Wij bedienen ook de omliggende polderkernen in de Lopikerwaard zonder extra meerkosten." },
  { slug:"leusden", city:"Leusden", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Leusden", nlSearches:50, priority:"P2", subAreas:["Leusden-Centrum","Achterveld","Stoutenburg","Rossenberg"], reviewQuote:"Autosleutel bijgemaakt in Leusden binnen een half uur.", reviewAuthor:"G. Hendriks", reviewCar:"Opel Corsa", geo:{lat:"52.1326",lng:"5.4294"}, popularBrands:["Opel","Volkswagen","Ford"], commonJob:"Sleutel bijmaken woonwijk", localFact:"Leusden grenst aan Amersfoort en heeft rustige woonwijken. Wij rijden hier regelmatig voor een snel sleutelduplica — direct bij mensen thuis." },
  { slug:"wijk-bij-duurstede", city:"Wijk bij Duurstede", region:"Utrecht", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Wijk bij Duurstede", nlSearches:40, priority:"P2", subAreas:["Wijk bij Duurstede Centrum","Cothen","Langbroek","De Horden"], reviewQuote:"Nieuwe sleutel perfect ingeleerd.", reviewAuthor:"S. Mulder", reviewCar:"Toyota Aygo", geo:{lat:"51.9723",lng:"5.3444"}, popularBrands:["Toyota","Peugeot","Volkswagen"], commonJob:"Toyota sleutel programmeren", localFact:"Wijk bij Duurstede ligt aan de Rijn. Wij bedienen ook de omliggende polderkernen in de Kromme Rijnstreek." },
  { slug:"culemborg", city:"Culemborg", region:"Gelderland", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Culemborg", nlSearches:45, priority:"P2", subAreas:["Culemborg Centrum","Terweijde","Eva Lanxmeer","Parijsch"], reviewQuote:"Mercedes sleutel bijgemaakt in Culemborg. Vakman!", reviewAuthor:"A. Bakker", reviewCar:"Mercedes C-Klasse", geo:{lat:"51.9542",lng:"5.2289"}, popularBrands:["Mercedes-Benz","Volkswagen","Opel"], commonJob:"Mercedes sleutel programmeren ter plaatse", localFact:"Culemborg is een groeiende stad aan de Lek. Wij bedienen zowel de nieuwbouw als het centrum — snel en zonder wegsleepkosten." },
  { slug:"amstelveen", city:"Amstelveen", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"25-30 min", keyword:"autosleutel programmeren Amstelveen", nlSearches:90, priority:"P2", subAreas:["Amstelveen Centrum","Buitenveldert","Uilenstede","Randwijck","Keizer Karelpark"], reviewQuote:"Nieuwe sleutel voor mijn leaseauto, snel en met factuur.", reviewAuthor:"R. Bakker", reviewCar:"Skoda Superb", geo:{lat:"52.3022",lng:"4.8625"}, popularBrands:["Skoda","BMW","Audi"], commonJob:"Leaseauto sleutel bijmaken met factuur", localFact:"Amstelveen herbergt veel internationale bedrijven en expats. Wij leveren sleutels met nette factuur voor lease- en zakelijke voertuigen." },
  { slug:"diemen", city:"Diemen", region:"Noord-Holland", country:"NL", lang:"NL", travelTime:"20-25 min", keyword:"autosleutel programmeren Diemen", nlSearches:60, priority:"P2", subAreas:["Diemen-Noord","Diemen-Centrum","Diemen-Zuid"], reviewQuote:"Sleutel kapot in Diemen, top geregeld.", reviewAuthor:"K. Visser", reviewCar:"Toyota Yaris", geo:{lat:"52.3392",lng:"4.9606"}, popularBrands:["Toyota","Volkswagen","Renault"], commonJob:"Sleutel bijmaken woonwijk Diemen", localFact:"Diemen is een compacte gemeente direct grenzend aan Amsterdam. Wij zijn er snel bij — zowel bij de woonwijken als bij de kantoorgebouwen langs de ring." },
  { slug:"ede", city:"Ede", region:"Gelderland", country:"NL", lang:"NL", travelTime:"30-40 min", keyword:"autosleutel programmeren Ede", nlSearches:120, priority:"P2", subAreas:["Ede Centrum","Rietkampen","Veldhuizen","Kernhem"], reviewQuote:"Binnen 30 minuten in Ede voor een nieuwe autosleutel.", reviewAuthor:"M. van den Berg", reviewCar:"Volkswagen Polo", geo:{lat:"52.0441",lng:"5.6713"}, popularBrands:["Volkswagen","Opel","Ford"], commonJob:"Sleutel kwijt Ede & keyless inleren", localFact:"Ede ligt centraal aan de rand van de Veluwe. Wij zijn er snel bij vanaf de A12 voor pechgevallen en sleutelduplicaties." },
];
