export type City = {
  slug: string; city: string; region: string; country: 'NL' | 'BE' | 'DE';
  lang: 'NL' | 'FR' | 'VL'; population: number; distanceKm: number;
  travelTime: string; keyword: string; nlSearches: number; priority: 'P1'|'P2'|'P3';
  subAreas: string[]; reviewQuote: string; reviewAuthor: string; reviewCar: string;
  geo: { lat: string; lng: string };
};

export const CITIES: City[] = [
  { slug:'eindhoven', city:'Eindhoven', region:'Noord-Brabant', country:'NL', lang:'NL', population:235000, distanceKm:0, travelTime:'15–25 min', keyword:'autosleutel programmeren Eindhoven', nlSearches:480, priority:'P1', subAreas:['Woensel','Stratum','Gestel','Tongelre','Strijp','Veldhoven','Nuenen','Son en Breugel'], reviewQuote:'Binnen 25 minuten ter plaatse, nieuwe BMW sleutel in 90 min.', reviewAuthor:'M. van den Berg', reviewCar:'BMW 5 Serie', geo:{lat:'51.4416',lng:'5.4697'} },
  { slug:'helmond', city:'Helmond', region:'Noord-Brabant', country:'NL', lang:'NL', population:92000, distanceKm:10, travelTime:'15–25 min', keyword:'autosleutel programmeren Helmond', nlSearches:160, priority:'P1', subAreas:['Brandevoort','Rijpelberg','Mierlo-Hout','Dierdonk'], reviewQuote:'Snel en vakkundig. Audi A4 sleutel in 1 uur.', reviewAuthor:'J. Hermans', reviewCar:'Audi A4', geo:{lat:'51.4833',lng:'5.6667'} },
  { slug:'tilburg', city:'Tilburg', region:'Noord-Brabant', country:'NL', lang:'NL', population:222000, distanceKm:20, travelTime:'20–35 min', keyword:'autosleutel programmeren Tilburg', nlSearches:280, priority:'P1', subAreas:['Reeshof','Tilburg-Noord','Udenhout','Berkel-Enschot','Oisterwijk'], reviewQuote:'Volkswagen Golf sleutel kwijt op station Tilburg. Binnen 35 minuten geholpen.', reviewAuthor:'S. de Jong', reviewCar:'VW Golf 8', geo:{lat:'51.5555',lng:'5.0913'} },
  { slug:'den-bosch', city:'Den Bosch', region:'Noord-Brabant', country:'NL', lang:'NL', population:155000, distanceKm:25, travelTime:'25–40 min', keyword:'autosleutel programmeren Den Bosch', nlSearches:230, priority:'P1', subAreas:['Rosmalen','Empel','Maaspoort','Orthen'], reviewQuote:'Mercedes E-klasse contact defect gerepareerd op parkeerplaats. Top service.', reviewAuthor:'R. Mulder', reviewCar:'Mercedes E-Klasse', geo:{lat:'51.6978',lng:'5.3037'} },
  { slug:'breda', city:'Breda', region:'Noord-Brabant', country:'NL', lang:'NL', population:185000, distanceKm:40, travelTime:'35–50 min', keyword:'autosleutel programmeren Breda', nlSearches:250, priority:'P1', subAreas:['Prinsenbeek','Teteringen','Ulvenhout','Bavel'], reviewQuote:'Toyota Prius hybrid sleutel gemaakt zonder origineel. Onmogelijk zei de dealer.', reviewAuthor:'L. Vermeer', reviewCar:'Toyota Prius', geo:{lat:'51.5719',lng:'4.7683'} },
  { slug:'amsterdam', city:'Amsterdam', region:'Noord-Holland', country:'NL', lang:'NL', population:880000, distanceKm:120, travelTime:'70–90 min', keyword:'autosleutel programmeren Amsterdam', nlSearches:580, priority:'P1', subAreas:['Zuid','Oost','Centrum','Noord','West','Amstelveen','Diemen'], reviewQuote:'Porsche Cayenne sleutel kwijt in Amsterdam. Came all the way, fixed in 2 hours. Worth it.', reviewAuthor:'T. Bakker', reviewCar:'Porsche Cayenne', geo:{lat:'52.3676',lng:'4.9041'} },
  { slug:'rotterdam', city:'Rotterdam', region:'Zuid-Holland', country:'NL', lang:'NL', population:650000, distanceKm:95, travelTime:'60–80 min', keyword:'autosleutel programmeren Rotterdam', nlSearches:520, priority:'P1', subAreas:['Centrum','Noord','Zuid','Capelle aan den IJssel','Barendrecht'], reviewQuote:'BMW X5 alle sleutels kwijt. Dealer: 12 dagen. Autosleutel Expert: zelfde dag.', reviewAuthor:'K. Visser', reviewCar:'BMW X5', geo:{lat:'51.9225',lng:'4.4792'} },
  { slug:'den-haag', city:'Den Haag', region:'Zuid-Holland', country:'NL', lang:'NL', population:545000, distanceKm:110, travelTime:'70–85 min', keyword:'autosleutel programmeren Den Haag', nlSearches:420, priority:'P1', subAreas:['Centrum','Scheveningen','Zoetermeer','Rijswijk'], reviewQuote:'Ford Transit sleutel gestolen. Vaste prijs, geen verrassingen. Uitstekend.', reviewAuthor:'P. de Vries', reviewCar:'Ford Transit', geo:{lat:'52.0705',lng:'4.3007'} },
  { slug:'utrecht', city:'Utrecht', region:'Utrecht', country:'NL', lang:'NL', population:360000, distanceKm:90, travelTime:'60–75 min', keyword:'autosleutel programmeren Utrecht', nlSearches:390, priority:'P1', subAreas:['Centrum','Vleuten','De Meern','Maarssen','Nieuwegein'], reviewQuote:'Audi Q5 keyless entry defect. Gerepareerd in 45 minuten. Indrukwekkend.', reviewAuthor:'H. Janssen', reviewCar:'Audi Q5', geo:{lat:'52.0907',lng:'5.1214'} },
  { slug:'oss', city:'Oss', region:'Noord-Brabant', country:'NL', lang:'NL', population:90000, distanceKm:30, travelTime:'25–40 min', keyword:'autosleutel programmeren Oss', nlSearches:100, priority:'P1', subAreas:['Berghem','Ravenstein','Schaijk'], reviewQuote:'Renault Trafic bedrijfswagen sleutel snel gemaakt.', reviewAuthor:'A. Willems', reviewCar:'Renault Trafic', geo:{lat:'51.7667',lng:'5.5167'} },
  { slug:'nijmegen', city:'Nijmegen', region:'Gelderland', country:'NL', lang:'NL', population:177000, distanceKm:55, travelTime:'45–60 min', keyword:'autosleutel programmeren Nijmegen', nlSearches:210, priority:'P2', subAreas:['Centrum','Dukenburg','Lindenholt','Elst'], reviewQuote:'Seat Leon sleutel kwijt in Nijmegen. Snel geholpen.', reviewAuthor:'F. van Dam', reviewCar:'Seat Leon', geo:{lat:'51.8425',lng:'5.8372'} },
  { slug:'arnhem', city:'Arnhem', region:'Gelderland', country:'NL', lang:'NL', population:165000, distanceKm:70, travelTime:'55–70 min', keyword:'autosleutel programmeren Arnhem', nlSearches:190, priority:'P2', subAreas:['Centrum','Malburgen','Presikhaaf','Velp'], reviewQuote:'Honda CR-V sleutel defect. Vakkundig gerepareerd.', reviewAuthor:'C. Hendriks', reviewCar:'Honda CR-V', geo:{lat:'51.9851',lng:'5.8987'} },
  { slug:'maastricht', city:'Maastricht', region:'Limburg', country:'NL', lang:'NL', population:121000, distanceKm:65, travelTime:'50–65 min', keyword:'autosleutel programmeren Maastricht', nlSearches:180, priority:'P2', subAreas:['Centrum','Wyck','Belvédère','Sittard-Geleen'], reviewQuote:'Volvo XC90 sleutel programmering. Prijs ver onder dealer.', reviewAuthor:'E. Smeets', reviewCar:'Volvo XC90', geo:{lat:'50.8514',lng:'5.6909'} },
  { slug:'venlo', city:'Venlo', region:'Limburg', country:'NL', lang:'NL', population:100000, distanceKm:55, travelTime:'45–60 min', keyword:'autosleutel programmeren Venlo', nlSearches:130, priority:'P2', subAreas:['Venlo-Centrum','Blerick','Tegelen','Horst'], reviewQuote:'Opel Vivaro reservesleutel gemaakt voor onze vloot.', reviewAuthor:'B. Janssen', reviewCar:'Opel Vivaro', geo:{lat:'51.3704',lng:'6.1724'} },
  { slug:'roermond', city:'Roermond', region:'Limburg', country:'NL', lang:'NL', population:57000, distanceKm:50, travelTime:'40–55 min', keyword:'autosleutel programmeren Roermond', nlSearches:100, priority:'P2', subAreas:['Centrum','Echt','Weert-nabij'], reviewQuote:'Fiat 500 sleutel bijgemaakt. Snel en vriendelijk.', reviewAuthor:'M. Bos', reviewCar:'Fiat 500', geo:{lat:'51.1930',lng:'5.9875'} },
  { slug:'weert', city:'Weert', region:'Limburg', country:'NL', lang:'NL', population:49000, distanceKm:45, travelTime:'35–50 min', keyword:'autosleutel programmeren Weert', nlSearches:90, priority:'P2', subAreas:['Centrum','Budel','Cranendonck'], reviewQuote:'Hyundai Tucson sleutel snel geregeld.', reviewAuthor:'G. Peters', reviewCar:'Hyundai Tucson', geo:{lat:'51.2494',lng:'5.7071'} },
  { slug:'bergen-op-zoom', city:'Bergen op Zoom', region:'Noord-Brabant', country:'NL', lang:'NL', population:67000, distanceKm:55, travelTime:'45–60 min', keyword:'autosleutel programmeren Bergen op Zoom', nlSearches:90, priority:'P2', subAreas:['Centrum','Roosendaal','Steenbergen'], reviewQuote:'Citroën Berlingo bedrijfssleutel programmering. Perfecte service.', reviewAuthor:'N. de Groot', reviewCar:'Citroën Berlingo', geo:{lat:'51.4975',lng:'4.2892'} },
  { slug:'almere', city:'Almere', region:'Flevoland', country:'NL', lang:'NL', population:215000, distanceKm:135, travelTime:'80–100 min', keyword:'autosleutel programmeren Almere', nlSearches:160, priority:'P2', subAreas:['Almere-Stad','Almere-Haven','Almere-Buiten'], reviewQuote:'Tesla Model Y keycard programmering. Unieke specialist.', reviewAuthor:'O. van Leeuwen', reviewCar:'Tesla Model Y', geo:{lat:'52.3702',lng:'5.2176'} },
  { slug:'amersfoort', city:'Amersfoort', region:'Utrecht', country:'NL', lang:'NL', population:163000, distanceKm:100, travelTime:'65–80 min', keyword:'autosleutel programmeren Amersfoort', nlSearches:140, priority:'P2', subAreas:['Centrum','Vathorst','Soest'], reviewQuote:'Kia Sportage sleutel kwijt. Snel en professioneel.', reviewAuthor:'D. Meijer', reviewCar:'Kia Sportage', geo:{lat:'52.1561',lng:'5.3878'} },
  { slug:'apeldoorn', city:'Apeldoorn', region:'Gelderland', country:'NL', lang:'NL', population:163000, distanceKm:80, travelTime:'55–70 min', keyword:'autosleutel programmeren Apeldoorn', nlSearches:140, priority:'P2', subAreas:['Centrum','Ugchelen','Beekbergen'], reviewQuote:'Mini Cooper sleutel bijgemaakt. BMW platform geen probleem.', reviewAuthor:'I. Kuipers', reviewCar:'Mini Cooper', geo:{lat:'52.2112',lng:'5.9699'} },
  { slug:'enschede', city:'Enschede', region:'Overijssel', country:'NL', lang:'NL', population:158000, distanceKm:105, travelTime:'70–90 min', keyword:'autosleutel programmeren Enschede', nlSearches:150, priority:'P2', subAreas:['Centrum','Hengelo','Almelo'], reviewQuote:'Skoda Octavia sleutel snel gemaakt op locatie.', reviewAuthor:'W. Timmermans', reviewCar:'Skoda Octavia', geo:{lat:'52.2215',lng:'6.8937'} },
  { slug:'haarlem', city:'Haarlem', region:'Noord-Holland', country:'NL', lang:'NL', population:160000, distanceKm:125, travelTime:'80–95 min', keyword:'autosleutel programmeren Haarlem', nlSearches:150, priority:'P2', subAreas:['Centrum','Heemstede','Hoofddorp'], reviewQuote:'Land Rover Discovery sleutel. Hoog ticket, eerlijke prijs.', reviewAuthor:'V. van Rijn', reviewCar:'Land Rover Discovery', geo:{lat:'52.3874',lng:'4.6462'} },
  { slug:'groningen', city:'Groningen', region:'Groningen', country:'NL', lang:'NL', population:230000, distanceKm:200, travelTime:'120–150 min', keyword:'autosleutel programmeren Groningen', nlSearches:210, priority:'P3', subAreas:['Centrum','Hoogezand','Veendam'], reviewQuote:'Ondanks de afstand snel geholpen. BMW 3 Serie sleutel.', reviewAuthor:'P. Smit', reviewCar:'BMW 3 Serie', geo:{lat:'53.2194',lng:'6.5665'} },
  { slug:'zwolle', city:'Zwolle', region:'Overijssel', country:'NL', lang:'NL', population:127000, distanceKm:130, travelTime:'85–105 min', keyword:'autosleutel programmeren Zwolle', nlSearches:130, priority:'P3', subAreas:['Centrum','Kampen','Meppel'], reviewQuote:'Ford Kuga sleutel snel gemaakt. Goede service.', reviewAuthor:'A. Boer', reviewCar:'Ford Kuga', geo:{lat:'52.5168',lng:'6.0830'} },
  { slug:'leiden', city:'Leiden', region:'Zuid-Holland', country:'NL', lang:'NL', population:123000, distanceKm:117, travelTime:'75–90 min', keyword:'autosleutel programmeren Leiden', nlSearches:120, priority:'P3', subAreas:['Centrum','Leiderdorp','Voorschoten'], reviewQuote:'Mazda CX-5 sleutel kwijt. Professioneel geholpen.', reviewAuthor:'C. van Dijk', reviewCar:'Mazda CX-5', geo:{lat:'52.1601',lng:'4.4970'} },
  { slug:'delft', city:'Delft', region:'Zuid-Holland', country:'NL', lang:'NL', population:103000, distanceKm:108, travelTime:'70–85 min', keyword:'autosleutel programmeren Delft', nlSearches:130, priority:'P3', subAreas:['Centrum','Pijnacker','Lansingerland'], reviewQuote:'Renault Clio sleutel bijgemaakt. Snel en goedkoop.', reviewAuthor:'T. de Wit', reviewCar:'Renault Clio', geo:{lat:'52.0116',lng:'4.3571'} },
  // ---- BELGIUM ----
  { slug:'antwerpen', city:'Antwerpen', region:'Antwerpen', country:'BE', lang:'VL', population:530000, distanceKm:65, travelTime:'50–70 min', keyword:'autoslotenmaker Antwerpen', nlSearches:480, priority:'P1', subAreas:['Centrum','Berchem','Borgerhout','Merksem','Hoboken','Wilrijk'], reviewQuote:'BMW 5 Serie sleutel kwijt in Antwerpen. Binnen 60 min geholpen.', reviewAuthor:'J. De Smedt', reviewCar:'BMW 5 Serie', geo:{lat:'51.2194',lng:'4.4025'} },
  { slug:'gent', city:'Gent', region:'Oost-Vlaanderen', country:'BE', lang:'VL', population:260000, distanceKm:120, travelTime:'80–100 min', keyword:'autoslotenmaker Gent', nlSearches:390, priority:'P1', subAreas:['Centrum','Ledeberg','Gentbrugge','Merelbeke'], reviewQuote:'Volkswagen Golf sleutel programmering op locatie. Perfect.', reviewAuthor:'L. Claes', reviewCar:'VW Golf 7', geo:{lat:'51.0543',lng:'3.7174'} },
  { slug:'bruxelles-brussel', city:'Brussel', region:'Brussels Hoofdstedelijk Gewest', country:'BE', lang:'FR', population:185000, distanceKm:130, travelTime:'90–110 min', keyword:'autoslotenmaker Brussel / serrurier auto Bruxelles', nlSearches:720, priority:'P1', subAreas:['Ixelles','Uccle','Schaarbeek','Anderlecht','Etterbeek','Molenbeek'], reviewQuote:'Service rapide et professionnel à Bruxelles. Clé Mercedes faite en 1h30.', reviewAuthor:'P. Dupont', reviewCar:'Mercedes C-Klasse', geo:{lat:'50.8503',lng:'4.3517'} },
  { slug:'leuven', city:'Leuven', region:'Vlaams-Brabant', country:'BE', lang:'VL', population:101000, distanceKm:110, travelTime:'75–90 min', keyword:'autoslotenmaker Leuven', nlSearches:220, priority:'P2', subAreas:['Centrum','Heverlee','Kessel-Lo','Haasrode'], reviewQuote:'Toyota C-HR sleutel gemaakt op universiteitscampus. Snel.', reviewAuthor:'S. Wouters', reviewCar:'Toyota C-HR', geo:{lat:'50.8798',lng:'4.7005'} },
  { slug:'mechelen', city:'Mechelen', region:'Antwerpen', country:'BE', lang:'VL', population:87000, distanceKm:90, travelTime:'65–80 min', keyword:'autoslotenmaker Mechelen', nlSearches:180, priority:'P2', subAreas:['Centrum','Leest','Bonheiden'], reviewQuote:'Peugeot 3008 keyless sleutel geprogrammeerd. Goede prijs.', reviewAuthor:'R. Mertens', reviewCar:'Peugeot 3008', geo:{lat:'51.0280',lng:'4.4804'} },
  { slug:'hasselt', city:'Hasselt', region:'Limburg', country:'BE', lang:'VL', population:78000, distanceKm:80, travelTime:'60–75 min', keyword:'autoslotenmaker Hasselt', nlSearches:160, priority:'P2', subAreas:['Centrum','Genk-nabij','Diepenbeek'], reviewQuote:'Opel Astra sleutel kwijt. Snel geholpen in Hasselt.', reviewAuthor:'K. Peeters', reviewCar:'Opel Astra', geo:{lat:'50.9311',lng:'5.3378'} },
  { slug:'brugge', city:'Brugge', region:'West-Vlaanderen', country:'BE', lang:'VL', population:118000, distanceKm:175, travelTime:'110–135 min', keyword:'autoslotenmaker Brugge', nlSearches:200, priority:'P2', subAreas:['Centrum','Sint-Andries','Assebroek'], reviewQuote:'Dacia Duster sleutel bijgemaakt. Uitstekende service.', reviewAuthor:'M. Desmet', reviewCar:'Dacia Duster', geo:{lat:'51.2093',lng:'3.2247'} },
  { slug:'liege', city:'Liège', region:'Liège', country:'BE', lang:'FR', population:197000, distanceKm:115, travelTime:'80–100 min', keyword:'serrurier auto Liège', nlSearches:290, priority:'P2', subAreas:['Centre','Seraing','Herstal','Beyne-Heusay'], reviewQuote:'Clé Renault Mégane perdue. Service rapide et prix correct.', reviewAuthor:'C. Lambert', reviewCar:'Renault Mégane', geo:{lat:'50.6326',lng:'5.5797'} },
  { slug:'genk', city:'Genk', region:'Limburg', country:'BE', lang:'VL', population:66000, distanceKm:75, travelTime:'60–75 min', keyword:'autoslotenmaker Genk', nlSearches:150, priority:'P2', subAreas:['Centrum','Winterslag','Waterschei'], reviewQuote:'Kia Sportage sleutel snel gemaakt in Genk.', reviewAuthor:'N. Claessen', reviewCar:'Kia Sportage', geo:{lat:'50.9651',lng:'5.5003'} },
  { slug:'kortrijk', city:'Kortrijk', region:'West-Vlaanderen', country:'BE', lang:'VL', population:77000, distanceKm:160, travelTime:'100–120 min', keyword:'autoslotenmaker Kortrijk', nlSearches:160, priority:'P2', subAreas:['Centrum','Harelbeke','Kuurne'], reviewQuote:'Citroën DS3 sleutel bijgemaakt. Correcte dienstverlening.', reviewAuthor:'B. Vandenberghe', reviewCar:'Citroën DS3', geo:{lat:'50.8282',lng:'3.2642'} },
  { slug:'charleroi', city:'Charleroi', region:'Hainaut', country:'BE', lang:'FR', population:202000, distanceKm:160, travelTime:'105–130 min', keyword:'serrurier auto Charleroi', nlSearches:210, priority:'P3', subAreas:['Centre','Montignies','Marchienne'], reviewQuote:'Intervention rapide pour clé Peugeot 208 à Charleroi.', reviewAuthor:'D. Lecomte', reviewCar:'Peugeot 208', geo:{lat:'50.4108',lng:'4.4446'} },
  { slug:'namur', city:'Namur', region:'Namur', country:'BE', lang:'FR', population:112000, distanceKm:155, travelTime:'100–125 min', keyword:'serrurier auto Namur', nlSearches:150, priority:'P3', subAreas:['Centre','Jambes','Wépion'], reviewQuote:'Clé Ford Focus perdue. Service mobile excellent.', reviewAuthor:'A. Simon', reviewCar:'Ford Focus', geo:{lat:'50.4670',lng:'4.8720'} },
  { slug:'aalst', city:'Aalst', region:'Oost-Vlaanderen', country:'BE', lang:'VL', population:87000, distanceKm:130, travelTime:'85–105 min', keyword:'autoslotenmaker Aalst', nlSearches:120, priority:'P3', subAreas:['Centrum','Ninove','Geraardsbergen'], reviewQuote:'VW Polo sleutel snel gemaakt. Eerlijke prijs.', reviewAuthor:'H. De Cock', reviewCar:'VW Polo', geo:{lat:'50.9403',lng:'4.0367'} },
];
