export interface Location {
  slug: string;
  city: string;
  region: string;
  country: string;
  geo: { lat: string; lng: string };
  travelTime: string;
  subAreas: string[];
  reviewQuote: string;
  reviewAuthor: string;
  reviewCar: string;
}

export const LOCATIONS: Location[] = [
  {
    slug: 'autosleutel-bijmaken-tilburg',
    city: 'Tilburg',
    region: 'Noord-Brabant',
    country: 'NL',
    geo: { lat: '51.5606', lng: '5.0919' },
    travelTime: '30 minuten',
    subAreas: ['Berkel-Enschot', 'Udenhout', 'Goirle', 'Oisterwijk', 'Hilvarenbeek'],
    reviewQuote: 'Sleutel van mijn Audi kwijt op Tilburg station. Gebeld om 20:00, ze waren er om 20:35. Nieuwe sleutel geprogrammeerd om 21:30. Ongelooflijke service.',
    reviewAuthor: 'Thomas',
    reviewCar: 'Audi A4, Tilburg',
  },
  {
    slug: 'autosleutel-bijmaken-breda',
    city: 'Breda',
    region: 'Noord-Brabant',
    country: 'NL',
    geo: { lat: '51.5719', lng: '4.7683' },
    travelTime: '45 minuten',
    subAreas: ['Prinsenbeek', 'Teteringen', 'Ulvenhout', 'Bavel', 'Ginneken'],
    reviewQuote: 'BMW alle sleutels kwijt in Breda centrum. Deze mannen kwamen in 50 minuten. Vakwerk, eerlijke prijs. Aanrader!',
    reviewAuthor: 'Kevin',
    reviewCar: 'BMW 3-serie, Breda',
  },
  {
    slug: 'autosleutel-bijmaken-den-bosch',
    city: 'Den Bosch',
    region: 'Noord-Brabant',
    country: 'NL',
    geo: { lat: '51.6978', lng: '5.3037' },
    travelTime: '25 minuten',
    subAreas: ["'s-Hertogenbosch", 'Rosmalen', 'Vught', 'Empel', 'Engelen'],
    reviewQuote: "Mercedes sleutel kapot op de A2. Binnen 35 minuten stond de bus naast me. Nieuwe sleutel ter plaatse. Fantastisch.",
    reviewAuthor: 'Sandra',
    reviewCar: 'Mercedes C-klasse, Den Bosch',
  },
  {
    slug: 'autosleutel-bijmaken-helmond',
    city: 'Helmond',
    region: 'Noord-Brabant',
    country: 'NL',
    geo: { lat: '51.4822', lng: '5.6567' },
    travelTime: '20 minuten',
    subAreas: ['Brandevoort', 'Dierdonk', 'Stiphout', 'Mierlo', 'Geldrop'],
    reviewQuote: 'VW Golf sleutel kwijt voor mijn werk in Helmond. In 25 minuten opgelost. Professioneel en snel!',
    reviewAuthor: 'Jeroen',
    reviewCar: 'VW Golf 7, Helmond',
  },
  {
    slug: 'autosleutel-bijmaken-weert',
    city: 'Weert',
    region: 'Limburg',
    country: 'NL',
    geo: { lat: '51.2493', lng: '5.7072' },
    travelTime: '35 minuten',
    subAreas: ['Stramproy', 'Budel', 'Cranendonck', 'Ospel', 'Laar'],
    reviewQuote: 'Toyota hybride sleutel kwijt in Weert. Dealer zei 2 weken wachten. Deze specialist was er in 40 minuten en loste alles op!',
    reviewAuthor: 'Marjan',
    reviewCar: 'Toyota Corolla Hybrid, Weert',
  },
  {
    slug: 'autosleutel-bijmaken-venlo',
    city: 'Venlo',
    region: 'Limburg',
    country: 'NL',
    geo: { lat: '51.3697', lng: '6.1724' },
    travelTime: '50 minuten',
    subAreas: ['Blerick', 'Tegelen', 'Belfeld', 'Arcen', 'Bergen'],
    reviewQuote: 'Ford Transit sleutels verloren in Venlo. Super snel geholpen, vaste prijs, geen verrassingen. Top service.',
    reviewAuthor: 'Rob',
    reviewCar: 'Ford Transit, Venlo',
  },
  {
    slug: 'autosleutel-bijmaken-roermond',
    city: 'Roermond',
    region: 'Limburg',
    country: 'NL',
    geo: { lat: '51.1941', lng: '5.9878' },
    travelTime: '45 minuten',
    subAreas: ['Echt', 'Montfort', 'Swalmen', 'Maasbree', 'Helden'],
    reviewQuote: 'Opel Astra sleutel kwijt. In Roermond dezelfde dag geholpen. Veel goedkoper dan de dealer. Aanrader!',
    reviewAuthor: 'Lisa',
    reviewCar: 'Opel Astra, Roermond',
  },
  {
    slug: 'autosleutel-bijmaken-maastricht',
    city: 'Maastricht',
    region: 'Limburg',
    country: 'NL',
    geo: { lat: '50.8514', lng: '5.6910' },
    travelTime: '60 minuten',
    subAreas: ['Wyck', 'Borgharen', 'Itteren', 'Meerssen', 'Valkenburg'],
    reviewQuote: 'Volvo XC60 sleutel kwijt in Maastricht. Ze kwamen van Eindhoven, waren er op tijd en losten alles op. Geweldig!',
    reviewAuthor: 'Patrick',
    reviewCar: 'Volvo XC60, Maastricht',
  },
  {
    slug: 'autosleutel-bijmaken-utrecht',
    city: 'Utrecht',
    region: 'Utrecht',
    country: 'NL',
    geo: { lat: '52.0907', lng: '5.1214' },
    travelTime: '60 minuten',
    subAreas: ['Houten', 'Nieuwegein', 'IJsselstein', 'Vianen', 'Maarssen'],
    reviewQuote: 'BMW alle sleutels kwijt in Utrecht. Dealer wilde €1.400. Deze jongens deden het voor €580 en kwamen naar mij toe!',
    reviewAuthor: 'Niels',
    reviewCar: 'BMW 5-serie, Utrecht',
  },
  {
    slug: 'autosleutel-bijmaken-arnhem',
    city: 'Arnhem',
    region: 'Gelderland',
    country: 'NL',
    geo: { lat: '51.9851', lng: '5.8987' },
    travelTime: '70 minuten',
    subAreas: ['Velp', 'Duiven', 'Zevenaar', 'Westervoort', 'Elst'],
    reviewQuote: 'Audi A3 sleutel kwijt in Arnhem. Super professioneel, kwamen snel, eerlijke prijs. Zeker aanbevelen!',
    reviewAuthor: 'Sanne',
    reviewCar: 'Audi A3, Arnhem',
  },
  {
    slug: 'autosleutel-bijmaken-nijmegen',
    city: 'Nijmegen',
    region: 'Gelderland',
    country: 'NL',
    geo: { lat: '51.8425', lng: '5.8372' },
    travelTime: '55 minuten',
    subAreas: ['Beuningen', 'Wijchen', 'Druten', 'Groesbeek', 'Berg en Dal'],
    reviewQuote: 'VW Polo sleutel verloren. In Nijmegen dezelfde dag nieuwe sleutel. Goede prijs en vriendelijk personeel.',
    reviewAuthor: 'Emma',
    reviewCar: 'VW Polo, Nijmegen',
  },
  {
    slug: 'autosleutel-bijmaken-rotterdam',
    city: 'Rotterdam',
    region: 'Zuid-Holland',
    country: 'NL',
    geo: { lat: '51.9225', lng: '4.4792' },
    travelTime: '75 minuten',
    subAreas: ['Capelle aan den IJssel', 'Spijkenisse', 'Ridderkerk', 'Barendrecht', 'Schiedam'],
    reviewQuote: 'Mercedes GLE sleutel gestolen in Rotterdam. Snel ter plaatse, alle sleutels opnieuw geprogrammeerd. Geweldig werk!',
    reviewAuthor: 'David',
    reviewCar: 'Mercedes GLE, Rotterdam',
  },
  {
    slug: 'autosleutel-bijmaken-den-haag',
    city: 'Den Haag',
    region: 'Zuid-Holland',
    country: 'NL',
    geo: { lat: '52.0705', lng: '4.3007' },
    travelTime: '90 minuten',
    subAreas: ['Rijswijk', 'Zoetermeer', 'Delft', 'Wassenaar', 'Leidschendam'],
    reviewQuote: 'Lexus RX sleutel kwijt in Den Haag. Geweldig dat ze zo ver kwamen. Professioneel en snel opgelost!',
    reviewAuthor: 'Christine',
    reviewCar: 'Lexus RX, Den Haag',
  },
  {
    slug: 'autosleutel-bijmaken-amsterdam',
    city: 'Amsterdam',
    region: 'Noord-Holland',
    country: 'NL',
    geo: { lat: '52.3676', lng: '4.9041' },
    travelTime: '90 minuten',
    subAreas: ['Amstelveen', 'Diemen', 'Ouder-Amstel', 'Zaandam', 'Haarlem'],
    reviewQuote: 'BMW alle sleutels kwijt in Amsterdam-Centrum. Ze kwamen van Eindhoven en losten alles op. Top service!',
    reviewAuthor: 'Marco',
    reviewCar: 'BMW X5, Amsterdam',
  },
  {
    slug: 'autosleutel-bijmaken-antwerpen',
    city: 'Antwerpen',
    region: 'Antwerpen',
    country: 'BE',
    geo: { lat: '51.2194', lng: '4.4025' },
    travelTime: '60 minuten',
    subAreas: ['Merksem', 'Berchem', 'Hoboken', 'Wilrijk', 'Edegem'],
    reviewQuote: 'Audi Q5 sleutel kwijt in Antwerpen. Grensoverschrijdende service! Snel, professioneel en goede prijs.',
    reviewAuthor: 'Filip',
    reviewCar: 'Audi Q5, Antwerpen',
  },
  {
    slug: 'autosleutel-bijmaken-brussel',
    city: 'Brussel',
    region: 'Brussel Hoofdstedelijk Gewest',
    country: 'BE',
    geo: { lat: '50.8503', lng: '4.3517' },
    travelTime: '90 minuten',
    subAreas: ['Etterbeek', 'Ixelles', 'Anderlecht', 'Schaarbeek', 'Vilvoorde'],
    reviewQuote: 'Mercedes sleutel kwijt in Brussel. Ze kwamen snel, alles perfect opgelost. Echte professionals!',
    reviewAuthor: 'Jean-Pierre',
    reviewCar: 'Mercedes E-klasse, Brussel',
  },
  {
    slug: 'autosleutel-bijmaken-leuven',
    city: 'Leuven',
    region: 'Vlaams-Brabant',
    country: 'BE',
    geo: { lat: '50.8798', lng: '4.7005' },
    travelTime: '75 minuten',
    subAreas: ['Heverlee', 'Kessel-Lo', 'Wilsele', 'Haasrode', 'Tervuren'],
    reviewQuote: 'VW Golf sleutel kwijt in Leuven. Super snelle reactie, vakkundige service. Zeker aanbevolen!',
    reviewAuthor: 'Sofie',
    reviewCar: 'VW Golf 8, Leuven',
  },
  {
    slug: 'autosleutel-bijmaken-hasselt',
    city: 'Hasselt',
    region: 'Limburg',
    country: 'BE',
    geo: { lat: '50.9307', lng: '5.3382' },
    travelTime: '50 minuten',
    subAreas: ['Genk', 'Diepenbeek', 'Lummen', 'Heusden-Zolder', 'Sint-Truiden'],
    reviewQuote: 'BMW F30 sleutel kwijt in Hasselt. In 55 minuten ter plaatse en alles opgelost. Geweldige service!',
    reviewAuthor: 'Pieter',
    reviewCar: 'BMW 320i, Hasselt',
  },
  {
    slug: 'autosleutel-bijmaken-lommel',
    city: 'Lommel',
    region: 'Limburg',
    country: 'BE',
    geo: { lat: '51.2280', lng: '5.3147' },
    travelTime: '35 minuten',
    subAreas: ['Neerpelt', 'Overpelt', 'Pelt', 'Hechtel-Eksel', 'Balen'],
    reviewQuote: 'Toyota Yaris sleutel verloren in Lommel. Snel geholpen, vriendelijk en eerlijke prijs. Top!',
    reviewAuthor: 'Annelies',
    reviewCar: 'Toyota Yaris, Lommel',
  },
  {
    slug: 'autosleutel-bijmaken-dusseldorf',
    city: 'Düsseldorf',
    region: 'Nordrhein-Westfalen',
    country: 'DE',
    geo: { lat: '51.2217', lng: '6.7762' },
    travelTime: '75 minuten',
    subAreas: ['Duisburg', 'Krefeld', 'Mönchengladbach', 'Neuss', 'Ratingen'],
    reviewQuote: 'BMW sleutel kwijt in Düsseldorf. Grensoverschrijdend — geen probleem! Uitstekende service.',
    reviewAuthor: 'Klaus',
    reviewCar: 'BMW 7-serie, Düsseldorf',
  },
  {
    slug: 'autosleutel-bijmaken-keulen',
    city: 'Keulen',
    region: 'Nordrhein-Westfalen',
    country: 'DE',
    geo: { lat: '50.9333', lng: '6.9500' },
    travelTime: '100 minuten',
    subAreas: ['Leverkusen', 'Bergisch Gladbach', 'Frechen', 'Pulheim', 'Brühl'],
    reviewQuote: 'Audi A6 sleutel probleem in Keulen. Ze kwamen van Nederland — geweldige service en eerlijke prijs!',
    reviewAuthor: 'Hans',
    reviewCar: 'Audi A6, Keulen',
  },
  {
    slug: 'autosleutel-bijmaken-aachen',
    city: 'Aachen',
    region: 'Nordrhein-Westfalen',
    country: 'DE',
    geo: { lat: '50.7753', lng: '6.0839' },
    travelTime: '60 minuten',
    subAreas: ['Herzogenrath', 'Alsdorf', 'Würselen', 'Baesweiler', 'Stolberg'],
    reviewQuote: 'Mercedes GLC sleutel kwijt bij de grens. Perfecte service, snel en professioneel. Dankjewel!',
    reviewAuthor: 'Petra',
    reviewCar: 'Mercedes GLC, Aachen',
  },
];
