export interface Service {
  slug: string;
  title: string;
  shortTitle: string;
  icon: string;
  price: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  h1: string;
  color: string;
  excerpt: string;
}

export const SERVICES: Service[] = [
  {
    slug: 'autosleutel-bijmaken-eindhoven',
    title: 'Autosleutel Bijmaken',
    shortTitle: 'Bijmaken',
    icon: '🗝️',
    price: 'Vanaf €180',
    metaTitle: 'Autosleutel Bijmaken Eindhoven | Alle Merken | Mobiel & Ter Plaatse',
    metaDescription: 'Professioneel autosleutel bijmaken in Eindhoven. Alle merken, alle modellen. Transponder sleutels, smart keys, keyless entry. Wij komen naar u toe. 30-60 min.',
    keywords: ['autosleutel bijmaken eindhoven', 'autosleutel vervangen', 'reserve autosleutel', 'transponder sleutel programmeren'],
    h1: 'Autosleutel Bijmaken Eindhoven — Mobiel & Ter Plaatse',
    color: '#0f62fe',
    excerpt: 'Reserve autosleutel nodig of sleutel kwijt? Wij programmeren alle sleuteltypes ter plaatse — geen sleepkosten.',
  },
  {
    slug: 'alle-sleutels-kwijt-auto',
    title: 'Alle Sleutels Kwijt',
    shortTitle: 'AKL Spoed',
    icon: '🚨',
    price: 'Spoed AKL',
    metaTitle: 'Alle Sleutels Kwijt? | Spoed Autosleutel Service Eindhoven | 24/7',
    metaDescription: 'Alle autosleutels kwijt? Spoed mobiele service in Eindhoven. BMW, Mercedes, Audi, VW, Toyota. Geen sleepkosten nodig. Wij maken sleutels ter plaatse. 30 min. 24/7.',
    keywords: ['alle sleutels kwijt auto', 'autosleutel kwijt eindhoven', 'spoed autosleutel', 'geen reserve sleutel auto'],
    h1: 'Alle Sleutels Kwijt? Wij Komen naar U Toe — Spoed Service',
    color: '#da1e28',
    excerpt: '24/7 spoed service bij verlies van alle autosleutels. BMW, Mercedes, VW, Toyota — alle merken opgelost.',
  },
  {
    slug: 'bmw-sleutel-bijmaken-eindhoven',
    title: 'BMW Sleutel Specialist',
    shortTitle: 'BMW',
    icon: '🔵',
    price: 'Vanaf €220',
    metaTitle: 'BMW Sleutel Bijmaken Eindhoven | FEM/BDC/CAS | ECU-Niveau',
    metaDescription: 'BMW sleutel programmering specialist in Eindhoven. E/F/G chassis, CAS3/4, FEM/BDC, BDC2. Dealer alternatief. Bench EEPROM, ISN extractie. Service op dezelfde dag.',
    keywords: ['BMW sleutel bijmaken eindhoven', 'BMW FEM sleutel', 'BMW BDC sleutel', 'BMW CAS4 sleutel', 'BMW alle sleutels kwijt'],
    h1: 'BMW Sleutel Bijmaken Eindhoven — FEM/BDC/CAS Specialist',
    color: '#1d4ed8',
    excerpt: 'Specialist in BMW E/F/G chassis sleutelprogrammering. CAS3, CAS4, FEM/BDC — dealer-niveau zonder dealer-prijs.',
  },
  {
    slug: 'mercedes-sleutel-vervangen-eindhoven',
    title: 'Mercedes Sleutel Specialist',
    shortTitle: 'Mercedes',
    icon: '⭐',
    price: 'Vanaf €250',
    metaTitle: 'Mercedes Sleutel Vervangen Eindhoven | FBS3/FBS4 | Mobiel',
    metaDescription: 'Mercedes sleutel vervangen in Eindhoven. FBS3 AKL, FBS4 oplossingen, EIS/ELV reparatie. G-Box 3, AVDI. Telefoon-als-sleutel tijdelijk. Mobiele service.',
    keywords: ['Mercedes sleutel vervangen eindhoven', 'Mercedes FBS3 sleutel', 'Mercedes EIS reparatie', 'Mercedes sleutel kwijt'],
    h1: 'Mercedes Sleutel Vervangen Eindhoven — FBS3/FBS4 Specialist',
    color: '#4b5563',
    excerpt: 'FBS3 wachtwoord berekening, EIS/ELV reparatie, FBS4 oplossingen. De Mercedes specialist die dealers niet kunnen evenaren.',
  },
  {
    slug: 'vw-audi-sleutel-bijmaken-eindhoven',
    title: 'VW & Audi Sleutel Specialist',
    shortTitle: 'VW/Audi',
    icon: '🔧',
    price: 'Vanaf €180',
    metaTitle: 'VW/Audi Sleutel Bijmaken Eindhoven | MQB/SFD/MLB Unlock',
    metaDescription: 'VW/Audi sleutel programmering in Eindhoven. MQB/MQB48, SFD unlock, MLB platform. Golf 8, ID.3, A3, A4, Q5, Porsche. Dealer-niveau zonder dealer wachtrij.',
    keywords: ['VW sleutel bijmaken eindhoven', 'Audi sleutel programmeren', 'VW Golf 8 sleutel', 'SFD unlock', 'MQB48 sleutel'],
    h1: 'VW/Audi Sleutel Bijmaken — MQB48, SFD, MLB Specialist',
    color: '#1565c0',
    excerpt: 'MQB48, SFD unlock, MLB platform — de meest complexe VAG systemen zijn geen probleem voor ons team.',
  },
  {
    slug: 'toyota-sleutel-vervangen-eindhoven',
    title: 'Toyota & Lexus Sleutel Specialist',
    shortTitle: 'Toyota/Lexus',
    icon: '🔴',
    price: 'Vanaf €200',
    metaTitle: 'Toyota/Lexus Sleutel Vervangen Eindhoven | Hybride AKL | Bypass',
    metaDescription: 'Toyota/Lexus sleutel vervangen in Eindhoven. 2019+ AKL bypass kabel, hybride systemen, smart key. Lonsdor K518 specialist. Mobiele service op dezelfde dag.',
    keywords: ['Toyota sleutel vervangen eindhoven', 'Lexus sleutel vervangen', 'Toyota hybride sleutel', 'Toyota AKL bypass'],
    h1: 'Toyota & Lexus Sleutel Vervangen — 2019+ AKL Specialist',
    color: '#dc2626',
    excerpt: '2019+ Toyota vereist speciale 30-PIN bypass kabel. Wij hebben de tools en kennis voor hybride sleutelprogrammering.',
  },
  {
    slug: 'volvo-sleutel-programmeren-eindhoven',
    title: 'Volvo Sleutel Specialist',
    shortTitle: 'Volvo',
    icon: '🛡️',
    price: 'Vanaf €220',
    metaTitle: 'Volvo Sleutel Programmeren Eindhoven | SPA/CMA Platform | Mobiel',
    metaDescription: 'Volvo sleutel programmeren in Eindhoven. P2/P3/SPA/CMA platform. Lonsdor veilige methode. XC60, XC90, V40, S60, V60. Service op dezelfde dag. Bel nu.',
    keywords: ['Volvo sleutel programmeren eindhoven', 'Volvo sleutel bijmaken', 'Volvo SPA sleutel', 'Volvo XC60 sleutel'],
    h1: 'Volvo Sleutel Programmeren Eindhoven — SPA/CMA Specialist',
    color: '#1e3a5f',
    excerpt: 'P2, P3, SPA en CMA platform — veilige Lonsdor methode zonder brick-risico voor uw Volvo.',
  },
  {
    slug: 'ecu-clonen-component-protection',
    title: 'ECU Clonen & CP Verwijdering',
    shortTitle: 'ECU/CP',
    icon: '💻',
    price: 'Vanaf €200',
    metaTitle: 'ECU Clonen & Component Protection Verwijderen | Hersenchirurg Niveau',
    metaDescription: 'Gebruikte ECU/BCM adaptatie, component protection verwijdering, ISN extractie. BMW, Mercedes, VW/Audi. Wat dealers niet kunnen, wij wel. Eindhoven & regio.',
    keywords: ['ECU clonen eindhoven', 'component protection verwijderen', 'ISN extractie BMW', 'CP verwijderen VW'],
    h1: 'ECU Clonen & Component Protection Verwijderen — Elite Service',
    color: '#7c3aed',
    excerpt: 'Waterschade, ongeval, gebruikte modules — wij redden uw auto waar dealers stoppen. ISN extractie, ECU klonen, CP verwijdering.',
  },
  {
    slug: 'ghost-immobiliser-installeren',
    title: 'Ghost Immobiliser Installatie',
    shortTitle: 'Ghost',
    icon: '👻',
    price: 'Vanaf €399',
    metaTitle: 'Ghost Immobiliser Installeren Eindhoven | CAN Bus Beveiliging',
    metaDescription: 'Ghost immobiliser installatie in Eindhoven. CAN bus bescherming tegen sleutel klonen & relay attacks. BMW, Mercedes, Audi, VW, Toyota. Verzekering goedgekeurd.',
    keywords: ['ghost immobiliser eindhoven', 'CAN bus immobilizer', 'relay attack bescherming', 'auto beveiliging eindhoven'],
    h1: 'Ghost Immobiliser Installatie — Ultieme CAN Bus Bescherming',
    color: '#059669',
    excerpt: 'TASSA gecertificeerd, ondetecteerbaar voor dieven, verzekering goedgekeurd. De beste anti-diefstal oplossing voor uw auto.',
  },
  {
    slug: 'bedrijfswagen-sleutel-beheer',
    title: 'Bedrijfswagen Sleutel Beheer',
    shortTitle: 'B2B/Fleet',
    icon: '🚐',
    price: 'Vanaf €90/klus',
    metaTitle: 'Bedrijfswagen Sleutel Beheer | B2B Auto Sleutel Service | Eindhoven',
    metaDescription: 'Bedrijfswagen sleutel beheer voor bedrijven in Eindhoven & Brainport. Prioriteit service, digitale sleutels, bulk prijzen. Fleet contracten. Vraag offerte aan.',
    keywords: ['bedrijfswagen sleutel beheer', 'zakelijk auto sleutel service', 'fleet sleutel vervanging', 'car sharing sleutel beheer'],
    h1: 'Bedrijfswagen Sleutel Beheer — Verminder Downtime, Bespaar Kosten',
    color: '#0891b2',
    excerpt: 'Prioriteit service, reserve sleutel programma, digitale sleutels via MoboKey. B2B oplossingen voor fleets van alle groottes.',
  },
];

export const BLOG_POSTS = [
  {
    slug: 'alle-sleutels-kwijt-wat-nu-eindhoven',
    title: 'Wat te Doen als U Alle Autosleutels Kwijt Bent in Eindhoven',
    excerpt: 'Paniek hoeft niet. Volg deze stappen en u rijdt binnen 60 minuten weer.',
    keywords: ['alle sleutels kwijt eindhoven', 'autosleutel kwijt wat doen'],
    publishDate: '2026-01-15',
    readTime: '5 min',
  },
  {
    slug: 'autosleutel-kosten-per-merk-2026',
    title: 'Autosleutel Vervangingskosten per Merk 2026',
    excerpt: 'BMW, Mercedes, Audi, VW, Toyota — wat kost een nieuwe autosleutel echt?',
    keywords: ['autosleutel kosten', 'prijs autosleutel per merk 2026'],
    publishDate: '2026-01-22',
    readTime: '7 min',
  },
  {
    slug: 'dealer-vs-slotenmaker-kostenverschil',
    title: 'Dealer vs Slotenmaker: Het Echte Kostenverschil',
    excerpt: 'Zelf onderzoek gedaan: dealer vs mobiele specialist. De cijfers zijn verbluffend.',
    keywords: ['dealer vs slotenmaker kosten', 'autosleutel dealer vergelijking'],
    publishDate: '2026-01-29',
    readTime: '6 min',
  },
  {
    slug: 'verzekering-dekt-autosleutel-vervangen',
    title: 'Wordt Autosleutel Vervanging Vergoed door de Verzekering in NL?',
    excerpt: 'All Risk, WA+, of WA? Wij leggen uit welke polissen vergoeden en hoe u claimt.',
    keywords: ['verzekering dekt autosleutel', 'autosleutel verzekering claim'],
    publishDate: '2026-02-05',
    readTime: '5 min',
  },
  {
    slug: 'sfd-lock-vw-golf-8-uitleg',
    title: 'Wat Is SFD Lock op VW Golf 8? (En Hoe Wij Het Ontgrendelen)',
    excerpt: 'SFD is de reden waarom uw Golf 8 sleutel zo duur is — maar niet bij ons.',
    keywords: ['SFD lock VW Golf 8', 'SFD unlock eindhoven'],
    publishDate: '2026-02-12',
    readTime: '8 min',
  },
  {
    slug: 'bmw-bdc2-sleutel-bijmaken-2026',
    title: 'BMW BDC2 Sleutel Bijmaken: Is Het Mogelijk in 2026?',
    excerpt: 'BDC2 is de moeilijkste BMW. Wij leggen uit wat kan en wat niet.',
    keywords: ['BMW BDC2 sleutel bijmaken', 'BMW G chassis sleutel'],
    publishDate: '2026-02-19',
    readTime: '6 min',
  },
  {
    slug: 'ghost-immobiliser-eindhoven',
    title: 'Ghost Immobiliser: Waarom Elke Keyless Auto in Eindhoven Er Een Nodig Heeft',
    excerpt: 'Relay attacks in Brainport nemen toe. Ghost immobiliser is de definitieve oplossing.',
    keywords: ['ghost immobiliser eindhoven', 'relay attack bescherming'],
    publishDate: '2026-02-26',
    readTime: '5 min',
  },
  {
    slug: 'faraday-pouch-bescherming-relay-attack',
    title: 'Faraday Pouch: Het €50 Apparaat Dat Uw €30.000 Auto Beschermt',
    excerpt: 'Keyless entry is handig maar gevaarlijk. Faraday pouch + Ghost = maximale bescherming.',
    keywords: ['faraday pouch bescherming', 'relay attack voorkomen'],
    publishDate: '2026-03-05',
    readTime: '4 min',
  },
  {
    slug: 'toyota-hybride-sleutel-vervangen',
    title: 'Toyota Hybride Sleutel Vervangen: Wat Maakt Het Anders',
    excerpt: 'Hybride systemen vereisen extra voorzorgsmaatregelen. Onze specialist legt het uit.',
    keywords: ['Toyota hybride sleutel', 'Prius Corolla sleutel vervangen'],
    publishDate: '2026-03-12',
    readTime: '6 min',
  },
  {
    slug: 'case-study-bmw-besparing',
    title: 'Hoe Wij een BMW Eigenaar €1.200 Bespaarden',
    excerpt: 'Echte casus: BMW X5, alle sleutels kwijt. Dealer: €1.800. Wij: €650. Zelfde dag.',
    keywords: ['BMW besparing casus', 'BMW alle sleutels kwijt eindhoven'],
    publishDate: '2026-03-19',
    readTime: '4 min',
  },
];
