'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Banknote, CreditCard, FileText, QrCode, RefreshCw } from 'lucide-react';
import { ui, Card, CardHead, Row, Badge, Empty, Notice } from '../../_ui';

export interface PaymentRow {
  id: string;
  amount: number;
  method: string;
  status: 'open' | 'betaald' | 'mislukt' | 'terugbetaald';
  checkout_url: string | null;
  commission_amount: number | null;
  paid_at: string | null;
  received_by: string | null;
}

const METHOD_LABEL: Record<string, string> = {
  ideal: 'iDEAL',
  contant: 'Contant',
  pin: 'Pin',
  tikkie: 'Tikkie',
  bank: 'Overboeking',
  factuur: 'Op rekening',
};

const euro = (value: number) => `€ ${value.toFixed(2).replace('.', ',')}`;

/**
 * Taking the money, at the door.
 *
 * Three ways, because a customer at 03:00 is not a customer in a shop: an
 * iDEAL request they scan with their own banking app, cash counted into a hand,
 * or an account for the garages and lease companies who will not pay at a kerb.
 *
 * iDEAL first, and on purpose. It needs no card reader, no Android, and no
 * enrolment — and unlike Tikkie or a separate terminal the job marks itself
 * paid, so nobody at the office has to find out later whether the money
 * arrived. That reconciliation is the whole argument; the rates are a detail.
 */
export default function PaymentPanel({
  jobId,
  due,
  payments,
}: {
  jobId: string;
  due: number;
  payments: PaymentRow[];
}) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<{ text: string; tone: 'ok' | 'bad' } | null>(null);
  const [link, setLink] = useState<string | null>(
    payments.find((p) => p.method === 'ideal' && p.status === 'open')?.checkout_url ?? null
  );

  const settled = payments.filter((p) => p.status === 'betaald');
  const received = settled.reduce((total, p) => total + Number(p.amount), 0);
  const outstanding = Math.max(0, due - received);

  async function take(method: string) {
    setBusy(method);
    setNotice(null);

    const response = await fetch(`/api/admin/jobs/${jobId}/payment`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ method }),
    }).catch(() => null);

    const result = await response?.json().catch(() => null);
    setBusy(null);

    if (!response?.ok) {
      setNotice({ text: result?.error ?? 'Er ging iets mis.', tone: 'bad' });
      return;
    }
    if (result.checkoutUrl) setLink(result.checkoutUrl);
    setNotice({ text: result.say, tone: 'ok' });
    router.refresh();
  }

  return (
    <>
      <Card>
        <CardHead>Betaling</CardHead>

        {notice && (
          <div style={{ padding: 'var(--sp-4) var(--sp-5) 0' }}>
            <Notice tone={notice.tone}>{notice.text}</Notice>
          </div>
        )}

        <div className={ui.row}>
          <div className={ui.rowMain}>
            <div className={ui.rowTitleLine}>
              <span className={ui.rowTitle}>{euro(due)}</span>
              {received > 0 && <span className={ui.rowNote}>{euro(received)} ontvangen</span>}
            </div>
            <div className={ui.rowMeta}>
              {outstanding > 0 ? (
                <Badge tone="warn">{euro(outstanding)} open</Badge>
              ) : (
                <Badge tone="ok">volledig betaald</Badge>
              )}
            </div>
          </div>
        </div>

        {outstanding > 0 && (
          <div className={ui.row} style={{ gap: 'var(--sp-2)', flexWrap: 'wrap' }}>
            <button
              className={`${ui.btn} ${ui.btnPrimary}`}
              onClick={() => take('ideal')}
              disabled={busy !== null}
            >
              <QrCode size={15} strokeWidth={2} />
              {busy === 'ideal' ? 'Bezig…' : 'iDEAL-verzoek'}
            </button>
            <button className={ui.btn} onClick={() => take('contant')} disabled={busy !== null}>
              <Banknote size={15} strokeWidth={1.9} />
              Contant ontvangen
            </button>
            <button className={ui.btn} onClick={() => take('pin')} disabled={busy !== null}>
              <CreditCard size={15} strokeWidth={1.9} />
              Pin
            </button>
            <button className={ui.btn} onClick={() => take('factuur')} disabled={busy !== null}>
              <FileText size={15} strokeWidth={1.9} />
              Op rekening
            </button>
          </div>
        )}

        {/*
          The QR is generated by Mollie's own hosted page. Rendering a code
          ourselves would mean a QR library in the bundle and a second thing to
          keep in step with their checkout — the phone shows their page, the
          customer scans, and it is Mollie's problem to keep working.
        */}
        {link && (
          <div className={ui.row} style={{ gap: 'var(--sp-3)', flexWrap: 'wrap' }}>
            <div className={ui.rowMain}>
              <div className={ui.rowTitleLine}>
                <span className={ui.rowTitle}>Laat de klant dit scannen</span>
              </div>
              <div className={ui.rowMeta}>
                <span className={ui.hint}>
                  Open de link en houd het scherm voor de klant. Zodra hij betaalt, staat het hier.
                </span>
              </div>
            </div>
            <div className={ui.rowActions}>
              <a className={`${ui.btn} ${ui.btnPrimary}`} href={link} target="_blank" rel="noopener noreferrer">
                <QrCode size={15} strokeWidth={2} />
                Betaalscherm openen
              </a>
              <button className={ui.btn} onClick={() => router.refresh()} title="Is er al betaald?">
                <RefreshCw size={15} strokeWidth={1.9} />
              </button>
            </div>
          </div>
        )}

        {payments.length === 0 && <Empty>Nog niets ontvangen op deze klus.</Empty>}

        {payments.map((payment) => (
          <Row
            key={payment.id}
            title={euro(Number(payment.amount))}
            note={METHOD_LABEL[payment.method] ?? payment.method}
            meta={
              <>
                <Badge
                  tone={
                    payment.status === 'betaald' ? 'ok'
                    : payment.status === 'open' ? 'warn'
                    : 'stop'
                  }
                >
                  {payment.status === 'open' && payment.method === 'factuur'
                    ? 'te factureren'
                    : payment.status}
                </Badge>
                {payment.received_by && <Badge>in handen van de monteur</Badge>}
                {payment.commission_amount != null && (
                  <Badge>commissie {euro(Number(payment.commission_amount))}</Badge>
                )}
                {payment.paid_at && payment.status === 'betaald' && (
                  <span className={ui.hint}>
                    {new Date(payment.paid_at).toLocaleString('nl-NL', {
                      day: '2-digit',
                      month: 'short',
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </span>
                )}
              </>
            }
          />
        ))}
      </Card>
    </>
  );
}
